//>>built
define("codemirror4/test/doc_test",["dojo","dijit","dojox"],function(s,t,u){(function(){function n(a,b){if(a){n.prototype=a;var d=new n;if(b)for(var e in b)b.hasOwnProperty(e)&&(d[e]=b[e]);return d}}function c(a){var b=arguments.length,d=null;"string"==typeof arguments[b-1]&&(d=arguments[--b]);if(e==b)throw Error("No editors provided to eqAll");for(var e=1;e<b;++e)eq(arguments[e].getValue(),a,d)}function f(a,b,d,e,c){e||(e={});return test("doc_"+a,function(){for(var a=document.getElementById("testground"),
c=b,f=e,p={},h=[];c;){var g=c.match(/^(\w+)(\*?)(?:='([^\']*)'|<(~?)(\w+)(?:\/(\d+)-(\d+))?)\s*/),q=g[1],m=g[2];if(g[3])m=m?CodeMirror.Doc(g[3]):CodeMirror(a,n(f,{value:g[3]}));else{var k=g[5];p.hasOwnProperty(k)||(p[k]=h.length,h.push(CodeMirror(a,f)));k=h[p[k]].linkedDoc({sharedHist:!g[4],from:g[6]?Number(g[6]):null,to:g[7]?Number(g[7]):null});m=m?k:CodeMirror(a,n(f,{value:k}))}p[q]=h.length;h.push(m);c=c.slice(g[0].length)}c=!1;try{d.apply(null,h),c=!0}finally{if(!c||verbose)a.style.visibility=
"visible";else for(c=0;c<h.length;++c)h[c]instanceof CodeMirror&&a.removeChild(h[c].getWrapperElement())}},c)}function q(a,b){c("x",a,b);a.setValue("hey");c("hey",a,b);b.setValue("wow");c("wow",a,b);a.replaceRange("u\nv\nw",Pos(0,3));b.replaceRange("i",Pos(0,4));b.replaceRange("j",Pos(2,1));c("wowui\nv\nwj",a,b)}var r=/MSIE [1-7]\b/.test(navigator.userAgent);f("basic","A\x3d'x' B\x3cA",q);f("basicSeparate","A\x3d'x' B\x3c~A",q);f("sharedHist","A\x3d'ab\ncd\nef' B\x3cA",function(a,b){a.replaceRange("x",
Pos(0));b.replaceRange("y",Pos(1));a.replaceRange("z",Pos(2));c("abx\ncdy\nefz",a,b);a.undo();a.undo();c("abx\ncd\nef",a,b);a.redo();c("abx\ncdy\nef",a,b);b.redo();c("abx\ncdy\nefz",a,b);a.undo();b.undo();a.undo();a.undo();c("ab\ncd\nef",a,b)},null,r);f("undoIntact","A\x3d'ab\ncd\nef' B\x3c~A",function(a,b){a.replaceRange("x",Pos(0));b.replaceRange("y",Pos(1));a.replaceRange("z",Pos(2));a.replaceRange("q",Pos(0));c("abxq\ncdy\nefz",a,b);a.undo();a.undo();c("abx\ncdy\nef",a,b);b.undo();c("abx\ncd\nef",
a,b);a.redo();c("abx\ncd\nefz",a,b);a.redo();c("abxq\ncd\nefz",a,b);a.undo();a.undo();a.undo();a.undo();c("ab\ncd\nef",a,b);b.redo();c("ab\ncdy\nef",a,b)});f("undoConflict","A\x3d'ab\ncd\nef' B\x3c~A",function(a,b){a.replaceRange("x",Pos(0));a.replaceRange("z",Pos(2));b.replaceRange("y",Pos(0));a.undo();a.undo();c("abxy\ncd\nef",a,b);a.replaceRange("u",Pos(2));a.replaceRange("v",Pos(0));b.replaceRange("w",Pos(0));a.undo();a.undo();c("abxyvw\ncd\nefu",a,b)});f("doubleRebase","A\x3d'ab\ncd\nef\ng' B\x3c~A C\x3cB",
function(a,b,d){d.replaceRange("u",Pos(3));a.replaceRange("",Pos(0,0),Pos(1,0));d.undo();c("cd\nef\ng",a,b,d)});f("undoUpdate","A\x3d'ab\ncd\nef' B\x3c~A",function(a,b){a.replaceRange("x",Pos(2));b.replaceRange("u\nv\nw\n",Pos(0,0));a.undo();c("u\nv\nw\nab\ncd\nef",a,b);a.redo();c("u\nv\nw\nab\ncd\nefx",a,b);a.undo();c("u\nv\nw\nab\ncd\nef",a,b);b.undo();a.redo();c("ab\ncd\nefx",a,b);a.undo();c("ab\ncd\nef",a,b)});f("undoKeepRanges","A\x3d'abcdefg' B\x3cA",function(a,b){var d=a.markText(Pos(0,1),
Pos(0,3),{className:"foo"});b.replaceRange("x",Pos(0,0));eqPos(d.find().from,Pos(0,2));b.replaceRange("yzzy",Pos(0,1),Pos(0));eq(d.find(),null);b.undo();eqPos(d.find().from,Pos(0,2));b.undo();eqPos(d.find().from,Pos(0,1))});f("longChain","A\x3d'uv' B\x3cA C\x3cB D\x3cC",function(a,b,d,e){a.replaceSelection("X");c("Xuv",a,b,d,e);e.replaceRange("Y",Pos(0));c("XuvY",a,b,d,e)});f("broadCast","B\x3cA C\x3cA D\x3cA E\x3cA",function(a,b,d,e,f){b.setValue("uu");c("uu",a,b,d,e,f);a.replaceRange("v",Pos(0,
1));c("uvu",a,b,d,e,f)});f("islands","A\x3d'x\ny\nz' B\x3cA C\x3c~A D\x3cC",function(a,b,d,e){a.replaceRange("u",Pos(0));e.replaceRange("v",Pos(2));b.undo();c("x\ny\nzv",a,b,d,e);d.undo();c("x\ny\nz",a,b,d,e);a.redo();c("xu\ny\nz",a,b,d,e);e.redo();c("xu\ny\nzv",a,b,d,e)});f("unlink","B\x3cA C\x3cA D\x3cB",function(a,b,d,e){a.setValue("hi");b.unlinkDoc(a);e.setValue("aye");c("hi",a,d);c("aye",b,e);a.setValue("oo");c("oo",a,d);c("aye",b,e)});f("bareDoc","A*\x3d'foo' B*\x3cA C\x3cB",function(a,b,d){is(a instanceof
CodeMirror.Doc);is(b instanceof CodeMirror.Doc);is(d instanceof CodeMirror);c("foo",a,b,d);a.replaceRange("hey",Pos(0,0),Pos(0));d.replaceRange("!",Pos(0));c("hey!",a,b,d);b.unlinkDoc(a);b.setValue("x");c("x",b,d);c("hey!",a)});f("swapDoc","A\x3d'a' B*\x3d'b' C\x3cA",function(a,b,d){var e=a.swapDoc(b);e.setValue("x");c("x",d,e);c("b",a,b)});f("docKeepsScroll","A\x3d'x' B*\x3d'y'",function(a,b){addDoc(a,200,200);a.scrollIntoView(Pos(199,200));var d=a.swapDoc(b);a.swapDoc(d);d=a.getScrollInfo();is(0<
d.left,"not at left");is(0<d.top,"not at top")});f("copyDoc","A\x3d'u'",function(a){var b=a.getDoc().copy(!0);a.setValue("foo");b.setValue("bar");b=a.swapDoc(b);eq(a.getValue(),"bar");a.undo();eq(a.getValue(),"u");a.swapDoc(b);eq(a.getValue(),"foo");eq(b.historySize().undo,1);eq(b.copy(!1).historySize().undo,0)});f("docKeepsMode","A\x3d'1+1'",function(a){var b=CodeMirror.Doc("hi","text/x-markdown");a.setOption("mode","text/javascript");b=a.swapDoc(b);eq(a.getOption("mode"),"text/x-markdown");eq(a.getMode().name,
"markdown");a.swapDoc(b);eq(a.getOption("mode"),"text/javascript");eq(a.getMode().name,"javascript")});f("subview","A\x3d'1\n2\n3\n4\n5' B\x3c~A/1-3",function(a,b){eq(b.getValue(),"2\n3");eq(b.firstLine(),1);b.setCursor(Pos(4));eqPos(b.getCursor(),Pos(2,1));a.replaceRange("-1\n0\n",Pos(0,0));eq(b.firstLine(),3);eqPos(b.getCursor(),Pos(4,1));a.undo();eqPos(b.getCursor(),Pos(2,1));b.replaceRange("oyoy\n",Pos(2,0));eq(a.getValue(),"1\n2\noyoy\n3\n4\n5");b.undo();eq(a.getValue(),"1\n2\n3\n4\n5")});f("subviewEditOnBoundary",
"A\x3d'11\n22\n33\n44\n55' B\x3c~A/1-4",function(a,b){a.replaceRange("x\nyy\nz",Pos(0,1),Pos(2,1));eq(b.firstLine(),2);eq(b.lineCount(),2);eq(b.getValue(),"z3\n44");a.replaceRange("q\nrr\ns",Pos(3,1),Pos(4,1));eq(b.firstLine(),2);eq(b.getValue(),"z3\n4q");eq(a.getValue(),"1x\nyy\nz3\n4q\nrr\ns5");a.execCommand("selectAll");a.replaceSelection("!");c("!",a,b)});f("sharedMarker","A\x3d'ab\ncd\nef\ngh' B\x3cA C\x3c~A/1-2",function(a,b,d){var c=b.markText(Pos(0,1),Pos(3,1),{className:"cm-searching",shared:!0}),
f=a.findMarksAt(Pos(0,2));eq(f.length,1);eq(f[0],c);eq(d.findMarksAt(Pos(1,1)).length,1);eqPos(c.find().from,Pos(0,1));eqPos(c.find().to,Pos(3,1));b.replaceRange("x\ny\n",Pos(0,0));eqPos(c.find().from,Pos(2,1));eqPos(c.find().to,Pos(5,1));var l=0;CodeMirror.on(c,"clear",function(){++l});b.operation(function(){c.clear()});eq(a.findMarksAt(Pos(3,1)).length,0);eq(b.findMarksAt(Pos(3,1)).length,0);eq(d.findMarksAt(Pos(3,1)).length,0);eq(c.find(),null);eq(l,1)});f("sharedMarkerCopy","A\x3d'abcde'",function(a){var b=
a.markText(Pos(0,1),Pos(0,3),{shared:!0});a=a.linkedDoc();var c=a.findMarksAt(Pos(0,2));eq(c.length,1);eq(c[0],b);b.clear();eq(a.findMarksAt(Pos(0,2)),0)});f("sharedMarkerDetach","A\x3d'abcde' B\x3cA C\x3cB",function(a,b,c){var e=a.markText(Pos(0,1),Pos(0,3),{shared:!0});a.unlinkDoc(b);a=b.findMarksAt(Pos(0,2));eq(a.length,1);is(a[0]!=e);c=c.findMarksAt(Pos(0,2));eq(c.length,1);is(c[0]!=e);c[0].clear();is(e.find())});f("sharedBookmark","A\x3d'ab\ncd\nef\ngh' B\x3cA C\x3c~A/1-2",function(a,b,c){var e=
b.setBookmark(Pos(1,1),{shared:!0}),f=a.findMarksAt(Pos(1,1));eq(f.length,1);eq(f[0],e);eq(c.findMarksAt(Pos(1,1)).length,1);eqPos(e.find(),Pos(1,1));b.replaceRange("x\ny\n",Pos(0,0));eqPos(e.find(),Pos(3,1));var l=0;CodeMirror.on(e,"clear",function(){++l});b.operation(function(){e.clear()});eq(a.findMarks(Pos(0,0),Pos(5)).length,0);eq(b.findMarks(Pos(0,0),Pos(5)).length,0);eq(c.findMarks(Pos(0,0),Pos(5)).length,0);eq(e.find(),null);eq(l,1)});f("undoInSubview","A\x3d'line 0\nline 1\nline 2\nline 3\nline 4' B\x3cA/1-4",
function(a,b){b.replaceRange("x",Pos(2,0));a.undo();eq(a.getValue(),"line 0\nline 1\nline 2\nline 3\nline 4");eq(b.getValue(),"line 1\nline 2\nline 3")})})()});
//# sourceMappingURL=doc_test.js.map