//>>built
(function(k){"object"==typeof exports&&"object"==typeof module?k(require("../../lib/codemirror"),require("../python/python"),require("../stex/stex"),require("../../addon/mode/overlay")):"function"==typeof define&&define.amd?define("codemirror4/mode/rst/rst",["../../lib/codemirror","../python/python","../stex/stex","../../addon/mode/overlay"],k):k(CodeMirror)})(function(k){k.defineMode("rst",function(l,h){var u=/^\*\*[^\*\s](?:[^\*]*[^\*\s])?\*\*/,f=/^\*[^\*\s](?:[^\*]*[^\*\s])?\*/,e=/^``[^`\s](?:[^`]*[^`\s])``/,
m=/^(?:[\d]+(?:[\.,]\d+)*)/,y=/^(?:\s\+[\d]+(?:[\.,]\d+)*)/,z=/^(?:\s\-[\d]+(?:[\.,]\d+)*)/,v=/^[Hh][Tt][Tt][Pp][Ss]?:\/\/(?:[\d\w.-]+)\.(?:\w{2,6})(?:\/[\d\w\#\%\&\-\.\,\/\:\=\?\~]+)*/,w=k.getMode(l,h.backdrop||"rst-base");return k.overlayMode(w,{token:function(d){if(d.match(u)&&d.match(/\W+|$/,!1))return"strong";if(d.match(f)&&d.match(/\W+|$/,!1))return"em";if(d.match(e)&&d.match(/\W+|$/,!1))return"string-2";if(d.match(m))return"number";if(d.match(y))return"positive";if(d.match(z))return"negative";
if(d.match(v))return"link";for(;null!=d.next()&&!d.match(u,!1)&&!d.match(f,!1)&&!d.match(e,!1)&&!d.match(m,!1)&&!d.match(y,!1)&&!d.match(z,!1)&&!d.match(v,!1););return null}},!0)},"python","stex");k.defineMode("rst-base",function(l){function h(b){var a=Array.prototype.slice.call(arguments,1);return b.replace(/{(\d+)}/g,function(b,c){return"undefined"!=typeof a[c]?a[c]:b})}function u(b){this.message=b}function f(b,a){if(!b)throw new u(a);return b}function e(b,a){var g=null;if(b.sol()&&b.match(I,!1))c(a,
w,{mode:A,local:k.startState(A)});else if(b.sol()&&b.match(J))c(a,m),g="meta";else if(b.sol()&&b.match(K))c(a,e),g="header";else if(a.ctx.phase==n||b.match(n,!1))switch(p(a)){case 0:c(a,e,d(n,1));f(b.match(/^:/));g="meta";break;case 1:c(a,e,d(n,2));f(b.match(E));g="keyword";b.current().match(/^(?:math|latex)/)&&(a.tmp_stex=!0);break;case 2:c(a,e,d(n,3));f(b.match(/^:`/));g="meta";break;case 3:a.tmp_stex&&(a.tmp_stex=void 0,a.tmp={mode:B,local:k.startState(B)});if(a.tmp){if("`"==b.peek()){c(a,e,d(n,
4));a.tmp=void 0;break}g=a.tmp.mode.token(b,a.tmp.local);break}c(a,e,d(n,4));f(b.match(F));g="string";break;case 4:c(a,e,d(n,5));f(b.match(/^`/));g="meta";break;case 5:c(a,e,d(n,6));f(b.match(G));break;default:c(a,e),f(""==b.current())}else if(a.ctx.phase==q||b.match(q,!1))switch(p(a)){case 0:c(a,e,d(q,1));f(b.match(/^`/));g="meta";break;case 1:c(a,e,d(q,2));f(b.match(F));g="string";break;case 2:c(a,e,d(q,3));f(b.match(/^`:/));g="meta";break;case 3:c(a,e,d(q,4));f(b.match(E));g="keyword";break;case 4:c(a,
e,d(q,5));f(b.match(/^:/));g="meta";break;case 5:c(a,e,d(q,6));f(b.match(G));break;default:c(a,e),f(""==b.current())}else if(a.ctx.phase==s||b.match(s,!1))switch(p(a)){case 0:c(a,e,d(s,1));f(b.match(/^:/));g="meta";break;case 1:c(a,e,d(s,2));f(b.match(E));g="keyword";break;case 2:c(a,e,d(s,3));f(b.match(/^:/));g="meta";break;case 3:c(a,e,d(s,4));f(b.match(G));break;default:c(a,e),f(""==b.current())}else if(a.ctx.phase==C||b.match(C,!1))switch(p(a)){case 0:c(a,e,d(C,1));f(b.match(H));g="variable-2";
break;case 1:c(a,e,d(C,2));b.match(/^_?_?/)&&(g="link");break;default:c(a,e),f(""==b.current())}else if(b.match(L))c(a,e),g="quote";else if(b.match(M))c(a,e),g="quote";else if(b.match(N)){if(c(a,e),!b.peek()||b.peek().match(/^\W$/))g="link"}else if(a.ctx.phase==r||b.match(r,!1))switch(p(a)){case 0:!b.peek()||b.peek().match(/^\W$/)?c(a,e,d(r,1)):b.match(r);break;case 1:c(a,e,d(r,2));f(b.match(/^`/));g="link";break;case 2:c(a,e,d(r,3));f(b.match(F));break;case 3:c(a,e,d(r,4));f(b.match(/^`_/));g="link";
break;default:c(a,e),f(""==b.current())}else b.match(O)?c(a,z):b.next()&&c(a,e);return g}function m(b,a){var g=null;if(a.ctx.phase==t||b.match(t,!1))switch(p(a)){case 0:c(a,m,d(t,1));f(b.match(H));g="variable-2";break;case 1:c(a,m,d(t,2));f(b.match(P));break;case 2:c(a,m,d(t,3));f(b.match(Q));g="keyword";break;case 3:c(a,m,d(t,4));f(b.match(R));g="meta";break;default:c(a,e),f(""==b.current())}else if(a.ctx.phase==x||b.match(x,!1))switch(p(a)){case 0:c(a,m,d(x,1));f(b.match(S));g="keyword";b.current().match(/^(?:math|latex)/)?
a.tmp_stex=!0:b.current().match(/^python/)&&(a.tmp_py=!0);break;case 1:c(a,m,d(x,2));f(b.match(T));g="meta";if(b.match(/^latex\s*$/)||a.tmp_stex)a.tmp_stex=void 0,c(a,w,{mode:B,local:k.startState(B)});break;case 2:c(a,m,d(x,3));if(b.match(/^python\s*$/)||a.tmp_py)a.tmp_py=void 0,c(a,w,{mode:A,local:k.startState(A)});break;default:c(a,e),f(""==b.current())}else if(a.ctx.phase==D||b.match(D,!1))switch(p(a)){case 0:c(a,m,d(D,1));f(b.match(U));f(b.match(V));g="link";break;case 1:c(a,m,d(D,2));f(b.match(W));
g="meta";break;default:c(a,e),f(""==b.current())}else b.match(X)?(c(a,e),g="quote"):b.match(Y)?(c(a,e),g="quote"):(b.eatSpace(),b.eol()?c(a,e):(b.skipToEnd(),c(a,y),g="comment"));return g}function y(b,a){return v(b,a,"comment")}function z(b,a){return v(b,a,"meta")}function v(b,a,d){if(b.eol()||b.eatSpace())return b.skipToEnd(),d;c(a,e);return null}function w(b,a){if(a.ctx.mode&&a.ctx.local)return b.sol()?(b.eatSpace()||c(a,e),null):a.ctx.mode.token(b,a.ctx.local);c(a,e);return null}function d(b,a,
c,d){return{phase:b,stage:a,mode:c,local:d}}function c(b,a,c){b.tok=a;b.ctx=c||{}}function p(b){return b.ctx.stage||0}u.prototype.toString=function(){return"AssertException: "+this.message};var A=k.getMode(l,"python"),B=k.getMode(l,"stex"),G=RegExp(h("^{0}","(?:\\s*|\\W|$)")),E=RegExp(h("^{0}","(?:[^\\W\\d_](?:[\\w!\"#$%\x26'()\\*\\+,\\-\\./:;\x3c\x3d\x3e\\?]*[^\\W_])?)"));l=h("(?:{0}|`{1}`)","(?:[^\\W\\d_](?:[\\w!\"#$%\x26'()\\*\\+,\\-\\./:;\x3c\x3d\x3e\\?]*[^\\W_])?)","(?:[^\\W\\d_](?:[\\w\\s!\"#$%\x26'()\\*\\+,\\-\\./:;\x3c\x3d\x3e\\?]*[^\\W_])?)");
var F=RegExp(h("^{0}","(?:[^\\`]+)")),K=/^([!'#$%&"()*+,-./:;<=>?@\[\\\]^_`{|}~])\1{3,}\s*$/,J=RegExp(h("^\\.\\.{0}","\\s+")),D=RegExp(h("^_{0}:{1}|^__:{1}",l,"(?:\\s*|\\W|$)")),x=RegExp(h("^{0}::{1}",l,"(?:\\s*|\\W|$)")),t=RegExp(h("^\\|{0}\\|{1}{2}::{3}","(?:[^\\s\\|](?:[^\\|]*[^\\s\\|])?)","\\s+",l,"(?:\\s*|\\W|$)")),X=RegExp(h("^\\[(?:\\d+|#{0}?|\\*)]{1}",l,"(?:\\s*|\\W|$)")),Y=RegExp(h("^\\[{0}\\]{1}",l,"(?:\\s*|\\W|$)")),C=RegExp(h("^\\|{0}\\|","(?:[^\\s\\|](?:[^\\|]*[^\\s\\|])?)")),L=RegExp(h("^\\[(?:\\d+|#{0}?|\\*)]_",
l)),M=RegExp(h("^\\[{0}\\]_",l)),N=RegExp(h("^{0}__?",l)),r=RegExp(h("^`{0}`_","(?:[^\\`]+)")),n=RegExp(h("^:{0}:`{1}`{2}","(?:[^\\W\\d_](?:[\\w!\"#$%\x26'()\\*\\+,\\-\\./:;\x3c\x3d\x3e\\?]*[^\\W_])?)","(?:[^\\`]+)","(?:\\s*|\\W|$)")),q=RegExp(h("^`{1}`:{0}:{2}","(?:[^\\W\\d_](?:[\\w!\"#$%\x26'()\\*\\+,\\-\\./:;\x3c\x3d\x3e\\?]*[^\\W_])?)","(?:[^\\`]+)","(?:\\s*|\\W|$)")),s=RegExp(h("^:{0}:{1}","(?:[^\\W\\d_](?:[\\w!\"#$%\x26'()\\*\\+,\\-\\./:;\x3c\x3d\x3e\\?]*[^\\W_])?)","(?:\\s*|\\W|$)")),S=RegExp(h("^{0}",
l)),T=RegExp(h("^::{0}","(?:\\s*|\\W|$)")),H=RegExp(h("^\\|{0}\\|","(?:[^\\s\\|](?:[^\\|]*[^\\s\\|])?)")),P=RegExp(h("^{0}","\\s+")),Q=RegExp(h("^{0}",l)),R=RegExp(h("^::{0}","(?:\\s*|\\W|$)")),U=/^_/,V=RegExp(h("^{0}|_",l)),W=RegExp(h("^:{0}","(?:\\s*|\\W|$)")),O=/^::\s*$/,I=/^\s+(?:>>>|In \[\d+\]:)\s/;return{startState:function(){return{tok:e,ctx:d(void 0,0)}},copyState:function(b){var a=b.ctx,c=b.tmp;a.local&&(a={mode:a.mode,local:k.copyState(a.mode,a.local)});c&&(c={mode:c.mode,local:k.copyState(c.mode,
c.local)});return{tok:b.tok,ctx:a,tmp:c}},innerMode:function(b){return b.tmp?{state:b.tmp.local,mode:b.tmp.mode}:b.ctx.mode?{state:b.ctx.local,mode:b.ctx.mode}:null},token:function(b,a){return a.tok(b,a)}}},"python","stex");k.defineMIME("text/x-rst","rst")});
//# sourceMappingURL=rst.js.map