//>>built
(function(h){"object"==typeof exports&&"object"==typeof module?h(require("../../lib/codemirror",require("../xml/xml"))):"function"==typeof define&&define.amd?define("codemirror4/mode/markdown/markdown",["../../lib/codemirror","../xml/xml"],h):h(CodeMirror)})(function(h){h.defineMode("markdown",function(z,d){function r(b,a,c){a.f=a.inline=c;return c(b,a)}function A(b){b.linkTitle=!1;b.em=!1;b.strong=!1;b.quote=0;!s&&b.f==t&&(b.f=k,b.block=l);b.trailingSpace=0;b.trailingSpaceNewLine=!1;b.thisLineHasContent=
!1;return null}function l(b,a){var c=b.sol(),e=!1!==a.list;!1!==a.list&&0<=a.indentationDiff?(4>a.indentationDiff&&(a.indentation-=a.indentationDiff),a.list=null):!1!==a.list&&0<a.indentation?(a.list=null,a.listDepth=Math.floor(a.indentation/4)):!1!==a.list&&(a.list=!1,a.listDepth=0);var g=null;return 4<=a.indentationDiff?(a.indentation-=4,b.skipToEnd(),u):b.eatSpace()?null:(g=b.match(K))?(a.header=6>=g[0].length?g[0].length:6,d.highlightFormatting&&(a.formatting="header"),a.f=a.inline,f(a)):a.prevLineHasContent&&
(g=b.match(L))?(a.header="\x3d"==g[0].charAt(0)?1:2,d.highlightFormatting&&(a.formatting="header"),a.f=a.inline,f(a)):b.eat("\x3e")?(a.indentation++,a.quote=c?1:a.quote+1,d.highlightFormatting&&(a.formatting="quote"),b.eatSpace(),f(a)):"["===b.peek()?r(b,a,M):b.match(N,!0)?O:(!a.prevLineHasContent||e)&&(b.match(B,!1)||b.match(C,!1))?(c=null,b.match(B,!0)?c="ul":(b.match(C,!0),c="ol"),a.indentation+=4,a.list=!0,a.listDepth++,d.taskLists&&b.match(D,!1)&&(a.taskList=!0),a.f=a.inline,d.highlightFormatting&&
(a.formatting=["list","list-"+c]),f(a)):d.fencedCodeBlocks&&b.match(/^```([\w+#]*)/,!0)?(a.localMode=P(RegExp.$1),a.localMode&&(a.localState=a.localMode.startState()),c=Q,a.f=a.block=c,c(b,a),d.highlightFormatting&&(a.formatting="code-block"),a.code=!0,f(a)):r(b,a,a.inline)}function t(b,a){var c=n.token(b,a.htmlState);if(s&&!a.htmlState.tagName&&!a.htmlState.context||a.md_inside&&-1<b.current().indexOf("\x3e"))a.f=k,a.block=l,a.htmlState=null;return c}function Q(b,a){if(b.sol()&&b.match(/^```/,!0)){a.localMode=
a.localState=null;a.f=k;a.block=l;d.highlightFormatting&&(a.formatting="code-block");a.code=!0;var c=f(a);a.code=!1;return c}if(a.localMode)return a.localMode.token(b,a.localState);b.skipToEnd();return u}function f(b){var a=[];if(b.formatting){a.push(p);"string"===typeof b.formatting&&(b.formatting=[b.formatting]);for(var c=0;c<b.formatting.length;c++)a.push(p+"-"+b.formatting[c]),"header"===b.formatting[c]&&a.push(p+"-"+b.formatting[c]+"-"+b.header),"quote"===b.formatting[c]&&(!d.maxBlockquoteDepth||
d.maxBlockquoteDepth>=b.quote?a.push(p+"-"+b.formatting[c]+"-"+b.quote):a.push("error"))}if(b.taskOpen)return a.push("meta"),a.length?a.join(" "):null;if(b.taskClosed)return a.push("property"),a.length?a.join(" "):null;if(b.linkHref)return a.push(v),a.length?a.join(" "):null;b.strong&&a.push(R);b.em&&a.push(S);b.linkText&&a.push(E);b.code&&a.push(u);b.header&&(a.push(F),a.push(F+"-"+b.header));b.quote&&(a.push(w),!d.maxBlockquoteDepth||d.maxBlockquoteDepth>=b.quote?a.push(w+"-"+b.quote):a.push(w+
"-"+d.maxBlockquoteDepth));!1!==b.list&&((c=(b.listDepth-1)%3)?1===c?a.push(T):a.push(U):a.push(V));b.trailingSpaceNewLine?a.push("trailing-space-new-line"):b.trailingSpace&&a.push("trailing-space-"+(b.trailingSpace%2?"a":"b"));return a.length?a.join(" "):null}function W(b,a){if(b.match(X,!0))return f(a)}function k(b,a){var c=a.text(b,a);if("undefined"!==typeof c)return c;if(a.list)return a.list=null,f(a);if(a.taskList)return"x"!==b.match(D,!0)[1]?a.taskOpen=!0:a.taskClosed=!0,d.highlightFormatting&&
(a.formatting="task"),a.taskList=!1,f(a);a.taskOpen=!1;a.taskClosed=!1;if(a.header&&b.match(/^#+$/,!0))return d.highlightFormatting&&(a.formatting="header"),f(a);var c=b.sol(),e=b.next();if(a.escape)return a.escape=!1,f(a);if("\\"===e)return d.highlightFormatting&&(a.formatting="escape"),a.escape=!0,f(a);if(a.linkTitle){a.linkTitle=!1;var g=e;"("===e&&(g=")");g=(g+"").replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1");if(b.match(RegExp("^\\s*(?:[^"+g+"\\\\]+|\\\\\\\\|\\\\.)"+g),!0))return v}if("`"===e){c=a.formatting;
d.highlightFormatting&&(a.formatting="code");e=f(a);g=b.pos;b.eatWhile("`");g=1+b.pos-g;if(a.code){if(g===G)return a.code=!1,e;a.formatting=c}else G=g,a.code=!0;return f(a)}if(a.code)return f(a);if("!"===e&&b.match(/\[[^\]]*\] ?(?:\(|\[)/,!1))return b.match(/\[[^\]]*\]/),a.inline=a.f=H,Y;if("["===e&&b.match(/.*\](\(| ?\[)/,!1))return a.linkText=!0,d.highlightFormatting&&(a.formatting="link"),f(a);if("]"===e&&a.linkText)return d.highlightFormatting&&(a.formatting="link"),c=f(a),a.linkText=!1,a.inline=
a.f=H,c;if("\x3c"===e&&b.match(/^(https?|ftps?):\/\/(?:[^\\>]|\\.)+>/,!1))return a.f=a.inline=I,d.highlightFormatting&&(a.formatting="link"),c=f(a),(c?c+" ":"")+x;if("\x3c"===e&&b.match(/^[^> \\]+@(?:[^\\>]|\\.)+>/,!1))return a.f=a.inline=I,d.highlightFormatting&&(a.formatting="link"),c=(c=f(a))?c+" ":"",c+Z;if("\x3c"===e&&b.match(/^\w/,!1))return-1!=b.string.indexOf("\x3e")&&(c=b.string.substring(1,b.string.indexOf("\x3e")),/markdown\s*=\s*('|"){0,1}1('|"){0,1}/.test(c)&&(a.md_inside=!0)),b.backUp(1),
a.htmlState=h.startState(n),c=t,a.f=a.block=c,c(b,a);if("\x3c"===e&&b.match(/^\/\w*?>/))return a.md_inside=!1,"tag";g=!1;if(!d.underscoresBreakWords&&"_"===e&&"_"!==b.peek()&&b.match(/(\w)/,!1)){var m=b.pos-2;0<=m&&(m=b.string.charAt(m),"_"!==m&&m.match(/(\w)/,!1)&&(g=!0))}if("*"===e||"_"===e&&!g){if(!(c&&" "===b.peek())){if(a.strong===e&&b.eat(e))return d.highlightFormatting&&(a.formatting="strong"),e=f(a),a.strong=!1,e;if(!a.strong&&b.eat(e))return a.strong=e,d.highlightFormatting&&(a.formatting=
"strong"),f(a);if(a.em===e)return d.highlightFormatting&&(a.formatting="em"),e=f(a),a.em=!1,e;if(!a.em)return a.em=e,d.highlightFormatting&&(a.formatting="em"),f(a)}}else if(" "===e&&(b.eat("*")||b.eat("_"))){if(" "===b.peek())return f(a);b.backUp(1)}" "===e&&(b.match(/ +$/,!1)?a.trailingSpace++:a.trailingSpace&&(a.trailingSpaceNewLine=!0));return f(a)}function I(b,a){if("\x3e"===b.next()){a.f=a.inline=k;d.highlightFormatting&&(a.formatting="link");var c=f(a);return(c?c+" ":"")+x}b.match(/^[^>]+/,
!0);return x}function H(b,a){if(b.eatSpace())return null;var c=b.next();return"("===c||"["===c?(a.f=a.inline=$("("===c?")":"]"),d.highlightFormatting&&(a.formatting="link-string"),a.linkHref=!0,f(a)):"error"}function $(b){return function(a,c){if(a.next()===b){c.f=c.inline=k;d.highlightFormatting&&(c.formatting="link-string");var e=f(c);c.linkHref=!1;return e}a.match(aa(b),!0)&&a.backUp(1);c.linkHref=!0;return f(c)}}function M(b,a){return b.match(/^[^\]]*\]:/,!1)?(a.f=ba,b.next(),d.highlightFormatting&&
(a.formatting="link"),a.linkText=!0,f(a)):r(b,a,k)}function ba(b,a){if(b.match(/^\]:/,!0)){a.f=a.inline=ca;d.highlightFormatting&&(a.formatting="link");var c=f(a);a.linkText=!1;return c}b.match(/^[^\]]+/,!0);return E}function ca(b,a){if(b.eatSpace())return null;b.match(/^[^\s]+/,!0);void 0===b.peek()?a.linkTitle=!0:b.match(/^(?:\s+(?:"(?:[^"\\]|\\\\|\\.)+"|'(?:[^'\\]|\\\\|\\.)+'|\((?:[^)\\]|\\\\|\\.)+\)))?/,!0);a.f=a.inline=k;return v}function aa(b){y[b]||(b=(b+"").replace(/([.?*+^$[\]\\(){}|-])/g,
"\\$1"),y[b]=RegExp("^(?:[^\\\\]|\\\\.)*?("+b+")"));return y[b]}var s=h.modes.hasOwnProperty("xml"),n=h.getMode(z,s?{name:"xml",htmlMode:!0}:"text/plain"),q={html:"htmlmixed",js:"javascript",json:"application/json",c:"text/x-csrc","c++":"text/x-c++src",java:"text/x-java",csharp:"text/x-csharp","c#":"text/x-csharp",scala:"text/x-scala"},P=function(){var b,a={},c={},e,d=[];for(e in h.modes)h.modes.propertyIsEnumerable(e)&&d.push(e);for(b=0;b<d.length;b++)a[d[b]]=d[b];d=[];for(e in h.mimeModes)h.mimeModes.propertyIsEnumerable(e)&&
d.push({mime:e,mode:h.mimeModes[e]});for(b=0;b<d.length;b++)e=d[b].mime,c[e]=d[b].mime;for(var f in q)if(q[f]in a||q[f]in c)a[f]=q[f];return function(b){return a[b]?h.getMode(z,a[b]):null}}();void 0===d.highlightFormatting&&(d.highlightFormatting=!1);void 0===d.maxBlockquoteDepth&&(d.maxBlockquoteDepth=0);void 0===d.underscoresBreakWords&&(d.underscoresBreakWords=!0);void 0===d.fencedCodeBlocks&&(d.fencedCodeBlocks=!1);void 0===d.taskLists&&(d.taskLists=!1);var G=0,F="header",u="comment",w="quote",
V="variable-2",T="variable-3",U="keyword",O="hr",Y="tag",p="formatting",x="link",Z="link",E="link",v="string",S="em",R="strong",N=/^([*\-=_])(?:\s*\1){2,}\s*$/,B=/^[*\-+]\s+/,C=/^[0-9]+\.\s+/,D=/^\[(x| )\](?=\s)/,K=/^#+/,L=/^(?:\={1,}|-{1,})$/,X=/^[^#!\[\]*_\\<>` "'(]+/,y=[],J={startState:function(){return{f:l,prevLineHasContent:!1,thisLineHasContent:!1,block:l,htmlState:null,indentation:0,inline:k,text:W,escape:!1,formatting:!1,linkText:!1,linkHref:!1,linkTitle:!1,em:!1,strong:!1,header:0,taskList:!1,
list:!1,listDepth:0,quote:0,trailingSpace:0,trailingSpaceNewLine:!1}},copyState:function(b){return{f:b.f,prevLineHasContent:b.prevLineHasContent,thisLineHasContent:b.thisLineHasContent,block:b.block,htmlState:b.htmlState&&h.copyState(n,b.htmlState),indentation:b.indentation,localMode:b.localMode,localState:b.localMode?h.copyState(b.localMode,b.localState):null,inline:b.inline,text:b.text,escape:!1,formatting:!1,linkTitle:b.linkTitle,em:b.em,strong:b.strong,header:b.header,taskList:b.taskList,list:b.list,
listDepth:b.listDepth,quote:b.quote,trailingSpace:b.trailingSpace,trailingSpaceNewLine:b.trailingSpaceNewLine,md_inside:b.md_inside}},token:function(b,a){a.formatting=!1;if(b.sol()){var c=b.match(/^\s*$/,!0)||a.header;a.header=0;if(c)return a.prevLineHasContent=!1,A(a),this.token(b,a);a.prevLineHasContent=a.thisLineHasContent;a.thisLineHasContent=!0;a.escape=!1;a.taskList=!1;a.code=!1;a.trailingSpace=0;a.trailingSpaceNewLine=!1;a.f=a.block;var c=b.match(/^\s*/,!0)[0].replace(/\t/g,"    ").length,
d=4*Math.floor((c-a.indentation)/4);4<d&&(d=4);d=a.indentation+d;a.indentationDiff=d-a.indentation;a.indentation=d;if(0<c)return null}c=a.f(b,a);return b.start==b.pos?this.token(b,a):c},innerMode:function(b){return b.block==t?{state:b.htmlState,mode:n}:b.localState?{state:b.localState,mode:b.localMode}:{state:b,mode:J}},blankLine:A,getType:f,fold:"markdown"};return J},"xml");h.defineMIME("text/x-markdown","markdown")});
//# sourceMappingURL=markdown.js.map