//>>built
define("codemirror4/mode/markdown/test",["dojo","dijit","dojox"],function(e,f,g){(function(){function a(a){test.mode(a,c,Array.prototype.slice.call(arguments,1))}function b(a){test.mode(a,d,Array.prototype.slice.call(arguments,1))}var c=CodeMirror.getMode({tabSize:4},"markdown"),d=CodeMirror.getMode({tabSize:4},{name:"markdown",highlightFormatting:!0});b("formatting_emAsterisk","[em\x26formatting\x26formatting-em *][em foo][em\x26formatting\x26formatting-em *]");b("formatting_emUnderscore","[em\x26formatting\x26formatting-em _][em foo][em\x26formatting\x26formatting-em _]");
b("formatting_strongAsterisk","[strong\x26formatting\x26formatting-strong **][strong foo][strong\x26formatting\x26formatting-strong **]");b("formatting_strongUnderscore","[strong\x26formatting\x26formatting-strong __][strong foo][strong\x26formatting\x26formatting-strong __]");b("formatting_codeBackticks","[comment\x26formatting\x26formatting-code `][comment foo][comment\x26formatting\x26formatting-code `]");b("formatting_doubleBackticks","[comment\x26formatting\x26formatting-code ``][comment foo ` bar][comment\x26formatting\x26formatting-code ``]");
b("formatting_atxHeader","[header\x26header-1\x26formatting\x26formatting-header\x26formatting-header-1 #][header\x26header-1  foo # bar ][header\x26header-1\x26formatting\x26formatting-header\x26formatting-header-1 #]");b("formatting_setextHeader","foo","[header\x26header-1\x26formatting\x26formatting-header\x26formatting-header-1 \x3d]");b("formatting_blockquote","[quote\x26quote-1\x26formatting\x26formatting-quote\x26formatting-quote-1 \x3e ][quote\x26quote-1 foo]");b("formatting_list","[variable-2\x26formatting\x26formatting-list\x26formatting-list-ul - ][variable-2 foo]");
b("formatting_list","[variable-2\x26formatting\x26formatting-list\x26formatting-list-ol 1. ][variable-2 foo]");b("formatting_link","[link\x26formatting\x26formatting-link [][link foo][link\x26formatting\x26formatting-link ]]][string\x26formatting\x26formatting-link-string (][string http://example.com/][string\x26formatting\x26formatting-link-string )]");b("formatting_linkReference","[link\x26formatting\x26formatting-link [][link foo][link\x26formatting\x26formatting-link ]]][string\x26formatting\x26formatting-link-string [][string bar][string\x26formatting\x26formatting-link-string ]]]",
"[link\x26formatting\x26formatting-link [][link bar][link\x26formatting\x26formatting-link ]]:] [string http://example.com/]");b("formatting_linkWeb","[link\x26formatting\x26formatting-link \x3c][link http://example.com/][link\x26formatting\x26formatting-link \x3e]");b("formatting_linkEmail","[link\x26formatting\x26formatting-link \x3c][link user@example.com][link\x26formatting\x26formatting-link \x3e]");b("formatting_escape","[formatting\x26formatting-escape \\]*");a("plainText","foo");a("trailingSpace1",
"foo ");a("trailingSpace2","foo[trailing-space-a  ][trailing-space-new-line  ]");a("trailingSpace3","foo[trailing-space-a  ][trailing-space-b  ][trailing-space-new-line  ]");a("trailingSpace4","foo[trailing-space-a  ][trailing-space-b  ][trailing-space-a  ][trailing-space-new-line  ]");a("codeBlocksUsing4Spaces","    [comment foo]");a("codeBlocksUsing4SpacesIndentation","    [comment bar]","        [comment hello]","            [comment world]","    [comment foo]","bar");a("codeBlocksUsing4SpacesIndentation",
" foo","    [comment bar]","        [comment hello]","    [comment world]");a("codeBlocksUsing1Tab","\t[comment foo]");a("inlineCodeUsingBackticks","foo [comment `bar`]");a("blockCodeSingleBacktick","[comment `]","foo","[comment `]");a("unclosedBackticks","foo [comment `bar]");a("doubleBackticks","[comment ``foo ` bar``]");a("consecutiveBackticks","[comment `foo```bar`]");a("consecutiveBackticks","[comment `foo```bar`] hello [comment `world`]");a("unclosedBackticks","[comment ``foo ``` bar` hello]");
a("closedBackticks","[comment ``foo ``` bar` hello``] world");a("atxH1","[header\x26header-1 # foo]");a("atxH2","[header\x26header-2 ## foo]");a("atxH3","[header\x26header-3 ### foo]");a("atxH4","[header\x26header-4 #### foo]");a("atxH5","[header\x26header-5 ##### foo]");a("atxH6","[header\x26header-6 ###### foo]");a("atxH6NotH7","[header\x26header-6 ####### foo]");a("atxH1inline","[header\x26header-1 # foo ][header\x26header-1\x26em *bar*]");a("setextH1","foo","[header\x26header-1 \x3d]");a("setextH1",
"foo","[header\x26header-1 \x3d\x3d\x3d]");a("setextH2","foo","[header\x26header-2 -]");a("setextH2","foo","[header\x26header-2 ---]");a("blockquoteSpace","[quote\x26quote-1 \x3e foo]");a("blockquoteNoSpace","[quote\x26quote-1 \x3efoo]");a("blockquoteNoBlankLine","foo","[quote\x26quote-1 \x3e bar]");a("blockquoteSpace","[quote\x26quote-1 \x3e foo]","[quote\x26quote-1 \x3e][quote\x26quote-2 \x3e foo]","[quote\x26quote-1 \x3e][quote\x26quote-2 \x3e][quote\x26quote-3 \x3e foo]");a("blockquoteThenParagraph",
"[quote\x26quote-1 \x3efoo]","","bar");a("multiBlockquoteLazy","[quote\x26quote-1 \x3efoo]","[quote\x26quote-1 bar]");a("multiBlockquoteLazyThenParagraph","[quote\x26quote-1 \x3efoo]","[quote\x26quote-1 bar]","","hello");a("multiBlockquote","[quote\x26quote-1 \x3efoo]","[quote\x26quote-1 \x3ebar]");a("multiBlockquoteThenParagraph","[quote\x26quote-1 \x3efoo]","[quote\x26quote-1 \x3ebar]","","hello");a("listAsterisk","foo","bar","","[variable-2 * foo]","[variable-2 * bar]");a("listPlus","foo","bar",
"","[variable-2 + foo]","[variable-2 + bar]");a("listDash","foo","bar","","[variable-2 - foo]","[variable-2 - bar]");a("listNumber","foo","bar","","[variable-2 1. foo]","[variable-2 2. bar]");a("listBogus","foo","1. bar","2. hello");a("listAfterHeader","[header\x26header-1 # foo]","[variable-2 - bar]");a("listAsteriskFormatting","[variable-2 * ][variable-2\x26em *foo*][variable-2  bar]","[variable-2 * ][variable-2\x26strong **foo**][variable-2  bar]","[variable-2 * ][variable-2\x26strong **][variable-2\x26em\x26strong *foo**][variable-2\x26em *][variable-2  bar]",
"[variable-2 * ][variable-2\x26comment `foo`][variable-2  bar]");a("listPlusFormatting","[variable-2 + ][variable-2\x26em *foo*][variable-2  bar]","[variable-2 + ][variable-2\x26strong **foo**][variable-2  bar]","[variable-2 + ][variable-2\x26strong **][variable-2\x26em\x26strong *foo**][variable-2\x26em *][variable-2  bar]","[variable-2 + ][variable-2\x26comment `foo`][variable-2  bar]");a("listDashFormatting","[variable-2 - ][variable-2\x26em *foo*][variable-2  bar]","[variable-2 - ][variable-2\x26strong **foo**][variable-2  bar]",
"[variable-2 - ][variable-2\x26strong **][variable-2\x26em\x26strong *foo**][variable-2\x26em *][variable-2  bar]","[variable-2 - ][variable-2\x26comment `foo`][variable-2  bar]");a("listNumberFormatting","[variable-2 1. ][variable-2\x26em *foo*][variable-2  bar]","[variable-2 2. ][variable-2\x26strong **foo**][variable-2  bar]","[variable-2 3. ][variable-2\x26strong **][variable-2\x26em\x26strong *foo**][variable-2\x26em *][variable-2  bar]","[variable-2 4. ][variable-2\x26comment `foo`][variable-2  bar]");
a("listParagraph","[variable-2 * foo]","","[variable-2 * bar]");a("listMultiParagraph","[variable-2 * foo]","","[variable-2 * bar]","","    [variable-2 hello]");a("listMultiParagraphExtra","[variable-2 * foo]","","[variable-2 * bar]","","","    [variable-2 hello]");a("listMultiParagraphExtraSpace","[variable-2 * foo]","","[variable-2 * bar]","","     [variable-2 hello]","","    [variable-2 world]");a("listTab","[variable-2 * foo]","","[variable-2 * bar]","","\t[variable-2 hello]");a("listNoIndent",
"[variable-2 * foo]","","[variable-2 * bar]","","hello");a("blockquote","[variable-2 * foo]","","[variable-2 * bar]","","    [variable-2\x26quote\x26quote-1 \x3e hello]");a("blockquoteCode","[variable-2 * foo]","","[variable-2 * bar]","","        [comment \x3e hello]","","    [variable-2 world]");a("blockquoteCodeText","[variable-2 * foo]","","    [variable-2 bar]","","        [comment hello]","","    [variable-2 world]");a("listAsteriskNested","[variable-2 * foo]","","    [variable-3 * bar]");a("listPlusNested",
"[variable-2 + foo]","","    [variable-3 + bar]");a("listDashNested","[variable-2 - foo]","","    [variable-3 - bar]");a("listNumberNested","[variable-2 1. foo]","","    [variable-3 2. bar]");a("listMixed","[variable-2 * foo]","","    [variable-3 + bar]","","        [keyword - hello]","","            [variable-2 1. world]");a("listBlockquote","[variable-2 * foo]","","    [variable-3 + bar]","","        [quote\x26quote-1\x26variable-3 \x3e hello]");a("listCode","[variable-2 * foo]","","    [variable-3 + bar]",
"","            [comment hello]");a("listCodeIndentation","[variable-2 * foo]","","        [comment bar]","            [comment hello]","                [comment world]","        [comment foo]","    [variable-2 bar]");a("listNested","[variable-2 * foo]","","    [variable-3 * bar]","","       [variable-2 hello]");a("listNested","[variable-2 * foo]","","    [variable-3 * bar]","","      [variable-3 * foo]");a("listCodeText","[variable-2 * foo]","","        [comment bar]","","hello");a("hrSpace","[hr * * *]");
a("hr","[hr ***]");a("hrLong","[hr *****]");a("hrSpaceDash","[hr - - -]");a("hrDashLong","[hr ---------------------------------------]");a("linkTitle",'[link [[foo]]][string (http://example.com/ "bar")] hello');a("linkNoTitle","[link [[foo]]][string (http://example.com/)] bar");a("linkImage","[link [[][tag ![[foo]]][string (http://example.com/)][link ]]][string (http://example.com/)] bar");a("linkEm","[link [[][link\x26em *foo*][link ]]][string (http://example.com/)] bar");a("linkStrong","[link [[][link\x26strong **foo**][link ]]][string (http://example.com/)] bar");
a("linkEmStrong","[link [[][link\x26strong **][link\x26em\x26strong *foo**][link\x26em *][link ]]][string (http://example.com/)] bar");a("imageTitle",'[tag ![[foo]]][string (http://example.com/ "bar")] hello');a("imageNoTitle","[tag ![[foo]]][string (http://example.com/)] bar");a("imageAsterisks","[tag ![[*foo*]]][string (http://example.com/)] bar");a("notALink","[[foo]] (bar)");a("linkReference","[link [[foo]]][string [[bar]]] hello");a("linkReferenceEm","[link [[][link\x26em *foo*][link ]]][string [[bar]]] hello");
a("linkReferenceStrong","[link [[][link\x26strong **foo**][link ]]][string [[bar]]] hello");a("linkReferenceEmStrong","[link [[][link\x26strong **][link\x26em\x26strong *foo**][link\x26em *][link ]]][string [[bar]]] hello");a("linkReferenceSpace","[link [[foo]]] [string [[bar]]] hello");a("linkReferenceDoubleSpace","[[foo]]  [[bar]] hello");a("linkImplicit","[link [[foo]]][string [[]]] hello");a("labelNoTitle","[link [[foo]]:] [string http://example.com/]");a("labelIndented","   [link [[foo]]:] [string http://example.com/]");
a("labelSpaceTitle",'[link [[foo bar]]:] [string http://example.com/ "hello"]');a("labelDoubleTitle",'[link [[foo bar]]:] [string http://example.com/ "hello"] "world"');a("labelTitleDoubleQuotes",'[link [[foo]]:] [string http://example.com/  "bar"]');a("labelTitleSingleQuotes","[link [[foo]]:] [string http://example.com/  'bar']");a("labelTitleParenthese","[link [[foo]]:] [string http://example.com/  (bar)]");a("labelTitleInvalid","[link [[foo]]:] [string http://example.com/] bar");a("labelLinkAngleBrackets",
'[link [[foo]]:] [string \x3chttp://example.com/\x3e  "bar"]');a("labelTitleNextDoubleQuotes","[link [[foo]]:] [string http://example.com/]",'[string "bar"] hello');a("labelTitleNextSingleQuotes","[link [[foo]]:] [string http://example.com/]","[string 'bar'] hello");a("labelTitleNextParenthese","[link [[foo]]:] [string http://example.com/]","[string (bar)] hello");a("labelTitleNextMixed","[link [[foo]]:] [string http://example.com/]",'(bar" hello');a("linkWeb","[link \x3chttp://example.com/\x3e] foo");
a("linkWebDouble","[link \x3chttp://example.com/\x3e] foo [link \x3chttp://example.com/\x3e]");a("linkEmail","[link \x3cuser@example.com\x3e] foo");a("linkEmailDouble","[link \x3cuser@example.com\x3e] foo [link \x3cuser@example.com\x3e]");a("emAsterisk","[em *foo*] bar");a("emUnderscore","[em _foo_] bar");a("emInWordAsterisk","foo[em *bar*]hello");a("emInWordUnderscore","foo[em _bar_]hello");a("emEscapedBySpaceIn","foo [em _bar _ hello_] world");a("emEscapedBySpaceOut","foo _ bar[em _hello_]world");
a("emEscapedByNewline","foo","_ bar[em _hello_]world");a("emIncompleteAsterisk","foo [em *bar]");a("emIncompleteUnderscore","foo [em _bar]");a("strongAsterisk","[strong **foo**] bar");a("strongUnderscore","[strong __foo__] bar");a("emStrongAsterisk","[em *foo][em\x26strong **bar*][strong hello**] world");a("emStrongUnderscore","[em _foo][em\x26strong __bar_][strong hello__] world");a("emStrongMixed","[em _foo][em\x26strong **bar*hello__ world]");a("emStrongMixed","[em *foo][em\x26strong __bar_hello** world]");
a("escapeBacktick","foo \\`bar\\`");a("doubleEscapeBacktick","foo \\\\[comment `bar\\\\`]");a("escapeAsterisk","foo \\*bar\\*");a("doubleEscapeAsterisk","foo \\\\[em *bar\\\\*]");a("escapeUnderscore","foo \\_bar\\_");a("doubleEscapeUnderscore","foo \\\\[em _bar\\\\_]");a("escapeHash","\\# foo");a("doubleEscapeHash","\\\\# foo");a("escapeNewline","\\","[em *foo*]");a("taskList","[variable-2 * [ ]] bar]");a("fencedCodeBlocks","[comment ```]","foo","[comment ```]")})()});
//# sourceMappingURL=test.js.map