//>>built
(function(l){"object"==typeof exports&&"object"==typeof module?l(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define("codemirror4/mode/haxe/haxe",["../../lib/codemirror"],l):l(CodeMirror)})(function(l){l.defineMode("haxe",function(m,D){function r(a,d){for(var c=!1,b;null!=(b=a.next());){if(b==d&&!c)return!1;c=!c&&"\\"==b}return c}function n(a,d,c){v=a;H=c;return d}function l(a,d){var c=a.next();if('"'==c||"'"==c)return c=S(c),d.tokenize=c,c(a,d);if(/[\[\]{}\(\),;\:\.]/.test(c))return n(c);
if("0"==c&&a.eat(/x/i))return a.eatWhile(/[\da-f]/i),n("number","number");if(/\d/.test(c)||"-"==c&&a.eat(/\d/))return a.match(/^\d*(?:\.\d*)?(?:[eE][+\-]?\d+)?/),n("number","number");if(d.reAllowed&&"~"==c&&a.eat(/\//))return r(a,"/"),a.eatWhile(/[gimsu]/),n("regexp","string-2");if("/"==c){if(a.eat("*"))return c=T,d.tokenize=c,c(a,d);if(a.eat("/"))return a.skipToEnd(),n("comment","comment");a.eatWhile(E);return n("operator",null,a.current())}if("#"==c)return a.skipToEnd(),n("conditional","meta");
if("@"==c)return a.eat(/:/),a.eatWhile(/[\w_]/),n("metadata","meta");if(E.test(c))return a.eatWhile(E),n("operator",null,a.current());if(/[A-Z]/.test(c))return a.eatWhile(/[\w_<>]/),c=a.current(),n("type","variable-3",c);a.eatWhile(/[\w_]/);var c=a.current(),b=I.propertyIsEnumerable(c)&&I[c];return b&&d.kwAllowed?n(b.type,b.style,c):n("variable","variable",c)}function S(a){return function(d,c){r(d,a)||(c.tokenize=l);return n("string","string")}}function T(a,d){for(var c=!1,b;b=a.next();){if("/"==
b&&c){d.tokenize=l;break}c="*"==b}return n("comment","comment")}function J(a,d,b,f,h,k){this.indented=a;this.column=d;this.type=b;this.prev=h;this.info=k;null!=f&&(this.align=f)}function K(a){for(var d=h.state,b=d.importedtypes;b;b=b.next)if(b.name==a)return;d.importedtypes={name:a,next:d.importedtypes}}function u(){for(var a=arguments.length-1;0<=a;a--)h.cc.push(arguments[a])}function b(){u.apply(null,arguments);return!0}function z(a){var b=h.state;if(b.context){h.marked="def";for(var c=b.localVars;c;c=
c.next)if(c.name==a)return;b.localVars={name:a,next:b.localVars}}}function A(){h.state.context||(h.state.localVars=U);h.state.context={prev:h.state.context,vars:h.state.localVars}}function B(){h.state.localVars=h.state.context.vars;h.state.context=h.state.context.prev}function e(a,b){var c=function(){var c=h.state;c.lexical=new J(c.indented,h.stream.column(),a,null,c.lexical,b)};c.lex=!0;return c}function g(){var a=h.state;a.lexical.prev&&(")"==a.lexical.type&&(a.indented=a.lexical.indented),a.lexical=
a.lexical.prev)}function p(a){function d(c){return c==a?b():";"==a?u():b(d)}return d}function s(a){return"@"==a?b(L):"var"==a?b(e("vardef"),F,p(";"),g):"keyword a"==a?b(e("form"),q,s,g):"keyword b"==a?b(e("form"),s,g):"{"==a?b(e("}"),A,G,g,B):";"==a?b():"attribute"==a?b(M):"function"==a?b(x):"for"==a?b(e("form"),p("("),e(")"),V,p(")"),g,s,g):"variable"==a?b(e("stat"),W):"switch"==a?b(e("form"),q,e("}","switch"),p("{"),G,g,g):"case"==a?b(q,p(":")):"default"==a?b(p(":")):"catch"==a?b(e("form"),A,p("("),
N,p(")"),s,g,B):"import"==a?b(O,p(";")):"typedef"==a?b(X):u(e("stat"),q,p(";"),g)}function q(a){return P.hasOwnProperty(a)?b(t):"function"==a?b(x):"keyword c"==a?b(Q):"("==a?b(e(")"),Q,p(")"),g,t):"operator"==a?b(q):"["==a?b(e("]"),w(q,"]"),g,t):"{"==a?b(e("}"),w(Y,"}"),g,t):b()}function Q(a){return a.match(/[;\}\)\],]/)?u():u(q)}function t(a,d){if("operator"==a&&/\+\+|--/.test(d))return b(t);if("operator"==a||":"==a)return b(q);if(";"!=a){if("("==a)return b(e(")"),w(q,")"),g,t);if("."==a)return b(Z,
t);if("["==a)return b(e("]"),q,p("]"),g,t)}}function M(a){if("attribute"==a)return b(M);if("function"==a)return b(x);if("var"==a)return b(F)}function L(a){if(":"==a||"variable"==a)return b(L);if("("==a)return b(e(")"),w($,")"),g,s)}function $(a){if("variable"==a)return b()}function O(a,d){if("variable"==a&&/[A-Z]/.test(d.charAt(0)))return K(d),b();if("variable"==a||"property"==a||"."==a||"*"==d)return b(O)}function X(a,d){if("variable"==a&&/[A-Z]/.test(d.charAt(0)))return K(d),b();if("type"==a&&/[A-Z]/.test(d.charAt(0)))return b()}
function W(a){return":"==a?b(g,s):u(t,p(";"),g)}function Z(a){if("variable"==a)return h.marked="property",b()}function Y(a){"variable"==a&&(h.marked="property");if(P.hasOwnProperty(a))return b(p(":"),q)}function w(a,d){function c(f){return","==f?b(a,c):f==d?b():b(p(d))}return function(f){return f==d?b():u(a,c)}}function G(a){return"}"==a?b():u(s,G)}function F(a,d){return"variable"==a?(z(d),b(C,R)):b()}function R(a,d){if("\x3d"==d)return b(q,R);if(","==a)return b(F)}function V(a,d){"variable"==a&&
z(d);return b(e(")"),A,aa,q,g,s,B)}function aa(a,d){if("in"==d)return b()}function x(a,d){if("variable"==a)return z(d),b(x);if("new"==d)return b(x);if("("==a)return b(e(")"),A,w(N,")"),g,C,s,B)}function C(a){if(":"==a)return b(ba)}function ba(a){if("type"==a||"variable"==a)return b();if("{"==a)return b(e("}"),w(ca,"}"),g)}function ca(a){if("variable"==a)return b(C)}function N(a,d){if("variable"==a)return z(d),b(C)}var y=m.indentUnit,I=function(){function a(a){return{type:a,style:"keyword"}}var b=
a("keyword a"),c=a("keyword b"),f=a("keyword c"),h=a("operator"),k={type:"atom",style:"atom"},g={type:"attribute",style:"attribute"},e=a("typedef");return{"if":b,"while":b,"else":c,"do":c,"try":c,"return":f,"break":f,"continue":f,"new":f,"throw":f,"var":a("var"),inline:g,"static":g,using:a("import"),"public":g,"private":g,cast:a("cast"),"import":a("import"),macro:a("macro"),"function":a("function"),"catch":a("catch"),untyped:a("untyped"),callback:a("cb"),"for":a("for"),"switch":a("switch"),"case":a("case"),
"default":a("default"),"in":h,never:a("property_access"),trace:a("trace"),"class":e,"abstract":e,"enum":e,"interface":e,typedef:e,"extends":e,"implements":e,dynamic:e,"true":k,"false":k,"null":k}}(),E=/[+\-*&%=<>!?|]/,v,H,P={atom:!0,number:!0,variable:!0,string:!0,regexp:!0},h={state:null,column:null,marked:null,cc:null},U={name:"this",next:null};g.lex=!0;return{startState:function(a){return{tokenize:l,reAllowed:!0,kwAllowed:!0,cc:[],lexical:new J((a||0)-y,0,"block",!1),localVars:D.localVars,importedtypes:"Int Float String Void Std Bool Dynamic Array".split(" "),
context:D.localVars&&{vars:D.localVars},indented:0}},token:function(a,b){a.sol()&&(b.lexical.hasOwnProperty("align")||(b.lexical.align=!1),b.indented=a.indentation());if(a.eatSpace())return null;var c=b.tokenize(a,b);if("comment"==v)return c;b.reAllowed=!!("operator"==v||"keyword c"==v||v.match(/^[\[{}\(,;:]$/));b.kwAllowed="."!=v;a:{var f=v,e=H,k=b.cc;h.state=b;h.stream=a;h.marked=null;h.cc=k;b.lexical.hasOwnProperty("align")||(b.lexical.align=!0);for(;;)if((k.length?k.pop():s)(f,e)){for(;k.length&&
k[k.length-1].lex;)k.pop()();if(h.marked){c=h.marked;break a}if(k="variable"==f)b:{for(k=b.localVars;k;k=k.next)if(k.name==e){k=!0;break b}k=void 0}if(k){c="variable-2";break a}if(f="variable"==f)b:if(f=b,/[a-z]/.test(e.charAt(0)))f=!1;else{for(var k=f.importedtypes.length,g=0;g<k;g++)if(f.importedtypes[g]==e){f=!0;break b}f=void 0}if(f){c="variable-3";break a}break a}c=void 0}return c},indent:function(a,b){if(a.tokenize!=l)return 0;var c=b&&b.charAt(0),f=a.lexical;"stat"==f.type&&"}"==c&&(f=f.prev);
var e=f.type,g=c==e;return"vardef"==e?f.indented+4:"form"==e&&"{"==c?f.indented:"stat"==e||"form"==e?f.indented+y:"switch"==f.info&&!g?f.indented+(/^(?:case|default)\b/.test(b)?y:2*y):f.align?f.column+(g?0:1):f.indented+(g?0:y)},electricChars:"{}",blockCommentStart:"/*",blockCommentEnd:"*/",lineComment:"//"}});l.defineMIME("text/x-haxe","haxe");l.defineMode("hxml",function(){return{startState:function(){return{define:!1,inString:!1}},token:function(m,l){var r=m.peek(),n=m.sol();if("#"==r)return m.skipToEnd(),
"comment";if(n&&"-"==r)return r="variable-2",m.eat(/-/),"-"==m.peek()&&(m.eat(/-/),r="keyword a"),"D"==m.peek()&&(m.eat(/[D]/),r="keyword c",l.define=!0),m.eatWhile(/[A-Z]/i),r;r=m.peek();!1==l.inString&&"'"==r&&(l.inString=!0,m.next());if(!0==l.inString)return m.skipTo("'")||m.skipToEnd(),"'"==m.peek()&&(m.next(),l.inString=!1),"string";m.next();return null},lineComment:"#"}});l.defineMIME("text/x-hxml","hxml")});
//# sourceMappingURL=haxe.js.map