//>>built
define("sol/wgt/Tree","dojo/_base/declare dijit/Tree dojo/_base/lang dojo/on dojo/dom-geometry dojo/dom-style dojo/dom-class dojo/dom-construct ./tree/OverflowWgt dojo/_base/fx".split(" "),function(g,h,l,k,f,d,c,e,m,n){var p=g([h._TreeNode],{buildRendering:function(){this.inherited(arguments);this.backgroundNode=e.create("div",{"class":"backgroundNode"});e.place(this.backgroundNode,this.domNode);this.moreNode=e.create("div",{"class":"treeOpenMore moreNode"});e.place(this.moreNode,this.rowNode);this.moreInner=
e.create("span",{"class":"treeOpenMore moreNodeInner",innerHTML:"..."});e.place(this.moreInner,this.moreNode);this.watch("hovering",l.hitch(this,"_hoverChange"))},_hoverChange:function(a,b,d){d?c.contains(this.rowNode,"dijitTreeRowHover")&&this.tree.addHoverNode(this):this.tree.removeHoverNode(this)},_addFloatStyle:function(){if(!this._floatStyleAdded){this._floatStyleAdded=!0;c.add(this.rowNode,"rowNodeIsFloating");c.add(this.backgroundNode,"rowNodeIsFloating");d.set(this.domNode,{paddingTop:this._rowBox().h+
"px"});d.set(this.rowNode,{zIndex:2E3-2*this.indent+1});var a=f.getMarginBox(this.expandoNode);d.set(this.backgroundNode,{zIndex:2E3-2*this.indent,height:this._rowBox().h+"px",left:a.l+a.w})}},_removeFloatStyle:function(){this._floatStyleAdded&&(this._floatStyleAdded=!1,c.remove(this.rowNode,"rowNodeIsFloating"),c.remove(this.backgroundNode,"rowNodeIsFloating"),d.set(this.domNode,{paddingTop:""}))},_removeFloat:function(){this._onScroll&&(this._onScroll.remove(),delete this._onScroll);this._removeFloatStyle()},
destroy:function(){this._removeFloat();this.inherited(arguments)},_rowBox:function(){if(this._rowBoxJsn)return this._rowBoxJsn;var a=f.getMarginBox(this.rowNode);a.h&&a.w&&(this._rowBoxJsn=a);return a},getIndentAddition:function(){return this.indent*this._rowBox().h},scrollToTop:function(){var a=f.getMarginBox(this.domNode);this.tree.scrollTo(a.t-this.getIndentAddition())},expand:function(){var a=this.inherited(arguments),b=this,c=function(){if(b.isExpandable){var a=f.getMarginBox(b.domNode);if(a.t<
b.tree.domNode.scrollTop+b.getIndentAddition()&&a.t+a.h>b.tree.domNode.scrollTop+b.getIndentAddition()){var c=b.tree.domNode.scrollTop+b.getIndentAddition();c+b._rowBox().h>a.t+a.h&&(c=a.t+a.h-b._rowBox().h);b._addFloatStyle();d.set(b.rowNode,{top:c+"px"});d.set(b.backgroundNode,{top:c+"px"})}else b._removeFloatStyle()}else b._removeFloat()};this._onScroll=k(this.tree.domNode,"scroll",c);this.tree._lastExpand=this;a.then(function(){c();if(b.tree._lastExpand===b){var a=f.getMarginBox(b.domNode);a.t+
a.h>b.tree.domNode.scrollTop+b.tree.domNode.clientHeight&&(b.getIndentAddition()+a.h>b.tree.domNode.clientHeight?b.scrollToTop():b.tree.scrollTo(a.t+a.h-b.tree.domNode.clientHeight))}});return a},collapse:function(){var a=this.inherited(arguments);this._floatStyleAdded&&this.scrollToTop();this._removeFloat();return a}});return g([h],{addHoverNode:function(a){this._hoverNode!==a&&(this._hoverNode=a,this.overflowWgt.set("hoverNode",a))},removeHoverNode:function(a){this._hoverNode===a&&(delete this._hoverNode,
this.overflowWgt.set("hoverNode",void 0))},scrollTo:function(a){var b=this;this._scrollAnimation&&this._scrollAnimation.stop();this._scrollAnimation=new n.Animation({curve:[this.domNode.scrollTop,a],onAnimate:function(a){b.domNode.scrollTop=a}});this._scrollAnimation.play()},_onClick:function(a,b){b.target&&c.contains(b.target,"treeOpenMore")?(a.scrollToTop(),b.stopPropagation(),b.preventDefault()):this.inherited(arguments)},buildRendering:function(){var a=this;this.inherited(arguments);this.overflowWgt=
new m({treeWgt:this});this.own(this.overflowWgt);this.overflowWgt.placeAt(document.body);this._onScroll=k(this.domNode,"scroll",function(){a.overflowWgt.update()});this.own(this._onScroll)},resize:function(){this.inherited(arguments);this.overflowWgt.updateSize()},_createTreeNode:function(a){return new p(a)},destroy:function(){this._scrollAnimation&&this._scrollAnimation.stop();this.inherited(arguments)}})});
//# sourceMappingURL=Tree.js.map