//>>built
(function(g){"object"==typeof exports&&"object"==typeof module?g(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define("codemirror4/addon/hint/show-hint",["../../lib/codemirror"],g):g(CodeMirror)})(function(g){function n(a,b){this.cm=a;this.options=this.buildOptions(b);this.widget=this.onClose=null}function y(a,b){function c(a,c){var d;d="string"!=typeof c?function(a){return c(a,b)}:f.hasOwnProperty(c)?f[c]:c;g[a]=d}var f={Up:function(){b.moveFocus(-1)},Down:function(){b.moveFocus(1)},
PageUp:function(){b.moveFocus(-b.menuSize()+1,!0)},PageDown:function(){b.moveFocus(b.menuSize()-1,!0)},Home:function(){b.setFocus(0)},End:function(){b.setFocus(b.length-1)},Enter:b.pick,Tab:b.pick,Esc:b.close},d=a.options.customKeys,g=d?{}:f;if(d)for(var e in d)d.hasOwnProperty(e)&&c(e,d[e]);if(d=a.options.extraKeys)for(e in d)d.hasOwnProperty(e)&&c(e,d[e]);return g}function u(a,b){for(;b&&b!=a;){if("LI"===b.nodeName.toUpperCase()&&b.parentNode==a)return b;b=b.parentNode}}function q(a,b){this.completion=
a;this.data=b;var c=this,f=a.cm,d=this.hints=document.createElement("ul");d.className="CodeMirror-hints";this.selectedHint=b.selectedHint||0;for(var m=b.list,e=0;e<m.length;++e){var l=d.appendChild(document.createElement("li")),h=m[e],k=z+(e!=this.selectedHint?"":" "+s);null!=h.className&&(k=h.className+" "+k);l.className=k;h.render?h.render(l,b,h):l.appendChild(document.createTextNode(h.displayText||("string"==typeof h?h:h.text)));l.hintId=e}var e=f.cursorCoords(a.options.alignWithWord?b.from:null),
p=e.left,r=e.bottom,v=!0;d.style.left=p+"px";d.style.top=r+"px";l=window.innerWidth||Math.max(document.body.offsetWidth,document.documentElement.offsetWidth);k=window.innerHeight||Math.max(document.body.offsetHeight,document.documentElement.offsetHeight);(a.options.container||document.body).appendChild(d);h=d.getBoundingClientRect();if(0<h.bottom-k){var t=h.bottom-h.top,w=h.top-(e.bottom-e.top);0<w-t?(d.style.top=(r=w-t)+"px",v=!1):t>k&&(d.style.height=k-5+"px",d.style.top=(r=e.bottom-h.top)+"px",
k=f.getCursor(),b.from.ch!=k.ch&&(e=f.cursorCoords(k),d.style.left=(p=e.left)+"px",h=d.getBoundingClientRect()))}k=h.left-l;0<k&&(h.right-h.left>l&&(d.style.width=l-5+"px",k-=h.right-h.left-l),d.style.left=(p=e.left-k)+"px");f.addKeyMap(this.keyMap=y(a,{moveFocus:function(a,b){c.changeActive(c.selectedHint+a,b)},setFocus:function(a){c.changeActive(a)},menuSize:function(){return c.screenAmount()},length:m.length,close:function(){a.close()},pick:function(){c.pick()},data:b}));if(a.options.closeOnUnfocus){var q;
f.on("blur",this.onBlur=function(){q=setTimeout(function(){a.close()},100)});f.on("focus",this.onFocus=function(){clearTimeout(q)})}var n=f.getScrollInfo();f.on("scroll",this.onScroll=function(){var c=f.getScrollInfo(),b=f.getWrapperElement().getBoundingClientRect(),e=r+n.top-c.top,g=e-(window.pageYOffset||(document.documentElement||document.body).scrollTop);v||(g+=d.offsetHeight);if(g<=b.top||g>=b.bottom)return a.close();d.style.top=e+"px";d.style.left=p+n.left-c.left+"px"});g.on(d,"dblclick",function(a){if((a=
u(d,a.target||a.srcElement))&&null!=a.hintId)c.changeActive(a.hintId),c.pick()});g.on(d,"click",function(b){if((b=u(d,b.target||b.srcElement))&&null!=b.hintId)c.changeActive(b.hintId),a.options.completeOnSingleClick&&c.pick()});g.on(d,"mousedown",function(){setTimeout(function(){f.focus()},20)});g.signal(b,"select",m[0],d.firstChild);return!0}var z="CodeMirror-hint",s="CodeMirror-hint-active";g.showHint=function(a,b,c){if(!b)return a.showHint(c);c&&c.async&&(b.async=!0);b={hint:b};if(c)for(var f in c)b[f]=
c[f];return a.showHint(b)};g.defineExtension("showHint",function(a){if(!(1<this.listSelections().length||this.somethingSelected())){this.state.completionActive&&this.state.completionActive.close();var b=this.state.completionActive=new n(this,a);if(a=b.options.hint)if(g.signal(this,"startCompletion",this),a.async)a(this,function(a){b.showHints(a)},b.options);else return b.showHints(a(this,b.options))}});n.prototype={close:function(){if(this.active()){this.cm.state.completionActive=null;this.widget&&
this.widget.close();if(this.onClose)this.onClose();g.signal(this.cm,"endCompletion",this.cm)}},active:function(){return this.cm.state.completionActive==this},pick:function(a,b){var c=a.list[b];c.hint?c.hint(this.cm,a,c):this.cm.replaceRange("string"==typeof c?c:c.text,c.from||a.from,c.to||a.to,"complete");g.signal(a,"pick",c);this.close()},showHints:function(a){if(!a||!a.list.length||!this.active())return this.close();this.options.completionSingle&&1==a.list.length?this.pick(a,0):this.showWidget(a)},
showWidget:function(a){function b(){l||(l=!0,e.close(),e.cm.off("cursorActivity",d),a&&g.signal(a,"close"))}function c(){if(!l){g.signal(a,"update");var b=e.options.hint;b.async?b(e.cm,f,e.options):f(b(e.cm,e.options))}}function f(c){a=c;if(!l){if(!a||!a.list.length)return b();e.widget&&e.widget.close();e.widget=new q(e,a)}}function d(){m&&(n(m),m=0);var a=e.cm.getCursor(),b=e.cm.getLine(a.line);a.line!=k.line||b.length-a.ch!=p-k.ch||a.ch<k.ch||e.cm.somethingSelected()||a.ch&&h.test(b.charAt(a.ch-
1))?e.close():(m=r(c),e.widget&&e.widget.close())}this.widget=new q(this,a);g.signal(a,"shown");var m=0,e=this,l,h=this.options.closeCharacters,k=this.cm.getCursor(),p=this.cm.getLine(k.line).length,r=window.requestAnimationFrame||function(a){return setTimeout(a,1E3/60)},n=window.cancelAnimationFrame||clearTimeout;this.cm.on("cursorActivity",d);this.onClose=b},buildOptions:function(a){var b=this.cm.options.hintOptions,c={},f;for(f in x)c[f]=x[f];if(b)for(f in b)void 0!==b[f]&&(c[f]=b[f]);if(a)for(f in a)void 0!==
a[f]&&(c[f]=a[f]);return c}};q.prototype={close:function(){if(this.completion.widget==this){this.completion.widget=null;this.hints.parentNode.removeChild(this.hints);this.completion.cm.removeKeyMap(this.keyMap);var a=this.completion.cm;this.completion.options.closeOnUnfocus&&(a.off("blur",this.onBlur),a.off("focus",this.onFocus));a.off("scroll",this.onScroll)}},pick:function(){this.completion.pick(this.data,this.selectedHint)},changeActive:function(a,b){a>=this.data.list.length?a=b?this.data.list.length-
1:0:0>a&&(a=b?0:this.data.list.length-1);if(this.selectedHint!=a){var c=this.hints.childNodes[this.selectedHint];c.className=c.className.replace(" "+s,"");c=this.hints.childNodes[this.selectedHint=a];c.className+=" "+s;c.offsetTop<this.hints.scrollTop?this.hints.scrollTop=c.offsetTop-3:c.offsetTop+c.offsetHeight>this.hints.scrollTop+this.hints.clientHeight&&(this.hints.scrollTop=c.offsetTop+c.offsetHeight-this.hints.clientHeight+3);g.signal(this.data,"select",this.data.list[this.selectedHint],c)}},
screenAmount:function(){return Math.floor(this.hints.clientHeight/this.hints.firstChild.offsetHeight)||1}};g.registerHelper("hint","auto",function(a,b){var c=a.getHelpers(a.getCursor(),"hint");if(c.length)for(var f=0;f<c.length;f++){var d=c[f](a,b);if(d&&d.list.length)return d}else if(c=a.getHelper(a.getCursor(),"hintWords")){if(c)return g.hint.fromList(a,{words:c})}else if(g.hint.anyword)return g.hint.anyword(a,b)});g.registerHelper("hint","fromList",function(a,b){for(var c=a.getCursor(),f=a.getTokenAt(c),
d=[],m=0;m<b.words.length;m++){var e=b.words[m];e.slice(0,f.string.length)==f.string&&d.push(e)}if(d.length)return{list:d,from:g.Pos(c.line,f.start),to:g.Pos(c.line,f.end)}});g.commands.autocomplete=g.showHint;var x={hint:g.hint.auto,completionSingle:!0,alignWithWord:!0,closeCharacters:/[\s()\[\]{};:>,]/,closeOnUnfocus:!0,completeOnSignleClick:!1,container:null,customKeys:null,extraKeys:null};g.defineOption("hintOptions",null)});
//# sourceMappingURL=show-hint.js.map