//>>built
define("sol/node/debug/Protocol",["dojo/_base/declare","dojo/json","dojo/Deferred","dojo/_base/lang"],function(l,h,e,m){return l([],{constructor:function(){this.bufStr="";this._events={};this.seq=0;this._responseHandler={};this._requestsRunning={}},destroy:function(){delete this._events;delete this._responseHandler},write:function(a){this.bufStr="STRING"==typeof a?this.bufStr+a:this.bufStr+a.toString();for(a=!0;a;)a=this.expectBody?this.parseBody():this.parseHead()},parseBody:function(){if(this.bufStr.length>=
this.contentLength)return this._newMsg({head:this.head,body:this.bufStr.substr(0,this.contentLength)}),this.bufStr=this.bufStr.substr(this.contentLength),this.expectBody=!1,!0},parseHead:function(){var a=this.bufStr.indexOf("\r\n\r\n");return-1<a?(this.headStr=this.bufStr.substr(0,a),this.bufStr=this.bufStr.substr(a+4),this._parseHead(),this.head["Content-Length"]&&((this.contentLength=parseInt(this.head["Content-Length"],10))?this.expectBody=!0:this._newMsg({head:this.head,body:void 0})),!0):!1},
_parseHead:function(){this.head={};var a=this.headStr.split("\r\n"),b,c;for(b=0;b<a.length;++b)if(c=a[b].indexOf(":"),-1<c){var d=a[b].substr(0,c);c=a[b].substr(c+(" "==a[b][c+1]?2:1));this.head[d]=c}},_newMsg:function(a){if(this._events._message)for(var b=0;b<this._events._message.length;++b)try{this._events._message[b](a)}catch(c){}void 0!==a.body&&(a=h.parse(a.body),"event"==a.type?this._handleEvent(a):"response"==a.type&&this._handleResponse(a))},_handleEvent:function(a){if(this._events[a.event])for(var b=
0;b<this._events[a.event].length;++b)try{this._events[a.event][b](a.body)}catch(c){}},on:function(a,b){this._events[a]||(this._events[a]=[]);this._events[a].push(b)},_data:function(a){if(this._events.data)for(var b=0;b<this._events.data.length;++b)try{this._events.data[b](a)}catch(c){}},_handleResponse:function(a){if(this._responseHandler[a.command])this._responseHandler[a.command](a)},_expectResponse:function(a){var b=new e;this._responseHandler[a.command]=m.hitch(this,function(c){delete this._responseHandler[a.command];
b.resolve(c)});return b.promise},getSource:function(a){var b=new e,c="";a={seq:this.seq++,type:"request",command:"scripts",arguments:{ids:[a.id],includeSource:!0}};c="Content-Length: ";a=h.stringify(a);c+=a.length;c=c+"\r\n\r\n"+a;this._data(c);this._expectResponse({command:"scripts"}).then(function(a){b.resolve({id:a.body[0].id,name:a.body[0].name,source:a.body[0].source})});return b},backtrace:function(a){var b=new e;this._commmand("backtrace",a).then(function(a){b.resolve(a)});return b},setExceptionBreak:function(a){var b=
new e;this._commmand("setexceptionbreak",a).then(function(a){b.resolve(a)});return b},version:function(a){var b=new e;this._commmand("version",a).then(function(a){b.resolve(a)});return b},setFrame:function(a){var b=new e;this._commmand("frame",{number:a}).then(function(a){b.resolve(a)});return b},_commmand:function(a,b){var c=new e,d="",g={seq:this.seq++,type:"request",command:a};b&&(g.arguments=b);var d="Content-Length: ",g=h.stringify(g),d=d+g.length,d=d+"\r\n\r\n"+g,d={data:d,command:a,handle:function(a){c.resolve(a)}},
f=this,k=function(a){f._requestsRunning[a.command]||(f._requestsRunning[a.command]={queue:[]});f._data(a.data);f._expectResponse({command:a.command}).then(function(b){a.handle(b);(b=f._requestsRunning[a.command])&&b.queue.length?k(b.queue.shift()):delete f._requestsRunning[a.command]})};this._requestsRunning[d.command]?this._requestsRunning[d.command].queue.push(d):k(d);return c},cont:function(a){var b=new e;this._commmand("continue",a.step?{stepaction:a.step}:void 0).then(function(a){b.resolve(a)});
return b}})});
//# sourceMappingURL=Protocol.js.map