//>>built
define("dojox/charting/widget/SelectableLegend","dojo/_base/array dojo/_base/declare dojo/query dojo/_base/connect dojo/_base/Color ./Legend dijit/form/CheckBox ../action2d/Highlight dojox/lang/functional dojox/gfx/fx dojo/keys dojo/dom-construct dojo/dom-prop dijit/registry".split(" "),function(g,n,e,m,x,p,q,r,y,z,f,s,t,u){var v=n(null,{constructor:function(a){this.legend=a;this.index=0;this.horizontalLength=this._getHrizontalLength();g.forEach(a.legends,function(a,c){0<c&&e("input",a).attr("tabindex",
-1)});this.firstLabel=e("input",a.legends[0])[0];m.connect(this.firstLabel,"focus",this,function(){this.legend.active=!0});m.connect(this.legend.domNode,"keydown",this,"_onKeyEvent")},_getHrizontalLength:function(){var a=this.legend.horizontal;return"number"==typeof a?Math.min(a,this.legend.legends.length):a?this.legend.legends.length:1},_onKeyEvent:function(a){if(this.legend.active)if(a.keyCode==f.TAB)this.legend.active=!1;else{var b=this.legend.legends.length;switch(a.keyCode){case f.LEFT_ARROW:this.index--;
0>this.index&&(this.index+=b);break;case f.RIGHT_ARROW:this.index++;this.index>=b&&(this.index-=b);break;case f.UP_ARROW:0<=this.index-this.horizontalLength&&(this.index-=this.horizontalLength);break;case f.DOWN_ARROW:this.index+this.horizontalLength<b&&(this.index+=this.horizontalLength);break;default:return}this._moveToFocus();Event.stop(a)}},_moveToFocus:function(){e("input",this.legend.legends[this.index])[0].focus()}}),w=n(r,{connect:function(){}});return n("dojox.charting.widget.SelectableLegend",
p,{outline:!1,transitionFill:null,transitionStroke:null,autoScale:!1,postCreate:function(){this.legends=[];this.legendAnim={};this._cbs=[];this.inherited(arguments)},refresh:function(){this.legends=[];this._clearLabels();this.inherited(arguments);this._applyEvents();new v(this)},_clearLabels:function(){for(var a=this._cbs;a.length;)a.pop().destroyRecursive()},_addLabel:function(a,b){this.inherited(arguments);var c=e("td",this.legendBody),d=c[c.length-1];this.legends.push(d);c=new q({checked:!0});
this._cbs.push(c);s.place(c.domNode,d,"first");d=e("label",d)[0];t.set(d,"for",c.id)},_applyEvents:function(){this.chart.dirty||g.forEach(this.legends,function(a,b){var c,d,k;this._isPie()?(c=this.chart.stack[0],d=c.name,k=this.chart.series[0].name):(c=this.chart.series[b],d=c.plot,k=c.name);var h=u.byNode(e(".dijitCheckBox",a)[0]);h.set("checked",!this._isHidden(d,b));m.connect(h,"onClick",this,function(a){this.toogle(d,b,!h.get("checked"));a.stopPropagation()});var l=e(".dojoxLegendIcon",a)[0],
f=this._getFilledShape(this._surfaces[b].children);g.forEach(["onmouseenter","onmouseleave"],function(a){m.connect(l,a,this,function(a){this._highlight(a,f,b,!h.get("checked"),k,d)})},this)},this)},_isHidden:function(a,b){return this._isPie()?-1!=this.chart.getPlot(a).runFilter.indexOf(b):this.chart.series[b].hidden},toogle:function(a,b,c){a=this.chart.getPlot(a);this._isPie()?-1!=a.runFilter.indexOf(b)?c||(a.runFilter=g.filter(a.runFilter,function(a){return a!=b})):c&&a.runFilter.push(b):this.chart.series[b].hidden=
c;this.autoScale?this.chart.dirty=!0:a.dirty=!0;this.chart.render()},_highlight:function(a,b,c,d,k,h){if(!d){var l=this._getAnim(h),e=this._isPie(),f="mouseenter"==a.type?"onmouseover":"mouseleave"==a.type?"onmouseout":"on"+a.type;l.process({shape:b,index:e?"legend"+c:"legend",run:{name:k},type:f});g.forEach(this._getShapes(c,h),function(a,b){var d={shape:a,index:e?c:b,run:{name:k},type:f};l.duration=100;l.process(d)})}},_getShapes:function(a,b){var c=[];if(this._isPie()){var d=0;g.forEach(this.chart.getPlot(b).runFilter,
function(b){a>b&&d++});c.push(this.chart.stack[0].group.children[a-d])}else this._isCandleStick(b)?g.forEach(this.chart.series[a].group.children,function(a){g.forEach(a.children,function(a){g.forEach(a.children,function(a){"line"!=a.shape.type&&c.push(a)})})}):c=this.chart.series[a].group.children;return c},_getAnim:function(a){this.legendAnim[a]||(this.legendAnim[a]=new w(this.chart,a));return this.legendAnim[a]},_getTransitionFill:function(a){return-1!=this.chart.stack[this.chart.plots[a]].declaredClass.indexOf("dojox.charting.plot2d.Stacked")?
this.chart.theme.plotarea.fill:null},_getFilledShape:function(a){for(var b=0;a[b];){if(a[b].getFill())return a[b];b++}return null},_isPie:function(){return"dojox.charting.plot2d.Pie"==this.chart.stack[0].declaredClass},_isCandleStick:function(a){return"dojox.charting.plot2d.Candlesticks"==this.chart.stack[this.chart.plots[a]].declaredClass},destroy:function(){this._clearLabels();this.inherited(arguments)}})});
//# sourceMappingURL=SelectableLegend.js.map