//>>built
(function(l){"object"==typeof exports&&"object"==typeof module?l(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define("codemirror4/addon/merge/merge",["../../lib/codemirror"],l):l(CodeMirror)})(function(l){function w(a,c){this.mv=a;this.type=c;this.classes="left"==c?{chunk:"CodeMirror-merge-l-chunk",start:"CodeMirror-merge-l-chunk-start",end:"CodeMirror-merge-l-chunk-end",insert:"CodeMirror-merge-l-inserted",del:"CodeMirror-merge-l-deleted",connect:"CodeMirror-merge-l-connect"}:
{chunk:"CodeMirror-merge-r-chunk",start:"CodeMirror-merge-r-chunk-start",end:"CodeMirror-merge-r-chunk-end",insert:"CodeMirror-merge-r-inserted",del:"CodeMirror-merge-r-deleted",connect:"CodeMirror-merge-r-connect"}}function F(a){a.diffOutOfDate&&(a.diff=G(a.orig.getValue(),a.edit.getValue()),a.diffOutOfDate=!1,l.signal(a.edit,"updateDiff",a.diff))}function R(a){function c(b){"full"==b&&(a.svg&&v(a.svg),v(a.copyButtons),z(a.edit,f.marked,a.classes),z(a.orig,g.marked,a.classes),f.from=f.to=g.from=
g.to=0);F(a);a.showDifferences&&(H(a.edit,a.diff,f,DIFF_INSERT,a.classes),H(a.orig,a.diff,g,DIFF_DELETE,a.classes));s(a)}function b(a){clearTimeout(m);m=setTimeout(c,!0==a?250:100)}function d(){a.diffOutOfDate||(a.diffOutOfDate=!0,f.from=f.to=g.from=g.to=0);b(!0)}var f={from:0,to:0,marked:[]},g={from:0,to:0,marked:[]},m;a.edit.on("change",d);a.orig.on("change",d);a.edit.on("markerAdded",b);a.edit.on("markerCleared",b);a.orig.on("markerAdded",b);a.orig.on("markerCleared",b);a.edit.on("viewportChange",
b);a.orig.on("viewportChange",b);c();return c}function S(a){a.edit.on("scroll",function(){A(a,DIFF_INSERT)&&s(a)});a.orig.on("scroll",function(){A(a,DIFF_DELETE)&&s(a)})}function A(a,c){if(a.diffOutOfDate)return!1;if(!a.lockScroll)return!0;var b,d,f=+new Date;c==DIFF_INSERT?(b=a.edit,d=a.orig):(b=a.orig,d=a.edit);if(b.state.scrollSetBy==a&&(b.state.scrollSetAt||0)+50>f)return!1;var g=b.getScrollInfo(),m=0.5*g.clientHeight,k=g.top+m,e=b.lineAtHeight(k,"local"),e=T(a.diff,e,c==DIFF_INSERT);b=I(b,c==
DIFF_INSERT?e.edit:e.orig);var e=I(d,c==DIFF_INSERT?e.orig:e.edit),k=e.top-m+(k-b.top)/(b.bot-b.top)*(e.bot-e.top),h;if(k>g.top&&1>(h=g.top/m))k=k*h+g.top*(1-h);else if((b=g.height-g.clientHeight-g.top)<m)if(e=d.getScrollInfo(),e.height-e.clientHeight-k>b&&1>(h=b/m))k=k*h+(e.height-e.clientHeight-b)*(1-h);d.scrollTo(g.left,k);d.state.scrollSetAt=f;d.state.scrollSetBy=a;return!0}function I(a,c){var b=c.after;null==b&&(b=a.lastLine()+1);return{top:a.heightAtLine(c.before||0,"local"),bot:a.heightAtLine(b,
"local")}}function J(a,c,b){(a.lockScroll=c)&&!1!=b&&A(a,DIFF_INSERT)&&s(a);a.lockButton.innerHTML=c?"\u21db\u21da":"\u21db\x26nbsp;\x26nbsp;\u21da"}function z(a,c,b){for(var d=0;d<c.length;++d){var f=c[d];f instanceof l.TextMarker?f.clear():f.parent&&(a.removeLineClass(f,"background",b.chunk),a.removeLineClass(f,"background",b.start),a.removeLineClass(f,"background",b.end))}c.length=0}function H(a,c,b,d,f){var g=a.getViewport();a.operation(function(){b.from==b.to||20<g.from-b.to||20<b.from-g.to?
(z(a,b.marked,f),B(a,c,d,b.marked,g.from,g.to,f),b.from=g.from,b.to=g.to):(g.from<b.from&&(B(a,c,d,b.marked,g.from,b.from,f),b.from=g.from),g.to>b.to&&(B(a,c,d,b.marked,b.to,g.to,f),b.to=g.to))})}function B(a,c,b,d,f,g,m){function k(b,c){for(var e=Math.max(f,b),k=Math.min(g,c),h=e;h<k;++h){var n=a.addLineClass(h,"background",m.chunk);h==b&&a.addLineClass(n,"background",m.start);h==c-1&&a.addLineClass(n,"background",m.end);d.push(n)}b==c&&(e==c&&k==c)&&(e?d.push(a.addLineClass(e-1,"background",m.end)):
d.push(a.addLineClass(e,"background",m.start)))}for(var e=t(0,0),h=t(f,0),C=a.clipPos(t(g-1)),r=b==DIFF_DELETE?m.del:m.insert,l=0,p=0;p<c.length;++p){var q=c[p],n=q[0],q=q[1];n==DIFF_EQUAL?(n=e.line+(K(c,p)?0:1),x(e,q),q=e.line+(L(c,p)?1:0),q>n&&(p&&k(l,n),l=q)):n==b&&(n=x(e,q,!0),e=0<(h.line-e.line||h.ch-e.ch)?h:e,q=0>(C.line-n.line||C.ch-n.ch)?C:n,e.line==q.line&&e.ch==q.ch||d.push(a.markText(e,q,{className:r})),e=n)}l<=e.line&&k(l,e.line+1)}function s(a){if(a.showDifferences){if(a.svg){v(a.svg);
var c=a.gap.offsetWidth;M(a.svg,"width",c,"height",a.gap.offsetHeight)}v(a.copyButtons);var b="left"==a.type,d=a.edit.getViewport(),f=a.orig.getViewport(),g=a.edit.getScrollInfo().top,m=a.orig.getScrollInfo().top;D(a.diff,function(k,e,h,l){if(!(h>d.to||l<d.from||k>f.to||e<f.from)){var r=a.orig.heightAtLine(k,"local")-m,t=r;if(a.svg){var p=a.edit.heightAtLine(h,"local")-g;if(b)var q=r,r=p,p=q;var n=a.orig.heightAtLine(e,"local")-m,s=a.edit.heightAtLine(l,"local")-g;b&&(q=n,n=s,s=q);r=" C "+c/2+" "+
p+" "+c/2+" "+r+" "+(c+2)+" "+r;s=" C "+c/2+" "+n+" "+c/2+" "+s+" -1 "+s;M(a.svg.appendChild(document.createElementNS(N,"path")),"d","M -1 "+p+r+" L "+(c+2)+" "+n+s+" z","class",a.classes.connect)}p=a.copyButtons.appendChild(u("div","left"==a.type?"\u21dd":"\u21dc","CodeMirror-merge-copy"));p.title="Revert chunk";p.chunk={topEdit:h,botEdit:l,topOrig:k,botOrig:e};p.style.top=t+"px"}})}}function O(a){var c=a.lockButton=u("div",null,"CodeMirror-merge-scrolllock");c.title="Toggle locked scrolling";var b=
u("div",[c],"CodeMirror-merge-scrolllock-wrap");l.on(c,"click",function(){J(a,!a.lockScroll)});a.copyButtons=u("div",null,"CodeMirror-merge-copybuttons-"+a.type);l.on(a.copyButtons,"click",function(b){b=b.target||b.srcElement;b.chunk&&(b=b.chunk,a.diffOutOfDate||a.edit.replaceRange(a.orig.getRange(t(b.topOrig,0),t(b.botOrig,0)),t(b.topEdit,0),t(b.botEdit,0)))});c=[a.copyButtons,b];(b=document.createElementNS&&document.createElementNS(N,"svg"))&&!b.createSVGRect&&(b=null);(a.svg=b)&&c.push(b);return a.gap=
u("div",c,"CodeMirror-merge-gap")}function G(a,c){var b=P.diff_main(a,c);P.diff_cleanupSemantic(b);for(var d=0;d<b.length;++d){var f=b[d];f[1]?d&&b[d-1][0]==f[0]&&(b.splice(d--,1),b[d][1]+=f[1]):b.splice(d--,1)}return b}function D(a,c){for(var b=0,d=0,f=t(0,0),g=t(0,0),m=0;m<a.length;++m){var k=a[m],e=k[0];if(e==DIFF_EQUAL){var h=K(a,m)?0:1,e=f.line+h,h=g.line+h;x(f,k[1],null,g);var l=L(a,m)?1:0,k=f.line+l,l=g.line+l;k>e&&(m&&c(d,h,b,e),b=k,d=l)}else x(e==DIFF_INSERT?f:g,k[1])}(b<=f.line||d<=g.line)&&
c(d,g.line+1,b,f.line+1)}function Q(a){F(a);var c=[];D(a.diff,function(a,d,f,g){c.push({origFrom:a,origTo:d,editFrom:f,editTo:g})});return c}function L(a,c){if(c==a.length-1)return!0;var b=a[c+1][1];if(1==b.length||10!=b.charCodeAt(0))return!1;if(c==a.length-2)return!0;b=a[c+2][1];return 1<b.length&&10==b.charCodeAt(0)}function K(a,c){if(0==c)return!0;var b=a[c-1][1];if(10!=b.charCodeAt(b.length-1))return!1;if(1==c)return!0;b=a[c-2][1];return 10==b.charCodeAt(b.length-1)}function T(a,c,b){var d,f,
g,m;D(a,function(a,e,h,l){var r=b?h:a,s=b?l:e;null==f&&(r>c?(f=h,m=a):s>c&&(f=l,m=e));s<=c?(d=l,g=e):r<=c&&(d=h,g=a)});return{edit:{before:d,after:f},orig:{before:g,after:m}}}function u(a,c,b,d){a=document.createElement(a);b&&(a.className=b);d&&(a.style.cssText=d);if("string"==typeof c)a.appendChild(document.createTextNode(c));else if(c)for(b=0;b<c.length;++b)a.appendChild(c[b]);return a}function v(a){for(var c=a.childNodes.length;0<c;--c)a.removeChild(a.firstChild)}function M(a){for(var c=1;c<arguments.length;c+=
2)a.setAttribute(arguments[c],arguments[c+1])}function E(a,c){c||(c={});for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b]);return c}function x(a,c,b,d){a=b?t(a.line,a.ch):a;for(b=0;;){var f=c.indexOf("\n",b);if(-1==f)break;++a.line;d&&++d.line;b=f+1}a.ch=(b?0:a.ch)+(c.length-b);d&&(d.ch=(b?0:d.ch)+(c.length-b));return a}var t=l.Pos,N="http://www.w3.org/2000/svg";w.prototype={constructor:w,init:function(a,c,b){this.edit=this.mv.edit;this.orig=l(a,E({value:c,readOnly:!0},E(b)));this.diff=G("string"==typeof c?
c:c.getValue(),"string"==typeof b.value?b.value:b.value.getValue());this.diffOutOfDate=!1;this.showDifferences=!1!==b.showDifferences;this.forceUpdate=R(this);J(this,!0,!1);S(this)},setShowDifferences:function(a){a=!1!==a;a!=this.showDifferences&&(this.showDifferences=a,this.forceUpdate("full"))}};var y=l.MergeView=function(a,c){if(!(this instanceof y))return new y(a,c);var b=c.origLeft,d=null==c.origRight?c.orig:c.origRight,f=null!=b,g=null!=d,m=1+(f?1:0)+(g?1:0),k=[],e=this.left=null,h=this.right=
null;if(f){var e=this.left=new w(this,"left"),t=u("div",null,"CodeMirror-merge-pane");k.push(t);k.push(O(e))}f=u("div",null,"CodeMirror-merge-pane");k.push(f);if(g){h=this.right=new w(this,"right");k.push(O(h));var r=u("div",null,"CodeMirror-merge-pane");k.push(r)}(g?r:f).className+=" CodeMirror-merge-pane-rightmost";k.push(u("div",null,null,"height: 0; clear: both;"));var v=this.wrap=a.appendChild(u("div",k,"CodeMirror-merge CodeMirror-merge-"+m+"pane"));this.edit=l(f,E(c));e&&e.init(t,b,c);h&&h.init(r,
d,c);var p=function(){e&&s(e);h&&s(h)};l.on(window,"resize",p);var q=setInterval(function(){for(var a=v.parentNode;a&&a!=document.body;a=a.parentNode);a||(clearInterval(q),l.off(window,"resize",p))},5E3)};y.prototype={constuctor:y,editor:function(){return this.edit},rightOriginal:function(){return this.right&&this.right.orig},leftOriginal:function(){return this.left&&this.left.orig},setShowDifferences:function(a){this.right&&this.right.setShowDifferences(a);this.left&&this.left.setShowDifferences(a)},
rightChunks:function(){return this.right&&Q(this.right)},leftChunks:function(){return this.left&&Q(this.left)}};var P=new diff_match_patch});
//# sourceMappingURL=merge.js.map