//>>built
define("codemirror4/addon/merge/dep/diff_match_patch",["dojo","dijit","dojox"],function(z,A,B){(function(){function k(){this.Diff_Timeout=1;this.Diff_EditCost=4;this.Match_Threshold=0.5;this.Match_Distance=1E3;this.Patch_DeleteThreshold=0.5;this.Patch_Margin=4;this.Match_MaxBits=32}k.prototype.diff_main=function(a,b,c,d){"undefined"==typeof d&&(d=0>=this.Diff_Timeout?Number.MAX_VALUE:(new Date).getTime()+1E3*this.Diff_Timeout);if(null==a||null==b)throw Error("Null input. (diff_main)");if(a==b)return a?
[[0,a]]:[];"undefined"==typeof c&&(c=!0);var e=c,f=this.diff_commonPrefix(a,b);c=a.substring(0,f);a=a.substring(f);b=b.substring(f);var f=this.diff_commonSuffix(a,b),g=a.substring(a.length-f);a=a.substring(0,a.length-f);b=b.substring(0,b.length-f);a=this.diff_compute_(a,b,e,d);c&&a.unshift([0,c]);g&&a.push([0,g]);this.diff_cleanupMerge(a);return a};k.prototype.diff_compute_=function(a,b,c,d){if(!a)return[[1,b]];if(!b)return[[-1,a]];var e=a.length>b.length?a:b,f=a.length>b.length?b:a,g=e.indexOf(f);
return-1!=g?(c=[[1,e.substring(0,g)],[0,f],[1,e.substring(g+f.length)]],a.length>b.length&&(c[0][0]=c[2][0]=-1),c):1==f.length?[[-1,a],[1,b]]:(e=this.diff_halfMatch_(a,b))?(f=e[0],a=e[1],g=e[2],b=e[3],e=e[4],f=this.diff_main(f,g,c,d),c=this.diff_main(a,b,c,d),f.concat([[0,e]],c)):c&&100<a.length&&100<b.length?this.diff_lineMode_(a,b,d):this.diff_bisect_(a,b,d)};k.prototype.diff_lineMode_=function(a,b,c){var d=this.diff_linesToChars_(a,b);a=d.chars1;b=d.chars2;d=d.lineArray;a=this.diff_main(a,b,!1,
c);this.diff_charsToLines_(a,d);this.diff_cleanupSemantic(a);a.push([0,""]);for(var e=d=b=0,f="",g="";b<a.length;){switch(a[b][0]){case 1:e++;g+=a[b][1];break;case -1:d++;f+=a[b][1];break;case 0:if(1<=d&&1<=e){a.splice(b-d-e,d+e);b=b-d-e;d=this.diff_main(f,g,!1,c);for(e=d.length-1;0<=e;e--)a.splice(b,0,d[e]);b+=d.length}d=e=0;g=f=""}b++}a.pop();return a};k.prototype.diff_bisect_=function(a,b,c){for(var d=a.length,e=b.length,f=Math.ceil((d+e)/2),g=2*f,h=Array(g),m=Array(g),l=0;l<g;l++)h[l]=-1,m[l]=
-1;h[f+1]=0;m[f+1]=0;for(var l=d-e,k=0!=l%2,t=0,y=0,x=0,r=0,u=0;u<f&&!((new Date).getTime()>c);u++){for(var s=-u+t;s<=u-y;s+=2){var n=f+s,p;p=s==-u||s!=u&&h[n-1]<h[n+1]?h[n+1]:h[n-1]+1;for(var w=p-s;p<d&&w<e&&a.charAt(p)==b.charAt(w);)p++,w++;h[n]=p;if(p>d)y+=2;else if(w>e)t+=2;else if(k&&(n=f+l-s,0<=n&&n<g&&-1!=m[n])){var v=d-m[n];if(p>=v)return this.diff_bisectSplit_(a,b,p,w,c)}}for(s=-u+x;s<=u-r;s+=2){n=f+s;v=s==-u||s!=u&&m[n-1]<m[n+1]?m[n+1]:m[n-1]+1;for(p=v-s;v<d&&p<e&&a.charAt(d-v-1)==b.charAt(e-
p-1);)v++,p++;m[n]=v;if(v>d)r+=2;else if(p>e)x+=2;else if(!k&&(n=f+l-s,0<=n&&n<g&&-1!=h[n]&&(p=h[n],w=f+p-n,v=d-v,p>=v)))return this.diff_bisectSplit_(a,b,p,w,c)}}return[[-1,a],[1,b]]};k.prototype.diff_bisectSplit_=function(a,b,c,d,e){var f=a.substring(0,c),g=b.substring(0,d);a=a.substring(c);b=b.substring(d);f=this.diff_main(f,g,!1,e);e=this.diff_main(a,b,!1,e);return f.concat(e)};k.prototype.diff_linesToChars_=function(a,b){function c(a){for(var b="",c=0,f=-1,g=d.length;f<a.length-1;){f=a.indexOf("\n",
c);-1==f&&(f=a.length-1);var k=a.substring(c,f+1),c=f+1;(e.hasOwnProperty?e.hasOwnProperty(k):void 0!==e[k])?b+=String.fromCharCode(e[k]):(b+=String.fromCharCode(g),e[k]=g,d[g++]=k)}return b}var d=[],e={};d[0]="";var f=c(a),g=c(b);return{chars1:f,chars2:g,lineArray:d}};k.prototype.diff_charsToLines_=function(a,b){for(var c=0;c<a.length;c++){for(var d=a[c][1],e=[],f=0;f<d.length;f++)e[f]=b[d.charCodeAt(f)];a[c][1]=e.join("")}};k.prototype.diff_commonPrefix=function(a,b){if(!a||!b||a.charAt(0)!=b.charAt(0))return 0;
for(var c=0,d=Math.min(a.length,b.length),e=d,f=0;c<e;)a.substring(f,e)==b.substring(f,e)?f=c=e:d=e,e=Math.floor((d-c)/2+c);return e};k.prototype.diff_commonSuffix=function(a,b){if(!a||!b||a.charAt(a.length-1)!=b.charAt(b.length-1))return 0;for(var c=0,d=Math.min(a.length,b.length),e=d,f=0;c<e;)a.substring(a.length-e,a.length-f)==b.substring(b.length-e,b.length-f)?f=c=e:d=e,e=Math.floor((d-c)/2+c);return e};k.prototype.diff_commonOverlap_=function(a,b){var c=a.length,d=b.length;if(0==c||0==d)return 0;
c>d?a=a.substring(c-d):c<d&&(b=b.substring(0,c));c=Math.min(c,d);if(a==b)return c;for(var d=0,e=1;;){var f=a.substring(c-e),f=b.indexOf(f);if(-1==f)return d;e+=f;if(0==f||a.substring(c-e)==b.substring(0,e))d=e,e++}};k.prototype.diff_halfMatch_=function(a,b){function c(a,b,c){for(var d=a.substring(c,c+Math.floor(a.length/4)),e=-1,g="",h,m,k,p;-1!=(e=b.indexOf(d,e+1));){var w=f.diff_commonPrefix(a.substring(c),b.substring(e)),v=f.diff_commonSuffix(a.substring(0,c),b.substring(0,e));g.length<v+w&&(g=
b.substring(e-v,e)+b.substring(e,e+w),h=a.substring(0,c-v),m=a.substring(c+w),k=b.substring(0,e-v),p=b.substring(e+w))}return 2*g.length>=a.length?[h,m,k,p,g]:null}if(0>=this.Diff_Timeout)return null;var d=a.length>b.length?a:b,e=a.length>b.length?b:a;if(4>d.length||2*e.length<d.length)return null;var f=this,g=c(d,e,Math.ceil(d.length/4)),d=c(d,e,Math.ceil(d.length/2)),h;if(!g&&!d)return null;h=d?g?g[4].length>d[4].length?g:d:d:g;var m;a.length>b.length?(g=h[0],d=h[1],e=h[2],m=h[3]):(e=h[0],m=h[1],
g=h[2],d=h[3]);h=h[4];return[g,d,e,m,h]};k.prototype.diff_cleanupSemantic=function(a){for(var b=!1,c=[],d=0,e=null,f=0,g=0,h=0,m=0,l=0;f<a.length;)0==a[f][0]?(c[d++]=f,g=m,h=l,l=m=0,e=a[f][1]):(1==a[f][0]?m+=a[f][1].length:l+=a[f][1].length,e&&e.length<=Math.max(g,h)&&e.length<=Math.max(m,l)&&(a.splice(c[d-1],0,[-1,e]),a[c[d-1]+1][0]=1,d--,d--,f=0<d?c[d-1]:-1,l=m=h=g=0,e=null,b=!0)),f++;b&&this.diff_cleanupMerge(a);this.diff_cleanupSemanticLossless(a);for(f=1;f<a.length;){if(-1==a[f-1][0]&&1==a[f][0]){b=
a[f-1][1];c=a[f][1];d=this.diff_commonOverlap_(b,c);e=this.diff_commonOverlap_(c,b);if(d>=e){if(d>=b.length/2||d>=c.length/2)a.splice(f,0,[0,c.substring(0,d)]),a[f-1][1]=b.substring(0,b.length-d),a[f+1][1]=c.substring(d),f++}else if(e>=b.length/2||e>=c.length/2)a.splice(f,0,[0,b.substring(0,e)]),a[f-1][0]=1,a[f-1][1]=c.substring(0,c.length-e),a[f+1][0]=-1,a[f+1][1]=b.substring(e),f++;f++}f++}};k.prototype.diff_cleanupSemanticLossless=function(a){function b(a,b){if(!a||!b)return 6;var c=a.charAt(a.length-
1),d=b.charAt(0),e=c.match(k.nonAlphaNumericRegex_),f=d.match(k.nonAlphaNumericRegex_),g=e&&c.match(k.whitespaceRegex_),h=f&&d.match(k.whitespaceRegex_),c=g&&c.match(k.linebreakRegex_),d=h&&d.match(k.linebreakRegex_),l=c&&a.match(k.blanklineEndRegex_),m=d&&b.match(k.blanklineStartRegex_);return l||m?5:c||d?4:e&&!g&&h?3:g||h?2:e||f?1:0}for(var c=1;c<a.length-1;){if(0==a[c-1][0]&&0==a[c+1][0]){var d=a[c-1][1],e=a[c][1],f=a[c+1][1],g=this.diff_commonSuffix(d,e);if(g)var h=e.substring(e.length-g),d=d.substring(0,
d.length-g),e=h+e.substring(0,e.length-g),f=h+f;for(var g=d,h=e,m=f,l=b(d,e)+b(e,f);e.charAt(0)===f.charAt(0);){var d=d+e.charAt(0),e=e.substring(1)+f.charAt(0),f=f.substring(1),q=b(d,e)+b(e,f);q>=l&&(l=q,g=d,h=e,m=f)}a[c-1][1]!=g&&(g?a[c-1][1]=g:(a.splice(c-1,1),c--),a[c][1]=h,m?a[c+1][1]=m:(a.splice(c+1,1),c--))}c++}};k.nonAlphaNumericRegex_=/[^a-zA-Z0-9]/;k.whitespaceRegex_=/\s/;k.linebreakRegex_=/[\r\n]/;k.blanklineEndRegex_=/\n\r?\n$/;k.blanklineStartRegex_=/^\r?\n\r?\n/;k.prototype.diff_cleanupEfficiency=
function(a){for(var b=!1,c=[],d=0,e=null,f=0,g=!1,h=!1,m=!1,l=!1;f<a.length;){if(0==a[f][0])a[f][1].length<this.Diff_EditCost&&(m||l)?(c[d++]=f,g=m,h=l,e=a[f][1]):(d=0,e=null),m=l=!1;else if(-1==a[f][0]?l=!0:m=!0,e&&(g&&h&&m&&l||e.length<this.Diff_EditCost/2&&3==g+h+m+l))a.splice(c[d-1],0,[-1,e]),a[c[d-1]+1][0]=1,d--,e=null,g&&h?(m=l=!0,d=0):(d--,f=0<d?c[d-1]:-1,m=l=!1),b=!0;f++}b&&this.diff_cleanupMerge(a)};k.prototype.diff_cleanupMerge=function(a){a.push([0,""]);for(var b=0,c=0,d=0,e="",f="",g;b<
a.length;)switch(a[b][0]){case 1:d++;f+=a[b][1];b++;break;case -1:c++;e+=a[b][1];b++;break;case 0:1<c+d?(0!==c&&0!==d&&(g=this.diff_commonPrefix(f,e),0!==g&&(0<b-c-d&&0==a[b-c-d-1][0]?a[b-c-d-1][1]+=f.substring(0,g):(a.splice(0,0,[0,f.substring(0,g)]),b++),f=f.substring(g),e=e.substring(g)),g=this.diff_commonSuffix(f,e),0!==g&&(a[b][1]=f.substring(f.length-g)+a[b][1],f=f.substring(0,f.length-g),e=e.substring(0,e.length-g))),0===c?a.splice(b-d,c+d,[1,f]):0===d?a.splice(b-c,c+d,[-1,e]):a.splice(b-c-
d,c+d,[-1,e],[1,f]),b=b-c-d+(c?1:0)+(d?1:0)+1):0!==b&&0==a[b-1][0]?(a[b-1][1]+=a[b][1],a.splice(b,1)):b++,c=d=0,f=e=""}""===a[a.length-1][1]&&a.pop();c=!1;for(b=1;b<a.length-1;)0==a[b-1][0]&&0==a[b+1][0]&&(a[b][1].substring(a[b][1].length-a[b-1][1].length)==a[b-1][1]?(a[b][1]=a[b-1][1]+a[b][1].substring(0,a[b][1].length-a[b-1][1].length),a[b+1][1]=a[b-1][1]+a[b+1][1],a.splice(b-1,1),c=!0):a[b][1].substring(0,a[b+1][1].length)==a[b+1][1]&&(a[b-1][1]+=a[b+1][1],a[b][1]=a[b][1].substring(a[b+1][1].length)+
a[b+1][1],a.splice(b+1,1),c=!0)),b++;c&&this.diff_cleanupMerge(a)};k.prototype.diff_xIndex=function(a,b){var c=0,d=0,e=0,f=0,g;for(g=0;g<a.length;g++){1!==a[g][0]&&(c+=a[g][1].length);-1!==a[g][0]&&(d+=a[g][1].length);if(c>b)break;e=c;f=d}return a.length!=g&&-1===a[g][0]?f:f+(b-e)};k.prototype.diff_prettyHtml=function(a){for(var b=[],c=/&/g,d=/</g,e=/>/g,f=/\n/g,g=0;g<a.length;g++){var h=a[g][0],m=a[g][1],m=m.replace(c,"\x26amp;").replace(d,"\x26lt;").replace(e,"\x26gt;").replace(f,"\x26para;\x3cbr\x3e");
switch(h){case 1:b[g]='\x3cins style\x3d"background:#e6ffe6;"\x3e'+m+"\x3c/ins\x3e";break;case -1:b[g]='\x3cdel style\x3d"background:#ffe6e6;"\x3e'+m+"\x3c/del\x3e";break;case 0:b[g]="\x3cspan\x3e"+m+"\x3c/span\x3e"}}return b.join("")};k.prototype.diff_text1=function(a){for(var b=[],c=0;c<a.length;c++)1!==a[c][0]&&(b[c]=a[c][1]);return b.join("")};k.prototype.diff_text2=function(a){for(var b=[],c=0;c<a.length;c++)-1!==a[c][0]&&(b[c]=a[c][1]);return b.join("")};k.prototype.diff_levenshtein=function(a){for(var b=
0,c=0,d=0,e=0;e<a.length;e++){var f=a[e][1];switch(a[e][0]){case 1:c+=f.length;break;case -1:d+=f.length;break;case 0:b+=Math.max(c,d),d=c=0}}return b+Math.max(c,d)};k.prototype.diff_toDelta=function(a){for(var b=[],c=0;c<a.length;c++)switch(a[c][0]){case 1:b[c]="+"+encodeURI(a[c][1]);break;case -1:b[c]="-"+a[c][1].length;break;case 0:b[c]="\x3d"+a[c][1].length}return b.join("\t").replace(/%20/g," ")};k.prototype.diff_fromDelta=function(a,b){for(var c=[],d=0,e=0,f=b.split(/\t/g),g=0;g<f.length;g++){var h=
f[g].substring(1);switch(f[g].charAt(0)){case "+":try{c[d++]=[1,decodeURI(h)]}catch(m){throw Error("Illegal escape in diff_fromDelta: "+h);}break;case "-":case "\x3d":var l=parseInt(h,10);if(isNaN(l)||0>l)throw Error("Invalid number in diff_fromDelta: "+h);h=a.substring(e,e+=l);"\x3d"==f[g].charAt(0)?c[d++]=[0,h]:c[d++]=[-1,h];break;default:if(f[g])throw Error("Invalid diff operation in diff_fromDelta: "+f[g]);}}if(e!=a.length)throw Error("Delta length ("+e+") does not equal source text length ("+
a.length+").");return c};k.prototype.match_main=function(a,b,c){if(null==a||null==b||null==c)throw Error("Null input. (match_main)");c=Math.max(0,Math.min(c,a.length));return a==b?0:a.length?a.substring(c,c+b.length)==b?c:this.match_bitap_(a,b,c):-1};k.prototype.match_bitap_=function(a,b,c){function d(a,d){var e=a/b.length,g=Math.abs(c-d);return!f.Match_Distance?g?1:e:e+g/f.Match_Distance}if(b.length>this.Match_MaxBits)throw Error("Pattern too long for this browser.");var e=this.match_alphabet_(b),
f=this,g=this.Match_Threshold,h=a.indexOf(b,c);-1!=h&&(g=Math.min(d(0,h),g),h=a.lastIndexOf(b,c+b.length),-1!=h&&(g=Math.min(d(0,h),g)));for(var m=1<<b.length-1,h=-1,l,k,t=b.length+a.length,y,x=0;x<b.length;x++){l=0;for(k=t;l<k;)d(x,c+k)<=g?l=k:t=k,k=Math.floor((t-l)/2+l);t=k;l=Math.max(1,c-k+1);var r=Math.min(c+k,a.length)+b.length;k=Array(r+2);for(k[r+1]=(1<<x)-1;r>=l;r--){var u=e[a.charAt(r-1)];k[r]=0===x?(k[r+1]<<1|1)&u:(k[r+1]<<1|1)&u|((y[r+1]|y[r])<<1|1)|y[r+1];if(k[r]&m&&(u=d(x,r-1),u<=g))if(g=
u,h=r-1,h>c)l=Math.max(1,2*c-h);else break}if(d(x+1,c)>g)break;y=k}return h};k.prototype.match_alphabet_=function(a){for(var b={},c=0;c<a.length;c++)b[a.charAt(c)]=0;for(c=0;c<a.length;c++)b[a.charAt(c)]|=1<<a.length-c-1;return b};k.prototype.patch_addContext_=function(a,b){if(0!=b.length){for(var c=b.substring(a.start2,a.start2+a.length1),d=0;b.indexOf(c)!=b.lastIndexOf(c)&&c.length<this.Match_MaxBits-this.Patch_Margin-this.Patch_Margin;)d+=this.Patch_Margin,c=b.substring(a.start2-d,a.start2+a.length1+
d);d+=this.Patch_Margin;(c=b.substring(a.start2-d,a.start2))&&a.diffs.unshift([0,c]);(d=b.substring(a.start2+a.length1,a.start2+a.length1+d))&&a.diffs.push([0,d]);a.start1-=c.length;a.start2-=c.length;a.length1+=c.length+d.length;a.length2+=c.length+d.length}};k.prototype.patch_make=function(a,b,c){var d;if("string"==typeof a&&"string"==typeof b&&"undefined"==typeof c)d=a,b=this.diff_main(d,b,!0),2<b.length&&(this.diff_cleanupSemantic(b),this.diff_cleanupEfficiency(b));else if(a&&"object"==typeof a&&
"undefined"==typeof b&&"undefined"==typeof c)b=a,d=this.diff_text1(b);else if("string"==typeof a&&b&&"object"==typeof b&&"undefined"==typeof c)d=a;else if("string"==typeof a&&"string"==typeof b&&c&&"object"==typeof c)d=a,b=c;else throw Error("Unknown call format to patch_make.");if(0===b.length)return[];c=[];a=new k.patch_obj;for(var e=0,f=0,g=0,h=d,m=0;m<b.length;m++){var l=b[m][0],q=b[m][1];!e&&0!==l&&(a.start1=f,a.start2=g);switch(l){case 1:a.diffs[e++]=b[m];a.length2+=q.length;d=d.substring(0,
g)+q+d.substring(g);break;case -1:a.length1+=q.length;a.diffs[e++]=b[m];d=d.substring(0,g)+d.substring(g+q.length);break;case 0:q.length<=2*this.Patch_Margin&&e&&b.length!=m+1?(a.diffs[e++]=b[m],a.length1+=q.length,a.length2+=q.length):q.length>=2*this.Patch_Margin&&e&&(this.patch_addContext_(a,h),c.push(a),a=new k.patch_obj,e=0,h=d,f=g)}1!==l&&(f+=q.length);-1!==l&&(g+=q.length)}e&&(this.patch_addContext_(a,h),c.push(a));return c};k.prototype.patch_deepCopy=function(a){for(var b=[],c=0;c<a.length;c++){var d=
a[c],e=new k.patch_obj;e.diffs=[];for(var f=0;f<d.diffs.length;f++)e.diffs[f]=d.diffs[f].slice();e.start1=d.start1;e.start2=d.start2;e.length1=d.length1;e.length2=d.length2;b[c]=e}return b};k.prototype.patch_apply=function(a,b){if(0==a.length)return[b,[]];a=this.patch_deepCopy(a);var c=this.patch_addPadding(a);b=c+b+c;this.patch_splitMax(a);for(var d=0,e=[],f=0;f<a.length;f++){var g=a[f].start2+d,h=this.diff_text1(a[f].diffs),k,l=-1;if(h.length>this.Match_MaxBits){if(k=this.match_main(b,h.substring(0,
this.Match_MaxBits),g),-1!=k&&(l=this.match_main(b,h.substring(h.length-this.Match_MaxBits),g+h.length-this.Match_MaxBits),-1==l||k>=l))k=-1}else k=this.match_main(b,h,g);if(-1==k)e[f]=!1,d-=a[f].length2-a[f].length1;else if(e[f]=!0,d=k-g,g=-1==l?b.substring(k,k+h.length):b.substring(k,l+this.Match_MaxBits),h==g)b=b.substring(0,k)+this.diff_text2(a[f].diffs)+b.substring(k+h.length);else if(g=this.diff_main(h,g,!1),h.length>this.Match_MaxBits&&this.diff_levenshtein(g)/h.length>this.Patch_DeleteThreshold)e[f]=
!1;else{this.diff_cleanupSemanticLossless(g);for(var h=0,q,l=0;l<a[f].diffs.length;l++){var t=a[f].diffs[l];0!==t[0]&&(q=this.diff_xIndex(g,h));1===t[0]?b=b.substring(0,k+q)+t[1]+b.substring(k+q):-1===t[0]&&(b=b.substring(0,k+q)+b.substring(k+this.diff_xIndex(g,h+t[1].length)));-1!==t[0]&&(h+=t[1].length)}}}b=b.substring(c.length,b.length-c.length);return[b,e]};k.prototype.patch_addPadding=function(a){for(var b=this.Patch_Margin,c="",d=1;d<=b;d++)c+=String.fromCharCode(d);for(d=0;d<a.length;d++)a[d].start1+=
b,a[d].start2+=b;var d=a[0],e=d.diffs;if(0==e.length||0!=e[0][0])e.unshift([0,c]),d.start1-=b,d.start2-=b,d.length1+=b,d.length2+=b;else if(b>e[0][1].length){var f=b-e[0][1].length;e[0][1]=c.substring(e[0][1].length)+e[0][1];d.start1-=f;d.start2-=f;d.length1+=f;d.length2+=f}d=a[a.length-1];e=d.diffs;0==e.length||0!=e[e.length-1][0]?(e.push([0,c]),d.length1+=b,d.length2+=b):b>e[e.length-1][1].length&&(f=b-e[e.length-1][1].length,e[e.length-1][1]+=c.substring(0,f),d.length1+=f,d.length2+=f);return c};
k.prototype.patch_splitMax=function(a){for(var b=this.Match_MaxBits,c=0;c<a.length;c++)if(!(a[c].length1<=b)){var d=a[c];a.splice(c--,1);for(var e=d.start1,f=d.start2,g="";0!==d.diffs.length;){var h=new k.patch_obj,m=!0;h.start1=e-g.length;h.start2=f-g.length;for(""!==g&&(h.length1=h.length2=g.length,h.diffs.push([0,g]));0!==d.diffs.length&&h.length1<b-this.Patch_Margin;){var g=d.diffs[0][0],l=d.diffs[0][1];1===g?(h.length2+=l.length,f+=l.length,h.diffs.push(d.diffs.shift()),m=!1):-1===g&&1==h.diffs.length&&
0==h.diffs[0][0]&&l.length>2*b?(h.length1+=l.length,e+=l.length,m=!1,h.diffs.push([g,l]),d.diffs.shift()):(l=l.substring(0,b-h.length1-this.Patch_Margin),h.length1+=l.length,e+=l.length,0===g?(h.length2+=l.length,f+=l.length):m=!1,h.diffs.push([g,l]),l==d.diffs[0][1]?d.diffs.shift():d.diffs[0][1]=d.diffs[0][1].substring(l.length))}g=this.diff_text2(h.diffs);g=g.substring(g.length-this.Patch_Margin);l=this.diff_text1(d.diffs).substring(0,this.Patch_Margin);""!==l&&(h.length1+=l.length,h.length2+=l.length,
0!==h.diffs.length&&0===h.diffs[h.diffs.length-1][0]?h.diffs[h.diffs.length-1][1]+=l:h.diffs.push([0,l]));m||a.splice(++c,0,h)}}};k.prototype.patch_toText=function(a){for(var b=[],c=0;c<a.length;c++)b[c]=a[c];return b.join("")};k.prototype.patch_fromText=function(a){var b=[];if(!a)return b;a=a.split("\n");for(var c=0,d=/^@@ -(\d+),?(\d*) \+(\d+),?(\d*) @@$/;c<a.length;){var e=a[c].match(d);if(!e)throw Error("Invalid patch string: "+a[c]);var f=new k.patch_obj;b.push(f);f.start1=parseInt(e[1],10);
""===e[2]?(f.start1--,f.length1=1):"0"==e[2]?f.length1=0:(f.start1--,f.length1=parseInt(e[2],10));f.start2=parseInt(e[3],10);""===e[4]?(f.start2--,f.length2=1):"0"==e[4]?f.length2=0:(f.start2--,f.length2=parseInt(e[4],10));for(c++;c<a.length;){e=a[c].charAt(0);try{var g=decodeURI(a[c].substring(1))}catch(h){throw Error("Illegal escape in patch_fromText: "+g);}if("-"==e)f.diffs.push([-1,g]);else if("+"==e)f.diffs.push([1,g]);else if(" "==e)f.diffs.push([0,g]);else if("@"==e)break;else if(""!==e)throw Error('Invalid patch mode "'+
e+'" in: '+g);c++}}return b};k.patch_obj=function(){this.diffs=[];this.start2=this.start1=null;this.length2=this.length1=0};k.patch_obj.prototype.toString=function(){var a,b;a=0===this.length1?this.start1+",0":1==this.length1?this.start1+1:this.start1+1+","+this.length1;b=0===this.length2?this.start2+",0":1==this.length2?this.start2+1:this.start2+1+","+this.length2;a=["@@ -"+a+" +"+b+" @@\n"];var c;for(b=0;b<this.diffs.length;b++){switch(this.diffs[b][0]){case 1:c="+";break;case -1:c="-";break;case 0:c=
" "}a[b+1]=c+encodeURI(this.diffs[b][1])+"\n"}return a.join("").replace(/%20/g," ")};this.diff_match_patch=k;this.DIFF_DELETE=-1;this.DIFF_INSERT=1;this.DIFF_EQUAL=0})()});
//# sourceMappingURL=diff_match_patch.js.map