//>>built
define("codemirror4/mode/gfm/test",["dojo","dijit","dojox"],function(e,f,g){(function(){function a(a){test.mode(a,c,Array.prototype.slice.call(arguments,1))}function b(a){test.mode(a,d,Array.prototype.slice.call(arguments,1))}var c=CodeMirror.getMode({tabSize:4},"gfm"),d=CodeMirror.getMode({tabSize:4},{name:"gfm",highlightFormatting:!0});b("codeBackticks","[comment\x26formatting\x26formatting-code `][comment foo][comment\x26formatting\x26formatting-code `]");b("doubleBackticks","[comment\x26formatting\x26formatting-code ``][comment foo ` bar][comment\x26formatting\x26formatting-code ``]");
b("codeBlock","[comment\x26formatting\x26formatting-code-block ```css]","[tag foo]","[comment\x26formatting\x26formatting-code-block ```]");b("taskList","[variable-2\x26formatting\x26formatting-list\x26formatting-list-ul - ][meta\x26formatting\x26formatting-task [ ]]][variable-2  foo]","[variable-2\x26formatting\x26formatting-list\x26formatting-list-ul - ][property\x26formatting\x26formatting-task [x]]][variable-2  foo]");a("emInWordAsterisk","foo[em *bar*]hello");a("emInWordUnderscore","foo_bar_hello");
a("emStrongUnderscore","[strong __][em\x26strong _foo__][em _] bar");a("fencedCodeBlocks","[comment ```]","[comment foo]","","[comment ```]","bar");a("fencedCodeBlockModeSwitching","[comment ```javascript]","[variable foo]","","[comment ```]","bar");a("taskListAsterisk","[variable-2 * []] foo]","[variable-2 * [ ]]bar]","[variable-2 * [x]]hello]","[variable-2 * ][meta [ ]]][variable-2  [world]]]","    [variable-3 * ][property [x]]][variable-3  foo]");a("taskListPlus","[variable-2 + []] foo]","[variable-2 + [ ]]bar]",
"[variable-2 + [x]]hello]","[variable-2 + ][meta [ ]]][variable-2  [world]]]","    [variable-3 + ][property [x]]][variable-3  foo]");a("taskListDash","[variable-2 - []] foo]","[variable-2 - [ ]]bar]","[variable-2 - [x]]hello]","[variable-2 - ][meta [ ]]][variable-2  [world]]]","    [variable-3 - ][property [x]]][variable-3  foo]");a("taskListNumber","[variable-2 1. []] foo]","[variable-2 2. [ ]]bar]","[variable-2 3. [x]]hello]","[variable-2 4. ][meta [ ]]][variable-2  [world]]]","    [variable-3 1. ][property [x]]][variable-3  foo]");
a("SHA","foo [link be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2] bar");a("SHAEmphasis","[em *foo ][em\x26link be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2][em *]");a("shortSHA","foo [link be6a8cc] bar");a("tooShortSHA","foo be6a8c bar");a("longSHA","foo be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd22 bar");a("badSHA","foo be6a8cc1c1ecfe9489fb51e4869af15a13fc2cg2 bar");a("userSHA","foo [link bar@be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2] hello");a("userSHAEmphasis","[em *foo ][em\x26link bar@be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2][em *]");
a("userProjectSHA","foo [link bar/hello@be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2] world");a("userProjectSHAEmphasis","[em *foo ][em\x26link bar/hello@be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2][em *]");a("num","foo [link #1] bar");a("numEmphasis","[em *foo ][em\x26link #1][em *]");a("badNum","foo #1bar hello");a("userNum","foo [link bar#1] hello");a("userNumEmphasis","[em *foo ][em\x26link bar#1][em *]");a("userProjectNum","foo [link bar/hello#1] world");a("userProjectNumEmphasis","[em *foo ][em\x26link bar/hello#1][em *]");
a("vanillaLink","foo [link http://www.example.com/] bar");a("vanillaLinkPunctuation","foo [link http://www.example.com/]. bar");a("vanillaLinkExtension","foo [link http://www.example.com/index.html] bar");a("vanillaLinkEmphasis","foo [em *][em\x26link http://www.example.com/index.html][em *] bar");a("notALink","[comment ```css]","[tag foo] {[property color]:[keyword black];}","[comment ```][link http://www.example.com/]");a("notALink","[comment ``foo `bar` http://www.example.com/``] hello");a("notALink",
"[comment `foo]","[link http://www.example.com/]","[comment `foo]","","[link http://www.example.com/]")})()});
//# sourceMappingURL=test.js.map