//>>built
(function(s){"object"==typeof exports&&"object"==typeof module?s(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define("codemirror4/mode/promiseland/promiseland",["../../lib/codemirror"],s):s(CodeMirror)})(function(s){s.defineMode("promiseland",function(ga,r){function n(a,d,e){A=a;D=e;return d}function B(a,d){var e=a.next();if('"'==e||"'"==e)return d.tokenize=ha(e),d.tokenize(a,d);if("."==e&&a.match(/^\d+(?:[eE][+\-]?\d+)?/))return n("number","number");if("."==e&&a.match(".."))return n("spread",
"meta");if(/[\[\]{}\(\),;\:\.]/.test(e))return n(e);if("\x3d"==e&&a.eat("\x3e"))return n("\x3d\x3e","operator");if("0"==e&&a.eat(/x/i))return a.eatWhile(/[\da-f]/i),n("number","number");if(/\d/.test(e))return a.match(/^\d*(?:\.\d*)?(?:[eE][+\-]?\d+)?/),n("number","number");if("/"==e){if(a.eat("*"))return d.tokenize=E,E(a,d);if(a.eat("/"))return a.skipToEnd(),n("comment","comment");if("operator"==d.lastType||"keyword c"==d.lastType||"sof"==d.lastType||/^[\[{}\(,;:]$/.test(d.lastType)){a:for(var e=
!1,c,b=!1;null!=(c=a.next());){if(!e){if("/"==c&&!b)break a;"["==c?b=!0:b&&"]"==c&&(b=!1)}e=!e&&"\\"==c}a.eatWhile(/[gimy]/);return n("regexp","string-2")}a.eatWhile(J);return n("operator","operator",a.current())}if("`"==e)return d.tokenize=K,K(a,d);if("#"==e)return a.skipToEnd(),n("error","error");if(J.test(e))return a.eatWhile(J),n("operator","operator",a.current());a.eatWhile(/[\w\$_]/);e=a.current();return(c=U.propertyIsEnumerable(e)&&U[e])&&"."!=d.lastType?n(c.type,c.style,e):n("variable","variable",
e)}function ha(a){return function(d,e){for(var c=!1,b;null!=(b=d.next())&&(b!=a||c);)c=!c&&"\\"==b;c||(e.tokenize=B);return n("string","string")}}function E(a,d){for(var e=!1,c;c=a.next();){if("/"==c&&e){d.tokenize=B;break}e="*"==c}return n("comment","comment")}function K(a,d){for(var e=!1,c;null!=(c=a.next());){if(!e&&("`"==c||"$"==c&&a.eat("{"))){d.tokenize=B;break}e=!e&&"\\"==c}return n("quasi","string-2",a.current())}function L(a,d){d.fatArrowAt&&(d.fatArrowAt=null);var e=a.string.indexOf("\x3d\x3e",
a.start);if(!(0>e)){for(var c=0,b=!1,e=e-1;0<=e;--e){var f=a.string.charAt(e),g=ia.indexOf(f);if(0<=g&&3>g){if(!c){++e;break}if(0==--c)break}else if(3<=g&&6>g)++c;else if(/[$\w]/.test(f))b=!0;else if(b&&!c){++e;break}}b&&!c&&(d.fatArrowAt=e)}}function V(a,d,b,c,f,g){this.indented=a;this.column=d;this.type=b;this.prev=f;this.info=g;null!=c&&(this.align=c)}function g(){for(var a=arguments.length-1;0<=a;a--)f.cc.push(arguments[a])}function b(){g.apply(null,arguments);return!0}function t(a){function d(d){for(;d;d=
d.next)if(d.name==a)return!0;return!1}var b=f.state;b.context?(f.marked="def",d(b.localVars)||(b.localVars={name:a,next:b.localVars})):!d(b.globalVars)&&r.globalVars&&(b.globalVars={name:a,next:b.globalVars})}function u(){f.state.context={prev:f.state.context,vars:f.state.localVars};f.state.localVars=ja}function v(){f.state.localVars=f.state.context.vars;f.state.context=f.state.context.prev}function k(a,d){var b=function(){var b=f.state,e=b.indented;"stat"==b.lexical.type&&(e=b.lexical.indented);
b.lexical=new V(e,f.stream.column(),a,null,b.lexical,d)};b.lex=!0;return b}function h(){var a=f.state;a.lexical.prev&&(")"==a.lexical.type&&(a.indented=a.lexical.indented),a.lexical=a.lexical.prev)}function l(a){function d(e){return e==a?b():";"==a?g():b(d)}return d}function p(a,d){return"var"==a?b(k("vardef",d.length),M,l(";"),h):"keyword a"==a?b(k("form"),m,p,h):"keyword b"==a?b(k("form"),p,h):"{"==a?b(k("}"),N,h):";"==a?b():"if"==a?("else"==f.state.lexical.info&&f.state.cc[f.state.cc.length-1]==
h&&f.state.cc.pop()(),b(k("form"),m,p,h,W)):"function"==a?b(w):"for"==a?b(k("form"),X,p,h):"variable"==a?b(k("stat"),ka):"switch"==a?b(k("form"),m,k("}","switch"),l("{"),N,h,h):"case"==a?b(m,l(":")):"default"==a?b(l(":")):"catch"==a?b(k("form"),u,l("("),O,l(")"),p,h,v):"module"==a?b(k("form"),u,la,v,h):"class"==a?b(k("form"),ma,na,h):"export"==a?b(k("form"),oa,h):"import"==a?b(k("form"),pa,h):g(k("stat"),m,l(";"),h)}function m(a){return Y(a,!1)}function q(a){return Y(a,!0)}function Y(a,d){if(f.state.fatArrowAt==
f.stream.start){var e=d?Z:$;if("("==a)return b(u,k(")"),C(x,")"),h,l("\x3d\x3e"),e,v);if("variable"==a)return g(u,x,l("\x3d\x3e"),e,v)}e=d?P:F;return aa.hasOwnProperty(a)?b(e):"function"==a?b(w,e):"keyword c"==a?b(d?qa:Q):"("==a?b(k(")"),Q,G,l(")"),h,e):"operator"==a||"spread"==a?b(d?q:m):"["==a?b(k("]"),ra,h,e):"{"==a?y(ba,"}",null,e):"quasi"==a?g(H,e):b()}function Q(a){return a.match(/[;\}\)\],]/)?g():g(m)}function qa(a){return a.match(/[;\}\)\],]/)?g():g(q)}function F(a,d){return","==a?b(m):P(a,
d,!1)}function P(a,d,e){var c=!1==e?F:P,f=!1==e?m:q;if("\x3d\x3e"==d)return b(u,e?Z:$,v);if("operator"==a)return/\+\+|--/.test(d)?b(c):"?"==d?b(m,l(":"),f):b(f);if("quasi"==a)return g(H,c);if(";"!=a){if("("==a)return y(q,")","call",c);if("."==a)return b(sa,c);if("["==a)return b(k("]"),Q,l("]"),h,c)}}function H(a,d){return"quasi"!=a?g():"${"!=d.slice(d.length-2)?b(H):b(m,ta)}function ta(a){if("}"==a)return f.marked="string-2",f.state.tokenize=K,b(H)}function $(a){L(f.stream,f.state);return"{"==a?g(p):
g(m)}function Z(a){L(f.stream,f.state);return"{"==a?g(p):g(q)}function ka(a){return":"==a?b(h,p):g(F,l(";"),h)}function sa(a){if("variable"==a)return f.marked="property",b()}function ba(a,d){if("variable"==a){if(f.marked="property","get"==d||"set"==d)return b(ua)}else if("number"==a||"string"==a)f.marked=a+" property";else if("["==a)return b(m,l("]"),R);if(aa.hasOwnProperty(a))return b(R)}function ua(a){if("variable"!=a)return g(R);f.marked="property";return b(w)}function R(a){if(":"==a)return b(q);
if("("==a)return g(w)}function C(a,d){function e(c){return","==c?(c=f.state.lexical,"call"==c.info&&(c.pos=(c.pos||0)+1),b(a,e)):c==d?b():b(l(d))}return function(c){return c==d?b():g(a,e)}}function y(a,d,e){for(var c=3;c<arguments.length;c++)f.cc.push(arguments[c]);return b(k(d,e),C(a,d),h)}function N(a){return"}"==a?b():g(p,N)}function ca(a){}function M(){return g(x,ca,S,va)}function x(a,d){if("variable"==a)return t(d),b();if("["==a)return y(x,"]");if("{"==a)return y(wa,"}")}function wa(a,d){if("variable"==
a&&!f.stream.match(/^\s*:/,!1))return t(d),b(S);"variable"==a&&(f.marked="property");return b(l(":"),x,S)}function S(a,d){if("\x3d"==d)return b(q)}function va(a){if(","==a)return b(M)}function W(a,d){if("keyword b"==a&&"else"==d)return b(k("form","else"),p,h)}function X(a){if("("==a)return b(k(")"),xa,l(")"),h)}function xa(a){return"var"==a?b(M,l(";"),I):";"==a?b(I):"variable"==a?b(ya):g(m,l(";"),I)}function ya(a,d){return"in"==d||"of"==d?(f.marked="keyword",b(m)):b(F,I)}function I(a,d){return";"==
a?b(da):"in"==d||"of"==d?(f.marked="keyword",b(m)):g(m,l(";"),da)}function da(a){")"!=a&&b(m)}function w(a,d){if("*"==d)return f.marked="keyword",b(w);if("variable"==a)return t(d),b(w);if("("==a)return b(u,k(")"),C(O,")"),h,p,v)}function O(a){return"spread"==a?b(O):g(x,ca)}function ma(a,d){if("variable"==a)return t(d),b(za)}function za(a,d){if("extends"==d)return b(m)}function na(a){if("{"==a)return y(ba,"}")}function la(a,d){if("string"==a)return b(p);if("variable"==a)return t(d),b(T)}function oa(a,
d){return"*"==d?(f.marked="keyword",b(T,l(";"))):"default"==d?(f.marked="keyword",b(m,l(";"))):g(p)}function pa(a){return"string"==a?b():g(ea,T)}function ea(a,d){if("{"==a)return y(ea,"}");"variable"==a&&t(d);return b()}function T(a,d){if("from"==d)return f.marked="keyword",b(m)}function ra(a){return"]"==a?b():g(q,Aa)}function Aa(a){return"for"==a?g(G,l("]")):","==a?b(C(q,"]")):g(C(q,"]"))}function G(a){if("for"==a)return b(X,G);if("if"==a)return b(m,G)}var z=ga.indentUnit,fa=r.statementIndent,U=
function(){function a(a){return{type:a,style:"keyword"}}var d=a("keyword a"),b=a("keyword b"),c=a("keyword c"),f=a("operator"),g={type:"atom",style:"atom"};return{"if":a("if"),"while":d,"with":d,"else":b,"do":b,"try":b,"finally":b,"return":c,"break":c,"continue":c,"new":c,"delete":c,"throw":c,"debugger":c,"const":a("var"),let:a("var"),"function":a("function"),"catch":a("catch"),"for":a("for"),"switch":a("switch"),"case":a("case"),"default":a("default"),"in":f,"typeof":f,"instanceof":f,"true":g,"false":g,
"null":g,undefined:g,NaN:g,Infinity:g,"this":a("this"),module:a("module"),"class":a("class"),"super":a("atom"),yield:c,"export":a("export"),"import":a("import"),"extends":c,require:f}}(),J=/[+\-*\u2721&%=<>!?|~^]/,A,D,ia="([{}])",aa={atom:!0,number:!0,variable:!0,string:!0,regexp:!0,"this":!0,"jsonld-keyword":!0},f={state:null,column:null,marked:null,cc:null},ja={name:"this",next:{name:"arguments"}};h.lex=!0;return{startState:function(a){a={tokenize:B,lastType:"sof",cc:[],lexical:new V((a||0)-z,0,
"block",!1),localVars:r.localVars,context:r.localVars&&{vars:r.localVars},indented:0};r.globalVars&&"object"==typeof r.globalVars&&(a.globalVars=r.globalVars);return a},token:function(a,b){a.sol()&&(b.lexical.hasOwnProperty("align")||(b.lexical.align=!1),b.indented=a.indentation(),L(a,b));if(b.tokenize!=E&&a.eatSpace())return null;var e=b.tokenize(a,b);if("comment"==A)return e;b.lastType="operator"==A&&("++"==D||"--"==D)?"incdec":A;a:{var c=A,g=D,h=b.cc;f.state=b;f.stream=a;f.marked=null;f.cc=h;b.lexical.hasOwnProperty("align")||
(b.lexical.align=!0);for(;;)if((h.length?h.pop():p)(c,g)){for(;h.length&&h[h.length-1].lex;)h.pop()();if(f.marked){e=f.marked;break a}if(c="variable"==c)b:{for(c=b.localVars;c;c=c.next)if(c.name==g){c=!0;break b}for(h=b.context;h;h=h.prev)for(c=h.vars;c;c=c.next)if(c.name==g){c=!0;break b}c=void 0}if(c){e="variable-2";break a}break a}e=void 0}return e},indent:function(a,b){if(a.tokenize==E)return s.Pass;if(a.tokenize!=B)return 0;var e=b&&b.charAt(0),c=a.lexical;if(!/^\s*else\b/.test(b))for(var f=
a.cc.length-1;0<=f;--f){var g=a.cc[f];if(g==h)c=c.prev;else if(g!=W)break}"stat"==c.type&&"}"==e&&(c=c.prev);fa&&(")"==c.type&&"stat"==c.prev.type)&&(c=c.prev);f=c.type;g=e==f;return"vardef"==f?c.indented+("operator"==a.lastType||","==a.lastType?c.info+1:0):"form"==f&&"{"==e?c.indented:"form"==f?c.indented+z:"stat"==f?c.indented+("operator"==a.lastType||","==a.lastType?fa||z:0):"switch"==c.info&&!g&&!1!=r.doubleIndentSwitch?c.indented+(/^(?:case|default)\b/.test(b)?z:2*z):c.align?c.column+(g?0:1):
c.indented+(g?0:z)},electricChars:":{}",blockCommentStart:"/*",blockCommentEnd:"*/",lineComment:"//",fold:"brace",helperType:"promiseland"}});s.defineMIME("text/promiseland","promiseland");s.defineMIME("application/promiseland","promiseland")});
//# sourceMappingURL=promiseland.js.map