//>>built
(function(n){"object"==typeof exports&&"object"==typeof module?n(require("../lib/codemirror"),require("../addon/search/searchcursor"),require("../addon/edit/matchbrackets")):"function"==typeof define&&define.amd?define("codemirror4/keymap/sublime",["../lib/codemirror","../addon/search/searchcursor","../addon/edit/matchbrackets"],n):n(CodeMirror)})(function(n){function s(a,b){a.extendSelectionsBy(function(c){if(a.display.shift||a.doc.extend||c.empty()){var d;var e=a.doc;c=c.head;if(0>b&&0==c.ch)d=
e.clipPos(m(c.line-1));else{var h=e.getLine(c.line);if(0<b&&c.ch>=h.length)d=e.clipPos(m(c.line+1,0));else{for(var e="start",f=c.ch,k=0>b?0:h.length,g=0;f!=k;f+=b,g++){var l=h.charAt(0>b?f-1:f),q="_"!=l&&n.isWordChar(l)?"w":"o";"w"==q&&l.toUpperCase()==l&&(q="W");if("start"==e)"o"!=q&&(e="in",d=q);else if("in"==e&&d!=q)if("w"==d&&("W"==q&&0>b)&&f--,"W"==d&&"w"==q&&0<b)d="w";else break}d=m(c.line,f)}}return d}return 0>b?c.from():c.to()})}function t(a,b){a.operation(function(){for(var c=a.listSelections().length,
d=[],e=-1,h=0;h<c;h++){var f=a.listSelections()[h].head;f.line<=e||(e=m(f.line+(b?0:1),0),a.replaceRange("\n",e,null,"+insertLine"),a.indentLine(e.line,null,!0),d.push({head:e,anchor:e}),e=f.line+1)}a.setSelections(d)})}function r(a,b){for(var c=b.ch,d=c,e=a.getLine(b.line);c&&n.isWordChar(e.charAt(c-1));)--c;for(;d<e.length&&n.isWordChar(e.charAt(d));)++d;return{from:m(b.line,c),to:m(b.line,d),word:e.slice(c,d)}}function u(a){var b=a.getCursor(),c=a.scanForBracket(b,-1);if(c)for(;;){b=a.scanForBracket(b,
1);if(!b)break;if(b.ch==v.charAt(v.indexOf(c.ch)+1))return a.setSelection(m(c.pos.line,c.pos.ch+1),b.pos,!1),!0;b=m(b.pos.line,b.pos.ch+1)}}function w(a,b){for(var c=a.listSelections(),d=[],e,h=0;h<c.length;h++){var f=c[h];if(!f.empty()){for(var k=f.from().line,g=f.to().line;h<c.length-1&&c[h+1].from().line==g;)g=f[++h].to().line;d.push(k,g)}}d.length?e=!0:d.push(a.firstLine(),a.lastLine());a.operation(function(){for(var c=[],f=0;f<d.length;f+=2){var h=d[f+1],g=m(d[f],0),h=m(h),k=a.getRange(g,h,!1);
b?k.sort():k.sort(function(a,b){var c=a.toUpperCase(),d=b.toUpperCase();c!=d&&(a=c,b=d);return a<b?-1:a==b?0:1});a.replaceRange(k,g,h);e&&c.push({anchor:g,head:h})}e&&a.setSelections(c,0)})}function x(a,b){a.operation(function(){for(var c=a.listSelections(),d=[],e=[],h=0;h<c.length;h++){var f=c[h];f.empty()?(d.push(h),e.push("")):e.push(b(a.getRange(f.from(),f.to())))}a.replaceSelections(e,"around","case");for(var h=d.length-1,g;0<=h;h--)f=c[d[h]],g&&0<n.cmpPos(f.head,g)||(e=r(a,f.head),g=e.from,
a.replaceRange(b(e.word),e.from,e.to))})}function y(a,b){var c=a.getCursor("from"),d=a.getCursor("to");if(0==n.cmpPos(c,d)){var e=r(a,c);if(!e.word)return;c=e.from;d=e.to}var h=a.getRange(c,d),f=a.getSearchCursor(h,b?d:c);(b?f.findNext():f.findPrevious())?a.setSelection(f.from(),f.to()):(f=a.getSearchCursor(h,b?m(a.firstLine(),0):a.clipPos(m(a.lastLine()))),(b?f.findNext():f.findPrevious())?a.setSelection(f.from(),f.to()):e&&a.setSelection(c,d))}var k=n.keyMap.sublime={fallthrough:"default"},l=n.commands,
m=n.Pos,g=n.keyMap["default"]==n.keyMap.pcDefault?"Ctrl-":"Cmd-";l[k["Alt-Left"]="goSubwordLeft"]=function(a){s(a,-1)};l[k["Alt-Right"]="goSubwordRight"]=function(a){s(a,1)};l[k[g+"Up"]="scrollLineUp"]=function(a){var b=a.getScrollInfo();if(!a.somethingSelected()){var c=a.lineAtHeight(b.top+b.clientHeight,"local");a.getCursor().line>=c&&a.execCommand("goLineUp")}a.scrollTo(null,b.top-a.defaultTextHeight())};l[k[g+"Down"]="scrollLineDown"]=function(a){var b=a.getScrollInfo();if(!a.somethingSelected()){var c=
a.lineAtHeight(b.top,"local")+1;a.getCursor().line<=c&&a.execCommand("goLineDown")}a.scrollTo(null,b.top+a.defaultTextHeight())};l[k["Shift-"+g+"L"]="splitSelectionByLine"]=function(a){for(var b=a.listSelections(),c=[],d=0;d<b.length;d++)for(var e=b[d].from(),h=b[d].to(),f=e.line;f<=h.line;++f)h.line>e.line&&f==h.line&&0==h.ch||c.push({anchor:f==e.line?e:m(f,0),head:f==h.line?h:m(f)});a.setSelections(c,0)};k["Shift-Tab"]="indentLess";l[k.Esc="singleSelectionTop"]=function(a){var b=a.listSelections()[0];
a.setSelection(b.anchor,b.head,{scroll:!1})};l[k[g+"L"]="selectLine"]=function(a){for(var b=a.listSelections(),c=[],d=0;d<b.length;d++){var e=b[d];c.push({anchor:m(e.from().line,0),head:m(e.to().line+1,0)})}a.setSelections(c)};k["Shift-"+g+"K"]="deleteLine";l[k[g+"Enter"]="insertLineAfter"]=function(a){t(a,!1)};l[k["Shift-"+g+"Enter"]="insertLineBefore"]=function(a){t(a,!0)};l[k[g+"D"]="selectNextOccurrence"]=function(a){var b=a.getCursor("from"),c=a.getCursor("to"),d=a.state.sublimeFindFullWord==
a.doc.sel;if(0==n.cmpPos(b,c)){d=r(a,b);if(!d.word)return;a.setSelection(d.from,d.to);d=!0}else b=a.getRange(b,c),b=d?RegExp("\\b"+b+"\\b"):b,c=a.getSearchCursor(b,c),c.findNext()?a.addSelection(c.from(),c.to()):(c=a.getSearchCursor(b,m(a.firstLine(),0)),c.findNext()&&a.addSelection(c.from(),c.to()));d&&(a.state.sublimeFindFullWord=a.doc.sel)};var v="(){}[]";l[k["Shift-"+g+"Space"]="selectScope"]=function(a){u(a)||a.execCommand("selectAll")};l[k["Shift-"+g+"M"]="selectBetweenBrackets"]=function(a){if(!u(a))return n.Pass};
l[k[g+"M"]="goToBracket"]=function(a){a.extendSelectionsBy(function(b){var c=a.scanForBracket(b.head,1);return c&&0!=n.cmpPos(c.pos,b.head)?c.pos:(c=a.scanForBracket(b.head,-1))&&m(c.pos.line,c.pos.ch+1)||b.head})};l[k["Shift-"+g+"Up"]="swapLineUp"]=function(a){for(var b=a.listSelections(),c=[],d=a.firstLine()-1,e=0;e<b.length;e++){var h=b[e],f=h.from().line-1,h=h.to().line;f>d?c.push(f,h):c.length&&(c[c.length-1]=h);d=h}a.operation(function(){for(var b=0;b<c.length;b+=2){var d=c[b],e=c[b+1],f=a.getLine(d);
a.replaceRange("",m(d,0),m(d+1,0),"+swapLine");if(e>a.lastLine()){a.replaceRange("\n"+f,m(a.lastLine()),null,"+swapLine");var d=a.listSelections(),h=d[d.length-1],f=h.head.line==e?m(e-1):h.head,e=h.anchor.line==e?m(e-1):h.anchor;a.setSelections(d.slice(0,d.length-1).concat([{head:f,anchor:e}]))}else a.replaceRange(f+"\n",m(e,0),null,"+swapLine")}a.scrollIntoView()})};l[k["Shift-"+g+"Down"]="swapLineDown"]=function(a){for(var b=a.listSelections(),c=[],d=a.lastLine()+1,e=b.length-1;0<=e;e--){var h=
b[e],f=h.to().line+1,h=h.from().line;f<d?c.push(f,h):c.length&&(c[c.length-1]=h);d=h}a.operation(function(){for(var b=c.length-2;0<=b;b-=2){var d=c[b],e=c[b+1],f=a.getLine(d);d==a.lastLine()?a.replaceRange("",m(d-1),m(d),"+swapLine"):a.replaceRange("",m(d,0),m(d+1,0),"+swapLine");a.replaceRange(f+"\n",m(e,0),null,"+swapLine")}a.scrollIntoView()})};k[g+"/"]="toggleComment";l[k[g+"J"]="joinLines"]=function(a){for(var b=a.listSelections(),c=[],d=0;d<b.length;d++){for(var e=b[d],h=e.from(),f=h.line,g=
e.to().line;d<b.length-1&&b[d+1].from().line==g;)g=b[++d].to().line;c.push({start:f,end:g,anchor:!e.empty()&&h})}a.operation(function(){for(var b=0,d=[],e=0;e<c.length;e++){for(var f=c[e],h=f.anchor&&m(f.anchor.line-b,f.anchor.ch),g,k=f.start;k<=f.end;k++){var l=k-b;k==f.end&&(g=m(l,a.getLine(l).length+1));l<a.lastLine()&&(a.replaceRange(" ",m(l),m(l+1,/^\s*/.exec(a.getLine(l+1))[0].length)),++b)}d.push({anchor:h||g,head:g})}a.setSelections(d,0)})};l[k["Shift-"+g+"D"]="duplicateLine"]=function(a){a.operation(function(){for(var b=
a.listSelections().length,c=0;c<b;c++){var d=a.listSelections()[c];d.empty()?a.replaceRange(a.getLine(d.head.line)+"\n",m(d.head.line,0)):a.replaceRange(a.getRange(d.from(),d.to()),d.from())}a.scrollIntoView()})};k[g+"T"]="transposeChars";l[k.F9="sortLines"]=function(a){w(a,!0)};l[k[g+"F9"]="sortLinesInsensitive"]=function(a){w(a,!1)};l[k.F2="nextBookmark"]=function(a){var b=a.state.sublimeBookmarks;if(b)for(;b.length;){var c=b.shift(),d=c.find();if(d)return b.push(c),a.setSelection(d.from,d.to)}};
l[k["Shift-F2"]="prevBookmark"]=function(a){var b=a.state.sublimeBookmarks;if(b)for(;b.length;){b.unshift(b.pop());var c=b[b.length-1].find();if(c)return a.setSelection(c.from,c.to);b.pop()}};l[k[g+"F2"]="toggleBookmark"]=function(a){for(var b=a.listSelections(),c=a.state.sublimeBookmarks||(a.state.sublimeBookmarks=[]),d=0;d<b.length;d++){for(var e=b[d].from(),h=b[d].to(),f=a.findMarks(e,h),g=0;g<f.length;g++)if(f[g].sublimeBookmark){f[g].clear();for(var k=0;k<c.length;k++)c[k]==f[g]&&c.splice(k--,
1);break}g==f.length&&c.push(a.markText(e,h,{sublimeBookmark:!0,clearWhenEmpty:!1}))}};l[k["Shift-"+g+"F2"]="clearBookmarks"]=function(a){if(a=a.state.sublimeBookmarks)for(var b=0;b<a.length;b++)a[b].clear();a.length=0};l[k["Alt-F2"]="selectBookmarks"]=function(a){var b=a.state.sublimeBookmarks,c=[];if(b)for(var d=0;d<b.length;d++){var e=b[d].find();e?c.push({anchor:e.from,head:e.to}):b.splice(d--,0)}c.length&&a.setSelections(c,0)};k["Alt-Q"]="wrapLines";var p=n.keyMap["sublime-Ctrl-K"]={auto:"sublime",
nofallthrough:!0};k[g+"K"]=function(a){a.setOption("keyMap","sublime-Ctrl-K")};p[g+"Backspace"]="delLineLeft";l[p[g+"K"]="delLineRight"]=function(a){a.operation(function(){for(var b=a.listSelections(),c=b.length-1;0<=c;c--)a.replaceRange("",b[c].anchor,m(b[c].to().line),"+delete");a.scrollIntoView()})};l[p[g+"U"]="upcaseAtCursor"]=function(a){x(a,function(a){return a.toUpperCase()})};l[p[g+"L"]="downcaseAtCursor"]=function(a){x(a,function(a){return a.toLowerCase()})};l[p[g+"Space"]="setSublimeMark"]=
function(a){a.state.sublimeMark&&a.state.sublimeMark.clear();a.state.sublimeMark=a.setBookmark(a.getCursor())};l[p[g+"A"]="selectToSublimeMark"]=function(a){var b=a.state.sublimeMark&&a.state.sublimeMark.find();b&&a.setSelection(a.getCursor(),b)};l[p[g+"W"]="deleteToSublimeMark"]=function(a){var b=a.state.sublimeMark&&a.state.sublimeMark.find();if(b){var c=a.getCursor();if(0<n.cmpPos(c,b))var d=b,b=c,c=d;a.state.sublimeKilled=a.getRange(c,b);a.replaceRange("",c,b)}};l[p[g+"X"]="swapWithSublimeMark"]=
function(a){var b=a.state.sublimeMark&&a.state.sublimeMark.find();b&&(a.state.sublimeMark.clear(),a.state.sublimeMark=a.setBookmark(a.getCursor()),a.setCursor(b))};l[p[g+"Y"]="sublimeYank"]=function(a){null!=a.state.sublimeKilled&&a.replaceSelection(a.state.sublimeKilled,null,"paste")};p[g+"G"]="clearBookmarks";l[p[g+"C"]="showInCenter"]=function(a){var b=a.cursorCoords(null,"local");a.scrollTo(null,(b.top+b.bottom)/2-a.getScrollInfo().clientHeight/2)};l[k["Shift-Alt-Up"]="selectLinesUpward"]=function(a){a.operation(function(){for(var b=
a.listSelections(),c=0;c<b.length;c++){var d=b[c];d.head.line>a.firstLine()&&a.addSelection(m(d.head.line-1,d.head.ch))}})};l[k["Shift-Alt-Down"]="selectLinesDownward"]=function(a){a.operation(function(){for(var b=a.listSelections(),c=0;c<b.length;c++){var d=b[c];d.head.line<a.lastLine()&&a.addSelection(m(d.head.line+1,d.head.ch))}})};l[k[g+"F3"]="findUnder"]=function(a){y(a,!0)};l[k["Shift-"+g+"F3"]="findUnderPrevious"]=function(a){y(a,!1)};k["Shift-"+g+"["]="fold";k["Shift-"+g+"]"]="unfold";p[g+
"0"]=p[g+"j"]="unfoldAll";k[g+"I"]="findIncremental";k["Shift-"+g+"I"]="findIncrementalReverse";k[g+"H"]="replace";k.F3="findNext";k["Shift-F3"]="findPrev"});
//# sourceMappingURL=sublime.js.map