//>>built
(function(m){"object"==typeof exports&&"object"==typeof module?m(require("../lib/codemirror"),require("../addon/search/searchcursor"),require("../addon/dialog/dialog"),require("../addon/edit/matchbrackets.js")):"function"==typeof define&&define.amd?define("codemirror4/keymap/vim",["../lib/codemirror","../addon/search/searchcursor","../addon/dialog/dialog","../addon/edit/matchbrackets"],m):m(CodeMirror)})(function(m){var F=[{keys:["\x3cLeft\x3e"],type:"keyToKey",toKeys:["h"]},{keys:["\x3cRight\x3e"],
type:"keyToKey",toKeys:["l"]},{keys:["\x3cUp\x3e"],type:"keyToKey",toKeys:["k"]},{keys:["\x3cDown\x3e"],type:"keyToKey",toKeys:["j"]},{keys:["\x3cSpace\x3e"],type:"keyToKey",toKeys:["l"]},{keys:["\x3cBS\x3e"],type:"keyToKey",toKeys:["h"]},{keys:["\x3cC-Space\x3e"],type:"keyToKey",toKeys:["W"]},{keys:["\x3cC-BS\x3e"],type:"keyToKey",toKeys:["B"]},{keys:["\x3cS-Space\x3e"],type:"keyToKey",toKeys:["w"]},{keys:["\x3cS-BS\x3e"],type:"keyToKey",toKeys:["b"]},{keys:["\x3cC-n\x3e"],type:"keyToKey",toKeys:["j"]},
{keys:["\x3cC-p\x3e"],type:"keyToKey",toKeys:["k"]},{keys:["\x3cC-[\x3e"],type:"keyToKey",toKeys:["\x3cEsc\x3e"]},{keys:["\x3cC-c\x3e"],type:"keyToKey",toKeys:["\x3cEsc\x3e"]},{keys:["s"],type:"keyToKey",toKeys:["c","l"],context:"normal"},{keys:["s"],type:"keyToKey",toKeys:["x","i"],context:"visual"},{keys:["S"],type:"keyToKey",toKeys:["c","c"],context:"normal"},{keys:["S"],type:"keyToKey",toKeys:["d","c","c"],context:"visual"},{keys:["\x3cHome\x3e"],type:"keyToKey",toKeys:["0"]},{keys:["\x3cEnd\x3e"],
type:"keyToKey",toKeys:["$"]},{keys:["\x3cPageUp\x3e"],type:"keyToKey",toKeys:["\x3cC-b\x3e"]},{keys:["\x3cPageDown\x3e"],type:"keyToKey",toKeys:["\x3cC-f\x3e"]},{keys:["\x3cCR\x3e"],type:"keyToKey",toKeys:["j","^"],context:"normal"},{keys:["H"],type:"motion",motion:"moveToTopLine",motionArgs:{linewise:!0,toJumplist:!0}},{keys:["M"],type:"motion",motion:"moveToMiddleLine",motionArgs:{linewise:!0,toJumplist:!0}},{keys:["L"],type:"motion",motion:"moveToBottomLine",motionArgs:{linewise:!0,toJumplist:!0}},
{keys:["h"],type:"motion",motion:"moveByCharacters",motionArgs:{forward:!1}},{keys:["l"],type:"motion",motion:"moveByCharacters",motionArgs:{forward:!0}},{keys:["j"],type:"motion",motion:"moveByLines",motionArgs:{forward:!0,linewise:!0}},{keys:["k"],type:"motion",motion:"moveByLines",motionArgs:{forward:!1,linewise:!0}},{keys:["g","j"],type:"motion",motion:"moveByDisplayLines",motionArgs:{forward:!0}},{keys:["g","k"],type:"motion",motion:"moveByDisplayLines",motionArgs:{forward:!1}},{keys:["w"],type:"motion",
motion:"moveByWords",motionArgs:{forward:!0,wordEnd:!1}},{keys:["W"],type:"motion",motion:"moveByWords",motionArgs:{forward:!0,wordEnd:!1,bigWord:!0}},{keys:["e"],type:"motion",motion:"moveByWords",motionArgs:{forward:!0,wordEnd:!0,inclusive:!0}},{keys:["E"],type:"motion",motion:"moveByWords",motionArgs:{forward:!0,wordEnd:!0,bigWord:!0,inclusive:!0}},{keys:["b"],type:"motion",motion:"moveByWords",motionArgs:{forward:!1,wordEnd:!1}},{keys:["B"],type:"motion",motion:"moveByWords",motionArgs:{forward:!1,
wordEnd:!1,bigWord:!0}},{keys:["g","e"],type:"motion",motion:"moveByWords",motionArgs:{forward:!1,wordEnd:!0,inclusive:!0}},{keys:["g","E"],type:"motion",motion:"moveByWords",motionArgs:{forward:!1,wordEnd:!0,bigWord:!0,inclusive:!0}},{keys:["{"],type:"motion",motion:"moveByParagraph",motionArgs:{forward:!1,toJumplist:!0}},{keys:["}"],type:"motion",motion:"moveByParagraph",motionArgs:{forward:!0,toJumplist:!0}},{keys:["\x3cC-f\x3e"],type:"motion",motion:"moveByPage",motionArgs:{forward:!0}},{keys:["\x3cC-b\x3e"],
type:"motion",motion:"moveByPage",motionArgs:{forward:!1}},{keys:["\x3cC-d\x3e"],type:"motion",motion:"moveByScroll",motionArgs:{forward:!0,explicitRepeat:!0}},{keys:["\x3cC-u\x3e"],type:"motion",motion:"moveByScroll",motionArgs:{forward:!1,explicitRepeat:!0}},{keys:["g","g"],type:"motion",motion:"moveToLineOrEdgeOfDocument",motionArgs:{forward:!1,explicitRepeat:!0,linewise:!0,toJumplist:!0}},{keys:["G"],type:"motion",motion:"moveToLineOrEdgeOfDocument",motionArgs:{forward:!0,explicitRepeat:!0,linewise:!0,
toJumplist:!0}},{keys:["0"],type:"motion",motion:"moveToStartOfLine"},{keys:["^"],type:"motion",motion:"moveToFirstNonWhiteSpaceCharacter"},{keys:["+"],type:"motion",motion:"moveByLines",motionArgs:{forward:!0,toFirstChar:!0}},{keys:["-"],type:"motion",motion:"moveByLines",motionArgs:{forward:!1,toFirstChar:!0}},{keys:["_"],type:"motion",motion:"moveByLines",motionArgs:{forward:!0,toFirstChar:!0,repeatOffset:-1}},{keys:["$"],type:"motion",motion:"moveToEol",motionArgs:{inclusive:!0}},{keys:["%"],
type:"motion",motion:"moveToMatchedSymbol",motionArgs:{inclusive:!0,toJumplist:!0}},{keys:["f","character"],type:"motion",motion:"moveToCharacter",motionArgs:{forward:!0,inclusive:!0}},{keys:["F","character"],type:"motion",motion:"moveToCharacter",motionArgs:{forward:!1}},{keys:["t","character"],type:"motion",motion:"moveTillCharacter",motionArgs:{forward:!0,inclusive:!0}},{keys:["T","character"],type:"motion",motion:"moveTillCharacter",motionArgs:{forward:!1}},{keys:[";"],type:"motion",motion:"repeatLastCharacterSearch",
motionArgs:{forward:!0}},{keys:[","],type:"motion",motion:"repeatLastCharacterSearch",motionArgs:{forward:!1}},{keys:["'","character"],type:"motion",motion:"goToMark",motionArgs:{toJumplist:!0,linewise:!0}},{keys:["`","character"],type:"motion",motion:"goToMark",motionArgs:{toJumplist:!0}},{keys:["]","`"],type:"motion",motion:"jumpToMark",motionArgs:{forward:!0}},{keys:["[","`"],type:"motion",motion:"jumpToMark",motionArgs:{forward:!1}},{keys:["]","'"],type:"motion",motion:"jumpToMark",motionArgs:{forward:!0,
linewise:!0}},{keys:["[","'"],type:"motion",motion:"jumpToMark",motionArgs:{forward:!1,linewise:!0}},{keys:["]","p"],type:"action",action:"paste",isEdit:!0,actionArgs:{after:!0,isEdit:!0,matchIndent:!0}},{keys:["[","p"],type:"action",action:"paste",isEdit:!0,actionArgs:{after:!1,isEdit:!0,matchIndent:!0}},{keys:["]","character"],type:"motion",motion:"moveToSymbol",motionArgs:{forward:!0,toJumplist:!0}},{keys:["[","character"],type:"motion",motion:"moveToSymbol",motionArgs:{forward:!1,toJumplist:!0}},
{keys:["|"],type:"motion",motion:"moveToColumn",motionArgs:{}},{keys:["o"],type:"motion",motion:"moveToOtherHighlightedEnd",motionArgs:{},context:"visual"},{keys:["d"],type:"operator",operator:"delete"},{keys:["y"],type:"operator",operator:"yank"},{keys:["c"],type:"operator",operator:"change"},{keys:["\x3e"],type:"operator",operator:"indent",operatorArgs:{indentRight:!0}},{keys:["\x3c"],type:"operator",operator:"indent",operatorArgs:{indentRight:!1}},{keys:["g","~"],type:"operator",operator:"swapcase"},
{keys:["n"],type:"motion",motion:"findNext",motionArgs:{forward:!0,toJumplist:!0}},{keys:["N"],type:"motion",motion:"findNext",motionArgs:{forward:!1,toJumplist:!0}},{keys:["x"],type:"operatorMotion",operator:"delete",motion:"moveByCharacters",motionArgs:{forward:!0},operatorMotionArgs:{visualLine:!1}},{keys:["X"],type:"operatorMotion",operator:"delete",motion:"moveByCharacters",motionArgs:{forward:!1},operatorMotionArgs:{visualLine:!0}},{keys:["D"],type:"operatorMotion",operator:"delete",motion:"moveToEol",
motionArgs:{inclusive:!0},operatorMotionArgs:{visualLine:!0}},{keys:["Y"],type:"operatorMotion",operator:"yank",motion:"moveToEol",motionArgs:{inclusive:!0},operatorMotionArgs:{visualLine:!0}},{keys:["C"],type:"operatorMotion",operator:"change",motion:"moveToEol",motionArgs:{inclusive:!0},operatorMotionArgs:{visualLine:!0}},{keys:["~"],type:"operatorMotion",operator:"swapcase",operatorArgs:{shouldMoveCursor:!0},motion:"moveByCharacters",motionArgs:{forward:!0}},{keys:["\x3cC-i\x3e"],type:"action",
action:"jumpListWalk",actionArgs:{forward:!0}},{keys:["\x3cC-o\x3e"],type:"action",action:"jumpListWalk",actionArgs:{forward:!1}},{keys:["\x3cC-e\x3e"],type:"action",action:"scroll",actionArgs:{forward:!0,linewise:!0}},{keys:["\x3cC-y\x3e"],type:"action",action:"scroll",actionArgs:{forward:!1,linewise:!0}},{keys:["a"],type:"action",action:"enterInsertMode",isEdit:!0,actionArgs:{insertAt:"charAfter"}},{keys:["A"],type:"action",action:"enterInsertMode",isEdit:!0,actionArgs:{insertAt:"eol"}},{keys:["i"],
type:"action",action:"enterInsertMode",isEdit:!0,actionArgs:{insertAt:"inplace"}},{keys:["I"],type:"action",action:"enterInsertMode",isEdit:!0,actionArgs:{insertAt:"firstNonBlank"}},{keys:["o"],type:"action",action:"newLineAndEnterInsertMode",isEdit:!0,interlaceInsertRepeat:!0,actionArgs:{after:!0}},{keys:["O"],type:"action",action:"newLineAndEnterInsertMode",isEdit:!0,interlaceInsertRepeat:!0,actionArgs:{after:!1}},{keys:["v"],type:"action",action:"toggleVisualMode"},{keys:["V"],type:"action",action:"toggleVisualMode",
actionArgs:{linewise:!0}},{keys:["g","v"],type:"action",action:"reselectLastSelection"},{keys:["J"],type:"action",action:"joinLines",isEdit:!0},{keys:["p"],type:"action",action:"paste",isEdit:!0,actionArgs:{after:!0,isEdit:!0}},{keys:["P"],type:"action",action:"paste",isEdit:!0,actionArgs:{after:!1,isEdit:!0}},{keys:["r","character"],type:"action",action:"replace",isEdit:!0},{keys:["@","character"],type:"action",action:"replayMacro"},{keys:["q","character"],type:"action",action:"enterMacroRecordMode"},
{keys:["R"],type:"action",action:"enterInsertMode",isEdit:!0,actionArgs:{replace:!0}},{keys:["u"],type:"action",action:"undo"},{keys:["u"],type:"action",action:"changeCase",actionArgs:{toLower:!0},context:"visual",isEdit:!0},{keys:["U"],type:"action",action:"changeCase",actionArgs:{toLower:!1},context:"visual",isEdit:!0},{keys:["\x3cC-r\x3e"],type:"action",action:"redo"},{keys:["m","character"],type:"action",action:"setMark"},{keys:['"',"character"],type:"action",action:"setRegister"},{keys:["z",
"z"],type:"action",action:"scrollToCursor",actionArgs:{position:"center"}},{keys:["z","."],type:"action",action:"scrollToCursor",actionArgs:{position:"center"},motion:"moveToFirstNonWhiteSpaceCharacter"},{keys:["z","t"],type:"action",action:"scrollToCursor",actionArgs:{position:"top"}},{keys:["z","\x3cCR\x3e"],type:"action",action:"scrollToCursor",actionArgs:{position:"top"},motion:"moveToFirstNonWhiteSpaceCharacter"},{keys:["z","-"],type:"action",action:"scrollToCursor",actionArgs:{position:"bottom"}},
{keys:["z","b"],type:"action",action:"scrollToCursor",actionArgs:{position:"bottom"},motion:"moveToFirstNonWhiteSpaceCharacter"},{keys:["."],type:"action",action:"repeatLastEdit"},{keys:["\x3cC-a\x3e"],type:"action",action:"incrementNumberToken",isEdit:!0,actionArgs:{increase:!0,backtrack:!1}},{keys:["\x3cC-x\x3e"],type:"action",action:"incrementNumberToken",isEdit:!0,actionArgs:{increase:!1,backtrack:!1}},{keys:["a","character"],type:"motion",motion:"textObjectManipulation"},{keys:["i","character"],
type:"motion",motion:"textObjectManipulation",motionArgs:{textObjectInner:!0}},{keys:["/"],type:"search",searchArgs:{forward:!0,querySrc:"prompt",toJumplist:!0}},{keys:["?"],type:"search",searchArgs:{forward:!1,querySrc:"prompt",toJumplist:!0}},{keys:["*"],type:"search",searchArgs:{forward:!0,querySrc:"wordUnderCursor",wholeWordOnly:!0,toJumplist:!0}},{keys:["#"],type:"search",searchArgs:{forward:!1,querySrc:"wordUnderCursor",wholeWordOnly:!0,toJumplist:!0}},{keys:["g","*"],type:"search",searchArgs:{forward:!0,
querySrc:"wordUnderCursor",toJumplist:!0}},{keys:["g","#"],type:"search",searchArgs:{forward:!1,querySrc:"wordUnderCursor",toJumplist:!0}},{keys:[":"],type:"ex"}],p=m.Pos,$=function(){function la(a,b){var c=a.state.vim;if(!c.insertMode&&!c.exMode){var c=b.ranges[0].head,d=b.ranges[0].anchor;if(c.ch&&c.ch==a.doc.getLine(c.line).length){var e=p(c.line,c.ch-1);b.update([{anchor:t(c,d)?e:d,head:e}])}}}function ma(a){var b=a.state.vim;b.onPasteFn||(b.onPasteFn=function(){b.insertMode||(a.setCursor(S(a.getCursor(),
0,1)),aa.enterInsertMode(a,{},b))});return b.onPasteFn}function ba(a,b){for(var c=[],d=a;d<a+b;d++)c.push(String.fromCharCode(d));return c}function O(a){return/^[A-Z]$/.test(a)}function ca(a,b){for(var c=0;c<b.length;c++)if(b[c]==a)return!0;return!1}function na(a,b,c){if(void 0===b)throw Error("defaultValue is required");c||(c="string");G[a]={type:c,defaultValue:b};da(a,b)}function da(a,b){var c=G[a];if(!c)throw Error("Unknown option: "+a);if("boolean"==c.type){if(b&&!0!==b)throw Error("Invalid argument: "+
a+"\x3d"+b);!1!==b&&(b=!0)}c.value="boolean"==c.type?!!b:b}function T(a){var b=G[a];if(!b)throw Error("Unknown option: "+a);return b.value}function oa(){this.latestRegister=void 0;this.isRecording=this.isPlaying=!1;this.replaySearchQueries=[];this.onRecordingDone=void 0;this.lastInsertModeChanges=pa()}function ea(a){a.state.vim||(a.state.vim={inputState:new E,lastEditInputState:void 0,lastEditActionCommand:void 0,lastHPos:-1,lastHSPos:-1,lastMotion:null,marks:{},insertMode:!1,insertModeRepeat:void 0,
visualMode:!1,visualLine:!1,lastSelection:null});return a.state.vim}function qa(){q={searchQuery:null,searchIsReversed:!1,lastSubstituteReplacePart:void 0,jumpList:La(),macroModeState:new oa,lastChararacterSearch:{increment:0,forward:!0,selectedCharacter:""},registerController:new ra({})};for(var a in G){var b=G[a];b.value=b.defaultValue}}function E(){this.prefixRepeat=[];this.motionRepeat=[];this.motionArgs=this.motion=this.operatorArgs=this.operator=null;this.keyBuffer=[];this.registerName=null}
function v(a,b){this.clear();this.keyBuffer=[a||""];this.insertModeChanges=[];this.searchQueries=[];this.linewise=!!b}function ra(a){this.registers=a;this.unnamedRegister=a['"']=new v;a["."]=new v;a[":"]=new v}function H(a,b,c){var d=Math.min(Math.max(a.firstLine(),b.line),a.lastLine());a=x(a,d)-1;b=Math.min(Math.max(0,b.ch),c?a+1:a);return p(d,b)}function U(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b}function S(a,b,c){return p(a.line+b,a.ch+c)}function Ma(a,b){for(var c=0;c<
a.length;c++)if(a[c]!=b[c]&&"character"!=b[c])return!1;return!0}function sa(a,b,c){return function(){for(var d=0;d<c;d++)b(a)}}function z(a){return p(a.line,a.ch)}function t(a,b){return a.ch==b.ch&&a.line==b.line}function s(a,b){return a.line<b.line||a.line==b.line&&a.ch<b.ch?!0:!1}function ta(a,b,c){a=s(a,b);b=s(b,c);return a&&b}function x(a,b){return a.getLine(b).length}function fa(a){return a.trim?a.trim():a.replace(/^\s+|\s+$/g,"")}function B(a){a.off("mousedown",B);var b=a.state.vim;b.lastSelection=
{curStart:b.marks["\x3c"].find(),curEnd:b.marks["\x3e"].find(),visualMode:b.visualMode,visualLine:b.visualLine};b.visualMode=!1;b.visualLine=!1;var b=a.getCursor("anchor"),c=a.getCursor("head");t(b,c)||a.setCursor(H(a,c));m.signal(a,"vim-mode-change",{mode:"normal"})}function y(a){if(!a)return 0;var b=a.search(/\S/);return-1==b?a.length:b}function V(a,b,c,d,e){c=a.getCursor();a=a.getLine(c.line);var f=c.ch,g=a.substring(f);e=e?g.search(/\w/):g.search(/\S/);if(-1==e)return null;f+=e;g=a.substring(f);
e=a.substring(0,f);var k;k=d?/^\S+/:/\w/.test(a.charAt(f))?/^\w+/:/^[^\w\s]+/;g=k.exec(g);d=f;f+=g[0].length;e=e.split("").reverse().join("");(k=k.exec(e))&&(d-=k[0].length);b&&(b=a.substring(f).match(/^\s*/)[0].length,0<b?f+=b:(b=e.substring(e.length-d).match(/^\s*/)[0].length,d-=b));return{start:p(c.line,d),end:p(c.line,f)}}function ua(a,b){q.lastChararacterSearch.increment=a;q.lastChararacterSearch.forward=b.forward;q.lastChararacterSearch.selectedCharacter=b.selectedCharacter}function ga(a,b,
c,d){for(var e=a.getCursor(),f=e.ch,g,k=0;k<b;k++){g=a.getLine(e.line);var h=d,l=void 0;g=l=c?g.indexOf(h,f+1):g.lastIndexOf(h,f-1);if(-1==g)return null;f=g}return p(a.getCursor().line,g)}function P(a,b,c,d){ca(c,Na)&&(b.marks[c]&&b.marks[c].clear(),b.marks[c]=a.setBookmark(d))}function va(){}function C(a){a=a.state.vim;return a.searchState_||(a.searchState_=new va)}function wa(a){for(var b=!1,c=[],d=0;d<a.length;d++){var e=a.charAt(d);!b&&"/"==e&&c.push(d);b=!b&&"\\"==e}return c}function u(a,b){a.openNotification?
a.openNotification('\x3cspan style\x3d"color: red"\x3e'+b+"\x3c/span\x3e",{bottom:!0,duration:5E3}):alert(b)}function W(a,b){var c=(b.prefix||"")+" "+(b.desc||""),d;d=b.prefix;var e=b.desc,f="";d&&(f+='\x3cspan style\x3d"font-family: monospace"\x3e'+d+"\x3c/span\x3e");f+='\x3cinput type\x3d"text"/\x3e \x3cspan style\x3d"color: #888"\x3e';e&&(f=f+'\x3cspan style\x3d"color: #888"\x3e'+e,f+="\x3c/span\x3e");d=f;e=b.onClose;a.openDialog?a.openDialog(d,e,{bottom:!0,value:b.value,onKeyDown:b.onKeyDown,
onKeyUp:b.onKeyUp}):e(prompt(c,""))}function X(a,b,c,d){if(b){var e=C(a),f;c=!!c;d=!!d;if(b instanceof RegExp)f=b;else{var g=wa(b),k;g.length?(k=b.substring(0,g[0]),f=-1!=b.substring(g[0]).indexOf("i")):k=b;if(k){if(!T("pcre")){b=k;g=!1;k=[];for(var h=-1;h<b.length;h++){var l=b.charAt(h)||"",r=b.charAt(h+1)||"",K=r&&-1!="|(){".indexOf(r);g?(("\\"!==l||!K)&&k.push(l),g=!1):"\\"===l?(g=!0,r&&-1!="}".indexOf(r)&&(K=!0),(!K||"\\"===r)&&k.push(l)):(k.push(l),K&&"\\"!==r&&k.push("\\"))}k=k.join("")}d&&
(c=/^[^A-Z]*$/.test(k));f=RegExp(k,c||f?"i":void 0)}else f=null}if(f){xa(a,f);a:if(a=e.getQuery(),f instanceof RegExp&&a instanceof RegExp){c=["global","multiline","ignoreCase","source"];for(d=0;d<c.length;d++)if(b=c[d],f[b]!==a[b]){a=!1;break a}a=!0}else a=!1;if(a)return f;e.setQuery(f);return f}}}function Oa(a){if("^"==a.source.charAt(0))var b=!0;return{token:function(c){if(b&&!c.sol())c.skipToEnd();else{var d=c.match(a,!1);if(d){if(0==d[0].length)return c.next(),"searching";if(!c.sol()&&(c.backUp(1),
!a.exec(c.next()+d[0])))return c.next(),null;c.match(a);return"searching"}for(;!c.eol()&&!(c.next(),c.match(a,!1)););}},query:a}}function xa(a,b){var c=C(a).getOverlay();if(!c||b!=c.query)c&&a.removeOverlay(c),c=Oa(b),a.addOverlay(c),C(a).setOverlay(c)}function ya(a,b,c,d){void 0===d&&(d=1);return a.operation(function(){for(var e=a.getCursor(),f=a.getSearchCursor(c,e),g=0;g<d;g++){var k=f.find(b);0==g&&(k&&t(f.from(),e))&&(k=f.find(b));if(!k&&(f=a.getSearchCursor(c,b?p(a.lastLine()):p(a.firstLine(),
0)),!f.find(b)))return}return f.from()})}function ha(a){a.removeOverlay(C(a).getOverlay());C(a).setOverlay(null)}function ia(a){var b=a.getScrollInfo(),c=a.coordsChar({left:0,top:6+b.top},"local");a=a.coordsChar({left:0,top:b.clientHeight-10+b.top},"local");return{top:c.line,bottom:a.line}}function Q(a){for(var b,c,d=[];a;){c=/<\w+-.+?>|<\w+>|./.exec(a);if(null===c)break;b=c[0];a=a.substring(c.index+b.length);d.push(b)}return d}function Pa(a,b,c,d,e,f,g){function k(){a.operation(function(){for(;!n;)h(),
l();r()})}function h(){var b=a.getRange(e.from(),e.to()).replace(f,g);e.replace(b)}function l(){if(e.findNext()){var b;b=e.from();var f=c,g=d;"number"!=typeof b&&(b=b.line);b=f instanceof Array?ca(b,f):g?b>=f&&b<=g:b==f;b?(a.scrollIntoView(e.from(),30),a.setSelection(e.from(),e.to()),p=e.from(),n=!1):n=!0}else n=!0}function r(b){b&&b();a.focus();p&&(a.setCursor(p),b=a.state.vim,b.exMode=!1,b.lastHPos=b.lastHSPos=p.ch)}function K(b,c,d){m.e_stop(b);switch(m.keyName(b)){case "Y":h();l();break;case "N":l();
break;case "A":a.operation(k);break;case "L":h();case "Q":case "Esc":case "Ctrl-C":case "Ctrl-[":r(d)}n&&r(d)}a.state.vim.exMode=!0;var n=!1,p=e.from();l();n?u(a,"No matches for "+f.source):b?W(a,{prefix:"replace with \x3cstrong\x3e"+g+"\x3c/strong\x3e (y/n/a/q/l)",onKeyDown:K}):k()}function R(a){var b=a.state.vim,c=q.macroModeState,d=q.registerController.getRegister("."),e=c.isPlaying;e||(a.off("change",za),m.off(a.getInputField(),"keydown",Aa));!e&&1<b.insertModeRepeat&&(Ba(a,b,b.insertModeRepeat-
1,!0),b.lastEditInputState.repeatOverride=b.insertModeRepeat);delete b.insertModeRepeat;b.insertMode=!1;a.setCursor(a.getCursor().line,a.getCursor().ch-1);a.setOption("keyMap","vim");a.setOption("disableInput",!0);a.toggleOverwrite(!1);d.setText(c.lastInsertModeChanges.changes.join(""));m.signal(a,"vim-mode-change",{mode:"normal"});c.isRecording&&(c.isPlaying||(a=q.registerController.getRegister(c.latestRegister))&&a.pushInsertModeChanges(c.lastInsertModeChanges))}function Ca(a,b){if(!a.isPlaying){var c=
q.registerController.getRegister(a.latestRegister);c&&c.pushText(b)}}function za(a,b){var c=q.macroModeState,d=c.lastInsertModeChanges;if(!c.isPlaying)for(;b;){d.expectCursorActivityForChange=!0;if("+input"==b.origin||"paste"==b.origin||void 0===b.origin)c=b.text.join("\n"),d.changes.push(c);b=b.next}}function Da(a){var b=a.state.vim;b.insertMode?(a=q.macroModeState,a.isPlaying||(a=a.lastInsertModeChanges,a.expectCursorActivityForChange?a.expectCursorActivityForChange=!1:a.changes=[])):"*mouse"==
a.doc.history.lastSelOrigin&&(b.lastHPos=a.doc.getCursor().ch)}function ja(a){this.keyName=a}function Aa(a){function b(){c.changes.push(new ja(d));return!0}var c=q.macroModeState.lastInsertModeChanges,d=m.keyName(a);(-1!=d.indexOf("Delete")||-1!=d.indexOf("Backspace"))&&m.lookupKey(d,["vim-insert"],b)}function Ba(a,b,c,d){function e(){k?L.processAction(a,b,b.lastEditActionCommand):L.evalInput(a,b)}function f(c){if(0<g.lastInsertModeChanges.changes.length){c=!b.lastEditActionCommand?1:c;var d=g.lastInsertModeChanges;
g.lastInsertModeChanges={};Ea(a,d.changes,c);g.lastInsertModeChanges=d}}var g=q.macroModeState;g.isPlaying=!0;var k=!!b.lastEditActionCommand,h=b.inputState;b.inputState=b.lastEditInputState;if(k&&b.lastEditActionCommand.interlaceInsertRepeat)for(var l=0;l<c;l++)e(),f(1);else d||e(),f(c);b.inputState=h;b.insertMode&&!d&&R(a);g.isPlaying=!1}function Ea(a,b,c){function d(b){if("string"==typeof b)m.commands[b](a);else b(a);return!0}for(var e=0;e<c;e++)for(var f=0;f<b.length;f++){var g=b[f];if(g instanceof
ja)m.lookupKey(g.keyName,["vim-insert"],d);else{var k=a.getCursor();a.replaceRange(g,k,k)}}}m.defineOption("vimMode",!1,function(a,b){b?(a.setOption("keyMap","vim"),a.setOption("disableInput",!0),m.signal(a,"vim-mode-change",{mode:"normal"}),a.on("beforeSelectionChange",la),a.on("cursorActivity",Da),ea(a),m.on(a.getInputField(),"paste",ma(a))):a.state.vim&&(a.setOption("keyMap","default"),a.setOption("disableInput",!1),a.off("beforeSelectionChange",la),a.off("cursorActivity",Da),m.off(a.getInputField(),
"paste",ma(a)),a.state.vim=null)});var Fa=/[\d]/,Qa=[/\w/,/[^\w\s]/],Ra=[/\S/],Y=ba(65,26),ka=ba(97,26),Z=ba(48,10),Ga="~`!@#$%^\x26*()_-+\x3d[{}]\\|/?.,\x3c\x3e:;\"'".split(""),Ha="Left Right Up Down Space Backspace Esc Home End PageUp PageDown Enter".split(" "),Na=[].concat(Y,ka,Z,["\x3c","\x3e"]),Sa=[].concat(Y,ka,Z,["-",'"',".",":"]),G={},La=function(){var a=100,b=-1,c=0,d=0,e=Array(a);return{cachedCursor:void 0,add:function(f,g,k){function h(c){var d=++b%a,g=e[d];g&&g.clear();e[d]=f.setBookmark(c)}
var l=e[b%a];l?(l=l.find())&&!t(l,g)&&h(g):h(g);h(k);c=b;d=b-a+1;0>d&&(d=0)},move:function(f,g){b+=g;b>c?b=c:b<d&&(b=d);var k=e[(a+b)%a];if(k&&!k.find()){var h=0<g?1:-1,l,r=f.getCursor();do if(b+=h,(k=e[(a+b)%a])&&(l=k.find())&&!t(r,l))break;while(b<c&&b>d)}return k}}},pa=function(a){return a?{changes:a.changes,expectCursorActivityForChange:a.expectCursorActivityForChange}:{changes:[],expectCursorActivityForChange:!1}};oa.prototype={exitMacroRecordMode:function(){var a=q.macroModeState;a.onRecordingDone();
a.onRecordingDone=void 0;a.isRecording=!1},enterMacroRecordMode:function(a,b){var c=q.registerController.getRegister(b);c&&(c.clear(),this.latestRegister=b,this.onRecordingDone=a.openDialog("(recording)["+b+"]",null,{bottom:!0}),this.isRecording=!0)}};var q,Ta={buildKeyMap:function(){},getRegisterController:function(){return q.registerController},resetVimGlobalState_:qa,getVimGlobalState_:function(){return q},maybeInitVimState_:ea,InsertModeKey:ja,map:function(a,b,c){I.map(a,b,c)},setOption:da,getOption:T,
defineOption:na,defineEx:function(a,b,c){if(0!==a.indexOf(b))throw Error('(Vim.defineEx) "'+b+'" is not a prefix of "'+a+'", command not registered');Ia[a]=c;I.commandMap_[b]={name:a,shortName:b,type:"api"}},handleKey:function(a,b){var c,d=ea(a),e=q.macroModeState;if(e.isRecording&&"q"==b)e.exitMacroRecordMode(),d.inputState=new E;else if("\x3cEsc\x3e"==b)d.inputState=new E,d.visualMode&&B(a);else{!d.visualMode&&!t(a.getCursor("head"),a.getCursor("anchor"))&&(d.visualMode=!0,d.visualLine=!1,m.signal(a,
"vim-mode-change",{mode:"visual"}),a.on("mousedown",B));if("0"!=b||"0"==b&&0===d.inputState.getRepeat())c=L.matchCommand(b,F,d);if(c)if("keyToKey"==c.type)for(d=0;d<c.toKeys.length;d++)this.handleKey(a,c.toKeys[d]);else e.isRecording&&Ca(e,b),L.processCommand(a,d,c);else Fa.test(b)&&d.inputState.pushRepeatDigit(b),e.isRecording&&Ca(e,b)}},handleEx:function(a,b){I.processCommand(a,b)}};E.prototype.pushRepeatDigit=function(a){this.operator?this.motionRepeat=this.motionRepeat.concat(a):this.prefixRepeat=
this.prefixRepeat.concat(a)};E.prototype.getRepeat=function(){var a=0;if(0<this.prefixRepeat.length||0<this.motionRepeat.length)a=1,0<this.prefixRepeat.length&&(a*=parseInt(this.prefixRepeat.join(""),10)),0<this.motionRepeat.length&&(a*=parseInt(this.motionRepeat.join(""),10));return a};v.prototype={setText:function(a,b){this.keyBuffer=[a||""];this.linewise=!!b},pushText:function(a,b){b&&(this.linewise||this.keyBuffer.push("\n"),this.linewise=!0);this.keyBuffer.push(a)},pushInsertModeChanges:function(a){this.insertModeChanges.push(pa(a))},
pushSearchQuery:function(a){this.searchQueries.push(a)},clear:function(){this.keyBuffer=[];this.insertModeChanges=[];this.searchQueries=[];this.linewise=!1},toString:function(){return this.keyBuffer.join("")}};ra.prototype={pushText:function(a,b,c,d){d&&"\n"==c.charAt(0)&&(c=c.slice(1)+"\n");d&&"\n"!==c.charAt(c.length-1)&&(c+="\n");var e=this.isValidRegister(a)?this.getRegister(a):null;if(e)O(a)?e.pushText(c,d):e.setText(c,d),this.unnamedRegister.setText(e.toString(),d);else{switch(b){case "yank":this.registers["0"]=
new v(c,d);break;case "delete":case "change":-1==c.indexOf("\n")?this.registers["-"]=new v(c,d):(this.shiftNumericRegisters_(),this.registers["1"]=new v(c,d))}this.unnamedRegister.setText(c,d)}},getRegister:function(a){if(!this.isValidRegister(a))return this.unnamedRegister;a=a.toLowerCase();this.registers[a]||(this.registers[a]=new v);return this.registers[a]},isValidRegister:function(a){return a&&ca(a,Sa)},shiftNumericRegisters_:function(){for(var a=9;2<=a;a--)this.registers[a]=this.getRegister(""+
(a-1))}};var L={matchCommand:function(a,b,c){function d(b){if(f.length<b.keys.length)return e.keyBuffer.push(a),null;"character"==b.keys[f.length-1]&&(e.selectedCharacter=k);e.keyBuffer=[];return b}for(var e=c.inputState,f=e.keyBuffer.concat(a),g=[],k,h=0;h<b.length;h++){var l=b[h];if(Ma(f,l.keys)&&!(e.operator&&"action"==l.type)){if("character"==l.keys[f.length-1]&&(k=f[f.length-1],1<k.length))switch(k){case "\x3cCR\x3e":k="\n";break;case "\x3cSpace\x3e":k=" ";break;default:continue}g.push(l)}}if(g.length){if(1==
g.length)return d(g[0]);b=c.visualMode?"visual":"normal";for(var r,h=0;h<g.length;h++)if(c=g[h],c.context==b){r=c;break}else!r&&!c.context&&(r=c);return d(r)}e.keyBuffer=[];return null},processCommand:function(a,b,c){b.inputState.repeatOverride=c.repeatOverride;switch(c.type){case "motion":this.processMotion(a,b,c);break;case "operator":this.processOperator(a,b,c);break;case "operatorMotion":this.processOperatorMotion(a,b,c);break;case "action":this.processAction(a,b,c);break;case "search":this.processSearch(a,
b,c);break;case "ex":case "keyToEx":this.processEx(a,b,c)}},processMotion:function(a,b,c){b.inputState.motion=c.motion;b.inputState.motionArgs=U(c.motionArgs);this.evalInput(a,b)},processOperator:function(a,b,c){var d=b.inputState;if(d.operator){if(d.operator==c.operator){d.motion="expandToLine";d.motionArgs={linewise:!0};this.evalInput(a,b);return}b.inputState=new E}d.operator=c.operator;d.operatorArgs=U(c.operatorArgs);b.visualMode&&this.evalInput(a,b)},processOperatorMotion:function(a,b,c){var d=
b.visualMode,e=U(c.operatorMotionArgs);e&&(d&&e.visualLine)&&(b.visualLine=!0);this.processOperator(a,b,c);d||this.processMotion(a,b,c)},processAction:function(a,b,c){var d=b.inputState,e=d.getRepeat(),f=!!e,g=U(c.actionArgs)||{};d.selectedCharacter&&(g.selectedCharacter=d.selectedCharacter);c.operator&&this.processOperator(a,b,c);c.motion&&this.processMotion(a,b,c);(c.motion||c.operator)&&this.evalInput(a,b);g.repeat=e||1;g.repeatIsExplicit=f;g.registerName=d.registerName;b.inputState=new E;b.lastMotion=
null;c.isEdit&&this.recordLastEdit(b,d,c);aa[c.action](a,g,b)},processSearch:function(a,b,c){function d(d,e,f){try{X(a,d,e,f)}catch(g){u(a,"Invalid regex: "+d);return}L.processMotion(a,b,{type:"motion",motion:"findNext",motionArgs:{forward:!0,toJumplist:c.searchArgs.toJumplist}})}function e(b){a.scrollTo(p.left,p.top);d(b,!0,!0);var c=q.macroModeState;c.isRecording&&(c.isPlaying||(c=q.registerController.getRegister(c.latestRegister))&&c.pushSearchQuery(b))}function f(b,c){var d;try{d=X(a,c,!0,!0)}catch(e){}d?
a.scrollIntoView(ya(a,!k,d),30):(ha(a),a.scrollTo(p.left,p.top))}function g(b,c,d){c=m.keyName(b);if("Esc"==c||"Ctrl-C"==c||"Ctrl-["==c)X(a,r),ha(a),a.scrollTo(p.left,p.top),m.e_stop(b),d(),a.focus()}if(a.getSearchCursor){var k=c.searchArgs.forward,h=c.searchArgs.wholeWordOnly;C(a).setReversed(!k);var l=k?"/":"?",r=C(a).getQuery(),p=a.getScrollInfo();switch(c.searchArgs.querySrc){case "prompt":h=q.macroModeState;h.isPlaying?(l=h.replaySearchQueries.shift(),d(l,!0,!1)):W(a,{onClose:e,prefix:l,desc:Ua,
onKeyUp:f,onKeyDown:g});break;case "wordUnderCursor":var n=V(a,!1,!0,!1,!0),w=!0;n||(n=V(a,!1,!0,!1,!1),w=!1);if(!n)break;l=a.getLine(n.start.line).substring(n.start.ch,n.end.ch);l=w&&h?"\\b"+l+"\\b":l.replace(/([.?*+$\[\]\/\\(){}|\-])/g,"\\$1");q.jumpList.cachedCursor=a.getCursor();a.setCursor(n.start);d(l,!0,!1)}}},processEx:function(a,b,c){function d(b){I.processCommand(a,b)}function e(b,c,d){c=m.keyName(b);if("Esc"==c||"Ctrl-C"==c||"Ctrl-["==c)m.e_stop(b),d(),a.focus()}"keyToEx"==c.type?I.processCommand(a,
c.exArgs.input):b.visualMode?W(a,{onClose:d,prefix:":",value:"'\x3c,'\x3e",onKeyDown:e}):W(a,{onClose:d,prefix:":",onKeyDown:e})},evalInput:function(a,b){var c=b.inputState,d=c.motion,e=c.motionArgs||{},f=c.operator,g=c.operatorArgs||{},k=c.registerName,h=z(a.getCursor("head")),l=z(a.getCursor("anchor")),r=z(h),m=z(r),n,w;f&&this.recordLastEdit(b,c);w=void 0!==c.repeatOverride?c.repeatOverride:c.getRepeat();if(0<w&&e.explicitRepeat)e.repeatIsExplicit=!0;else if(e.noRepeat||!e.explicitRepeat&&0===
w)w=1,e.repeatIsExplicit=!1;c.selectedCharacter&&(e.selectedCharacter=g.selectedCharacter=c.selectedCharacter);e.repeat=w;b.inputState=new E;if(d){c=M[d](a,e,b);b.lastMotion=M[d];if(!c)return;e.toJumplist&&(n=q.jumpList,(d=n.cachedCursor)?(t(d,c)||q.jumpList.add(a,d,c),delete n.cachedCursor):t(m,c)||q.jumpList.add(a,m,c));c instanceof Array?(r=c[0],n=c[1]):n=c;n||(n=p(r.line,r.ch));if(b.visualMode){if(s(l,h)&&(t(l,n)||s(n,l)))l.ch+=1;else if(s(h,l)&&(t(l,n)||s(l,n)))l.ch-=1;h=n;l=c instanceof Array?
r:l;b.visualLine&&(s(l,h)?(l.ch=0,c=a.lastLine(),h.line>c&&(h.line=c),h.ch=x(a,h.line)):(h.ch=0,l.ch=x(a,l.line)));a.setSelection(l,h);P(a,b,"\x3c",s(l,h)?l:h);P(a,b,"\x3e",s(l,h)?h:l)}else f||(n=H(a,n),a.setCursor(n.line,n.ch))}if(f){c=!1;b.lastMotion=null;g.repeat=w;b.visualMode&&(r=l,n=h,e.inclusive=!0);n&&s(n,r)?(h=r,r=n,n=h,c=!0):n||(n=z(r));e.inclusive&&(!b.visualMode||!c)&&n.ch++;g.selOffset?(n.line=r.line+g.selOffset.line,n.ch=g.selOffset.line?g.selOffset.ch:r.ch+g.selOffset.ch):b.visualMode&&
(h=p(),h.line=n.line-r.line,h.ch=h.line?n.ch:n.ch-r.ch,g.selOffset=h);if(h=e.linewise||b.visualMode&&b.visualLine||g.linewise)e=n,r.ch=0,e.ch=0,e.line++;else if(e.forward&&(e=n,l=a.getRange(r,e),/\n\s*$/.test(l))){l=l.split("\n");l.pop();for(w=l.pop();0<l.length&&w&&/^\s*$/.test(w);w=l.pop())e.line--,e.ch=0;w?(e.line--,e.ch=x(a,e.line)):e.ch=0}g.registerName=k;g.linewise=h;Va[f](a,g,b,r,n,m);b.visualMode&&B(a)}},recordLastEdit:function(a,b,c){var d=q.macroModeState;d.isPlaying||(a.lastEditInputState=
b,a.lastEditActionCommand=c,d.lastInsertModeChanges.changes=[],d.lastInsertModeChanges.expectCursorActivityForChange=!1)}},M={moveToTopLine:function(a,b){var c=ia(a).top+b.repeat-1;return p(c,y(a.getLine(c)))},moveToMiddleLine:function(a){var b=ia(a),b=Math.floor(0.5*(b.top+b.bottom));return p(b,y(a.getLine(b)))},moveToBottomLine:function(a,b){var c=ia(a).bottom-b.repeat+1;return p(c,y(a.getLine(c)))},expandToLine:function(a,b){var c=a.getCursor();return p(c.line+b.repeat-1,Infinity)},findNext:function(a,
b){var c=C(a),d=c.getQuery();if(d){var e=!b.forward,e=c.isReversed()?!e:e;xa(a,d);return ya(a,e,d,b.repeat)}},goToMark:function(a,b,c){return(c=c.marks[b.selectedCharacter])?(c=c.find(),b.linewise?{line:c.line,ch:y(a.getLine(c.line))}:c):null},moveToOtherHighlightedEnd:function(a){var b=z(a.getCursor("head"));a=z(a.getCursor("anchor"));s(a,b)?b.ch+=1:s(b,a)&&(a.ch-=1);return[b,a]},jumpToMark:function(a,b,c){for(var d=a.getCursor(),e=0;e<b.repeat;e++){var f=d,g;for(g in c.marks)if(/^[a-z]$/.test(g)){var k=
c.marks[g].find();if(!(b.forward?s(k,f):s(f,k))&&!(b.linewise&&k.line==f.line)){var h=t(f,d),l=b.forward?ta(f,k,d):ta(d,k,f);if(h||l)d=k}}}b.linewise&&(d=p(d.line,y(a.getLine(d.line))));return d},moveByCharacters:function(a,b){var c=a.getCursor(),d=b.repeat;return p(c.line,b.forward?c.ch+d:c.ch-d)},moveByLines:function(a,b,c){var d=a.getCursor(),e=d.ch;switch(c.lastMotion){case this.moveByLines:case this.moveByDisplayLines:case this.moveByScroll:case this.moveToColumn:case this.moveToEol:e=c.lastHPos;
break;default:c.lastHPos=e}var f=b.repeat+(b.repeatOffset||0),f=b.forward?d.line+f:d.line-f,g=a.firstLine(),k=a.lastLine();if(!(f<g&&d.line==g||f>k&&d.line==k))return b.toFirstChar&&(e=y(a.getLine(f)),c.lastHPos=e),c.lastHSPos=a.charCoords(p(f,e),"div").left,p(f,e)},moveByDisplayLines:function(a,b,c){var d=a.getCursor();switch(c.lastMotion){case this.moveByDisplayLines:case this.moveByScroll:case this.moveByLines:case this.moveToColumn:case this.moveToEol:break;default:c.lastHSPos=a.charCoords(d,
"div").left}var e=b.repeat,d=a.findPosV(d,b.forward?e:-e,"line",c.lastHSPos);d.hitSide&&(b.forward?b={top:a.charCoords(d,"div").top+8,left:c.lastHSPos}:(b=a.charCoords(p(a.firstLine(),0),"div"),b.left=c.lastHSPos),d=a.coordsChar(b,"div"));c.lastHPos=d.ch;return d},moveByPage:function(a,b){var c=a.getCursor(),d=b.repeat;return a.findPosV(c,b.forward?d:-d,"page")},moveByParagraph:function(a,b){for(var c=a.getCursor().line,d=b.repeat,e=b.forward?1:-1,f=0;f<d&&!(!b.forward&&c===a.firstLine()||b.forward&&
c==a.lastLine());f++)for(c+=e;c!==a.firstLine()&&c!=a.lastLine()&&a.getLine(c);)c+=e;return p(c,0)},moveByScroll:function(a,b,c){var d=a.getScrollInfo(),e=null;(e=b.repeat)||(e=d.clientHeight/(2*a.defaultTextHeight()));var f=a.charCoords(a.getCursor(),"local");b.repeat=e;e=M.moveByDisplayLines(a,b,c);if(!e)return null;b=a.charCoords(e,"local");a.scrollTo(null,d.top+b.top-f.top);return e},moveByWords:function(a,b){var c;var d=b.repeat;c=!!b.forward;var e=!!b.wordEnd,f=!!b.bigWord,g=a.getCursor(),k=
z(g),h=[];(c&&!e||!c&&e)&&d++;for(var l=!(c&&e),r=0;r<d;r++){var m;b:{m=a;var n=c,q=f,u=l,s=g.line,A=g.ch,D=m.getLine(s),J=n?1:-1,q=q?Ra:Qa;if(u&&""==D){s+=J;D=m.getLine(s);if(!(s>=m.firstLine()&&s<=m.lastLine())){m=null;break b}A=n?0:D.length}for(;;){if(u&&""==D){m={from:0,to:0,line:s};break b}for(var N=n=0<J?D.length:-1,t=n;A!=n;){for(var y=!1,v=0;v<q.length&&!y;++v)if(q[v].test(D.charAt(A))){for(N=A;A!=n&&q[v].test(D.charAt(A));)A+=J;t=A;y=N!=t;if(!(N==g.ch&&s==g.line&&t==N+J)){m={from:Math.min(N,
t+1),to:Math.max(N,t),line:s};break b}}y||(A+=J)}s+=J;if(!(s>=m.firstLine()&&s<=m.lastLine())){m=null;break b}D=m.getLine(s);A=0<J?0:D.length}throw Error("The impossible happened.");}if(!m){f=x(a,a.lastLine());h.push(c?{line:a.lastLine(),from:f,to:f}:{line:0,from:0,to:0});break}h.push(m);g=p(m.line,c?m.to-1:m.from)}d=h.length!=d;f=h[0];l=h.pop();if(c&&!e){if(!d&&(f.from!=k.ch||f.line!=k.line))l=h.pop();c=p(l.line,l.from)}else if(c&&e)c=p(l.line,l.to-1);else if(!c&&e){if(!d&&(f.to!=k.ch||f.line!=k.line))l=
h.pop();c=p(l.line,l.to)}else c=p(l.line,l.from);return c},moveTillCharacter:function(a,b){var c=ga(a,b.repeat,b.forward,b.selectedCharacter),d=b.forward?-1:1;ua(d,b);if(!c)return null;c.ch+=d;return c},moveToCharacter:function(a,b){var c=b.repeat;ua(0,b);return ga(a,c,b.forward,b.selectedCharacter)||a.getCursor()},moveToSymbol:function(a,b){var c;c=b.repeat;var d=b.forward,e=b.selectedCharacter,f=z(a.getCursor()),g=d?1:-1,k=d?a.lineCount():-1,h=f.ch,l=f.line,m=a.getLine(l),d={lineText:m,nextCh:m.charAt(h),
lastCh:null,index:h,symb:e,reverseSymb:(d?{")":"(","}":"{"}:{"(":")","{":"}"})[e],forward:d,depth:0,curMoveThrough:!1};if(h=Wa[e]){e=Ja[h].init;h=Ja[h].isComplete;for(e&&e(d);l!==k&&c;)d.index+=g,d.nextCh=d.lineText.charAt(d.index),d.nextCh||(l+=g,d.lineText=a.getLine(l)||"",0<g?d.index=0:(e=d.lineText.length,d.index=0<e?e-1:0),d.nextCh=d.lineText.charAt(d.index)),h(d)&&(f.line=l,f.ch=d.index,c--);c=d.nextCh||d.curMoveThrough?p(l,d.index):f}else c=f;return c||a.getCursor()},moveToColumn:function(a,
b,c){b=b.repeat;c.lastHPos=b-1;c.lastHSPos=a.charCoords(a.getCursor(),"div").left;c=a.getCursor().line;return H(a,p(c,b-1))},moveToEol:function(a,b,c){var d=a.getCursor();c.lastHPos=Infinity;b=p(d.line+b.repeat-1,Infinity);d=a.clipPos(b);d.ch--;c.lastHSPos=a.charCoords(d,"div").left;return b},moveToFirstNonWhiteSpaceCharacter:function(a){var b=a.getCursor();return p(b.line,y(a.getLine(b.line)))},moveToMatchedSymbol:function(a){var b=a.getCursor(),c=b.line,d=b.ch,e=a.getLine(c),f;do if((f=e.charAt(d++))&&
-1!="()[]{}".indexOf(f)){var g=a.getTokenTypeAt(p(c,d));if("string"!==g&&"comment"!==g)break}while(f);return f?a.findMatchingBracket(p(c,d)).to:b},moveToStartOfLine:function(a){a=a.getCursor();return p(a.line,0)},moveToLineOrEdgeOfDocument:function(a,b){var c=b.forward?a.lastLine():a.firstLine();b.repeatIsExplicit&&(c=b.repeat-a.getOption("firstLineNumber"));return p(c,y(a.getLine(c)))},textObjectManipulation:function(a,b){var c={"'":!0,'"':!0},d=b.selectedCharacter;"b"==d?d="(":"B"==d&&(d="{");var e=
!b.textObjectInner;if({"(":")",")":"(","{":"}","}":"{","[":"]","]":"["}[d]){var f=d,g=a.getCursor(),c={"(":/[()]/,")":/[()]/,"[":/[[\]]/,"]":/[[\]]/,"{":/[{}]/,"}":/[{}]/}[f],f={"(":"(",")":"(","[":"[","]":"[","{":"{","}":"{"}[f],d=a.getLine(g.line).charAt(g.ch)===f?1:0,f=a.scanForBracket(p(g.line,g.ch+d),-1,null,{bracketRegex:c}),c=a.scanForBracket(p(g.line,g.ch+d),1,null,{bracketRegex:c});if(!f||!c)e={start:g,end:g};else{f=f.pos;c=c.pos;if(f.line==c.line&&f.ch>c.ch||f.line>c.line)g=f,f=c,c=g;e?
c.ch+=1:f.ch+=1;e={start:f,end:c}}}else if(c[d]){var c=d,d=z(a.getCursor()),k=a.getLine(d.line).split(""),h,l;h=k.indexOf(c);d.ch<h?d.ch=h:h<d.ch&&k[d.ch]==c&&(f=d.ch,--d.ch);if(k[d.ch]==c&&!f)g=d.ch+1;else for(h=d.ch;-1<h&&!g;h--)k[h]==c&&(g=h+1);if(g&&!f){h=g;for(l=k.length;h<l&&!f;h++)k[h]==c&&(f=h)}!g||!f?e={start:d,end:d}:(e&&(--g,++f),e={start:p(d.line,g),end:p(d.line,f)})}else if("W"===d)e=V(a,e,!0,!0);else if("w"===d)e=V(a,e,!0,!1);else return null;return[e.start,e.end]},repeatLastCharacterSearch:function(a,
b){var c=q.lastChararacterSearch,d=b.repeat,e=b.forward===c.forward,f=(c.increment?1:0)*(e?-1:1);a.moveH(-f,"char");b.inclusive=e?!0:!1;c=ga(a,d,e,c.selectedCharacter);if(!c)return a.moveH(f,"char"),a.getCursor();c.ch+=f;return c}},Va={change:function(a,b,c,d,e){q.registerController.pushText(b.registerName,"change",a.getRange(d,e),b.linewise);b.linewise?(b=e.line>a.lastLine()?"":"\n",a.replaceRange(b,d,e),a.indentLine(d.line,"smart"),d.ch=null):(b=a.getRange(d,e),/^\s*$/.test(b)||(b=/\s+$/.exec(b))&&
(e=S(e,0,-b[0].length)),a.replaceRange("",d,e));aa.enterInsertMode(a,{},a.state.vim);a.setCursor(d)},"delete":function(a,b,c,d,e){b.linewise&&(e.line>a.lastLine()&&d.line>a.firstLine())&&(d.line--,d.ch=x(a,d.line));q.registerController.pushText(b.registerName,"delete",a.getRange(d,e),b.linewise);a.replaceRange("",d,e);b.linewise?a.setCursor(M.moveToFirstNonWhiteSpaceCharacter(a)):a.setCursor(d)},indent:function(a,b,c,d,e){var f=d.line;e=e.line;c=c.visualMode?b.repeat:1;for(b.linewise&&e--;f<=e;f++)for(var g=
0;g<c;g++)a.indentLine(f,b.indentRight);a.setCursor(d);a.setCursor(M.moveToFirstNonWhiteSpaceCharacter(a))},swapcase:function(a,b,c,d,e,f){c=a.getRange(d,e);for(var g="",k=0;k<c.length;k++)var h=c.charAt(k),g=g+(O(h)?h.toLowerCase():h.toUpperCase());a.replaceRange(g,d,e);b.shouldMoveCursor||a.setCursor(f)},yank:function(a,b,c,d,e,f){q.registerController.pushText(b.registerName,"yank",a.getRange(d,e),b.linewise);a.setCursor(f)}},aa={jumpListWalk:function(a,b,c){c.visualMode||(c=b.repeat,b=(b=(b=q.jumpList.move(a,
b.forward?c:-c))?b.find():void 0)?b:a.getCursor(),a.setCursor(b))},scroll:function(a,b,c){if(!c.visualMode){var d=b.repeat||1;c=a.defaultTextHeight();var e=a.getScrollInfo().top,d=c*d,e=b.forward?e+d:e-d,d=z(a.getCursor()),f=a.charCoords(d,"local");b.forward?e>f.top?(d.line+=(e-f.top)/c,d.line=Math.ceil(d.line),a.setCursor(d),f=a.charCoords(d,"local"),a.scrollTo(null,f.top)):a.scrollTo(null,e):(b=e+a.getScrollInfo().clientHeight,b<f.bottom?(d.line-=(f.bottom-b)/c,d.line=Math.floor(d.line),a.setCursor(d),
f=a.charCoords(d,"local"),a.scrollTo(null,f.bottom-a.getScrollInfo().clientHeight)):a.scrollTo(null,e))}},scrollToCursor:function(a,b){var c=a.getCursor().line,d=a.charCoords(p(c,0),"local"),c=a.getScrollInfo().clientHeight,e=d.top,d=d.bottom-e;switch(b.position){case "center":e=e-c/2+d;break;case "bottom":e=e-c+1.4*d;break;case "top":e+=0.4*d}a.scrollTo(null,e)},replayMacro:function(a,b,c){var d=b.selectedCharacter;b=b.repeat;var e=q.macroModeState;"@"==d&&(d=e.latestRegister);for(;b--;){var f=a,
g=c,k=e,h=q.registerController.getRegister(d),l=h.keyBuffer,p=0;k.isPlaying=!0;k.replaySearchQueries=h.searchQueries.slice(0);for(var s=0;s<l.length;s++)for(var n=l[s],w,u;n;)w=/<\w+-.+?>|<\w+>|./.exec(n),u=w[0],n=n.substring(w.index+u.length),m.Vim.handleKey(f,u),g.insertMode&&(Ea(f,h.insertModeChanges[p++].changes,1),R(f));k.isPlaying=!1}},enterMacroRecordMode:function(a,b){q.macroModeState.enterMacroRecordMode(a,b.selectedCharacter)},enterInsertMode:function(a,b,c){a.getOption("readOnly")||(c.insertMode=
!0,c.insertModeRepeat=b&&b.repeat||1,c=b?b.insertAt:null,"eol"==c?(c=a.getCursor(),c=p(c.line,x(a,c.line)),a.setCursor(c)):"charAfter"==c?a.setCursor(S(a.getCursor(),0,1)):"firstNonBlank"==c&&a.setCursor(M.moveToFirstNonWhiteSpaceCharacter(a)),a.setOption("keyMap","vim-insert"),a.setOption("disableInput",!1),b&&b.replace?(a.toggleOverwrite(!0),a.setOption("keyMap","vim-replace"),m.signal(a,"vim-mode-change",{mode:"replace"})):(a.setOption("keyMap","vim-insert"),m.signal(a,"vim-mode-change",{mode:"insert"})),
q.macroModeState.isPlaying||(a.on("change",za),m.on(a.getInputField(),"keydown",Aa)))},toggleVisualMode:function(a,b,c){var d=b.repeat,e=a.getCursor();c.visualMode?(e=a.getCursor("anchor"),d=a.getCursor("head"),!c.visualLine&&b.linewise?(c.visualLine=!0,e.ch=s(e,d)?0:x(a,e.line),d.ch=s(e,d)?x(a,d.line):0,a.setSelection(e,d),m.signal(a,"vim-mode-change",{mode:"visual",subMode:"linewise"})):c.visualLine&&!b.linewise?(c.visualLine=!1,m.signal(a,"vim-mode-change",{mode:"visual"})):B(a)):(a.on("mousedown",
B),c.visualMode=!0,c.visualLine=!!b.linewise,c.visualLine?(e.ch=0,d=H(a,p(e.line+d-1,x(a,e.line)),!0)):d=H(a,p(e.line,e.ch+d),!0),!b.repeatIsExplicit&&!c.visualLine?(a.setCursor(d),a.setSelection(d,e)):a.setSelection(e,d),m.signal(a,"vim-mode-change",{mode:"visual",subMode:c.visualLine?"linewise":""}));P(a,c,"\x3c",s(e,d)?e:d);P(a,c,"\x3e",s(e,d)?d:e)},reselectLastSelection:function(a,b,c){c.lastSelection&&(b=c.lastSelection,a.setSelection(b.curStart,b.curEnd),b.visualLine?(c.visualMode=!0,c.visualLine=
!0):(c.visualMode=!0,c.visualLine=!1),m.signal(a,"vim-mode-change",{mode:"visual",subMode:c.visualLine?"linewise":""}))},joinLines:function(a,b,c){var d,e;c.visualMode?(d=a.getCursor("anchor"),e=a.getCursor("head"),e.ch=x(a,e.line)-1):(b=Math.max(b.repeat,2),d=a.getCursor(),e=H(a,p(d.line+b-1,Infinity)));var f=0;a.operation(function(){for(var b=d.line;b<e.line;b++){f=x(a,d.line);var c=p(d.line+1,x(a,d.line+1)),h=a.getRange(d,c),h=h.replace(/\n\s*/g," ");a.replaceRange(h,d,c)}b=p(d.line,f);a.setCursor(b)})},
newLineAndEnterInsertMode:function(a,b,c){c.insertMode=!0;var d=z(a.getCursor());d.line===a.firstLine()&&!b.after?(a.replaceRange("\n",p(a.firstLine(),0)),a.setCursor(a.firstLine(),0)):(d.line=b.after?d.line:d.line-1,d.ch=x(a,d.line),a.setCursor(d),(m.commands.newlineAndIndentContinueComment||m.commands.newlineAndIndent)(a));this.enterInsertMode(a,{repeat:b.repeat},c)},paste:function(a,b){var c=z(a.getCursor()),d=q.registerController.getRegister(b.registerName),e=d.toString();if(e){if(b.matchIndent)var f=
function(b){var c=b.split("\t").length-1;b=b.split(" ").length-1;return c*a.options.tabSize+1*b},g=a.getLine(a.getCursor().line),k=f(g.match(/^\s*/)[0]),g=e.replace(/\n$/,""),h=e!==g,l=f(e.match(/^\s*/)[0]),e=g.replace(/^\s*/gm,function(b){b=k+(f(b)-l);return 0>b?"":a.options.indentWithTabs?Array(Math.floor(b/a.options.tabSize)+1).join("\t"):Array(b+1).join(" ")}),e=e+(h?"\n":"");1<b.repeat&&(e=Array(b.repeat+1).join(e));(d=d.linewise)?b.after?(e="\n"+e.slice(0,e.length-1),c.ch=x(a,c.line)):c.ch=
0:c.ch+=b.after?1:0;a.replaceRange(e,c);d&&b.after?e=p(c.line+1,y(a.getLine(c.line+1))):d&&!b.after?e=p(c.line,y(a.getLine(c.line))):!d&&b.after?(c=a.indexFromPos(c),e=a.posFromIndex(c+e.length-1)):(c=a.indexFromPos(c),e=a.posFromIndex(c+e.length));a.setCursor(e)}},undo:function(a,b){a.operation(function(){sa(a,m.commands.undo,b.repeat)();a.setCursor(a.getCursor("anchor"))})},redo:function(a,b){sa(a,m.commands.redo,b.repeat)()},setRegister:function(a,b,c){c.inputState.registerName=b.selectedCharacter},
setMark:function(a,b,c){P(a,c,b.selectedCharacter,a.getCursor())},replace:function(a,b,c){var d=b.selectedCharacter,e=a.getCursor(),f;c.visualMode?(e=a.getCursor("start"),f=a.getCursor("end"),f=a.clipPos(p(f.line,f.ch+1))):(f=a.getLine(e.line),b=e.ch+b.repeat,b>f.length&&(b=f.length),f=p(e.line,b));"\n"==d?(c.visualMode||a.replaceRange("",e,f),(m.commands.newlineAndIndentContinueComment||m.commands.newlineAndIndent)(a)):(b=a.getRange(e,f),b=b.replace(/[^\n]/g,d),a.replaceRange(b,e,f),c.visualMode?
(a.setCursor(e),B(a)):a.setCursor(S(f,0,-1)))},incrementNumberToken:function(a,b){for(var c=a.getCursor(),d=a.getLine(c.line),e=/-?\d+/g,f,g,k,h;null!==(f=e.exec(d))&&!(h=f[0],g=f.index,k=g+h.length,c.ch<k););if((b.backtrack||!(k<=c.ch))&&h)d=b.increase?1:-1,d=parseInt(h)+d*b.repeat,h=p(c.line,g),k=p(c.line,k),d=d.toString(),a.replaceRange(d,h,k),a.setCursor(p(c.line,g+d.length-1))},repeatLastEdit:function(a,b,c){if(c.lastEditInputState){var d=b.repeat;d&&b.repeatIsExplicit?c.lastEditInputState.repeatOverride=
d:d=c.lastEditInputState.repeatOverride||d;Ba(a,c,d,!1)}},changeCase:function(a,b,c){var d;a:{var e=a.getCursor("anchor");d=a.getCursor("head");var f=c.lastSelection;if(c.visualMode)B(a);else{var g=(c=f.curEnd.line-f.curStart.line)?f.curEnd.ch:f.curEnd.ch-f.curStart.ch;d={line:d.line+c,ch:c?d.ch:g+d.ch};if(f.visualLine){d=[{line:e.line,ch:0},{line:d.line,ch:x(a,d.line)}];break a}}d=[e,d]}e=d[0];d=d[1];b=b.toLower;s(d,e)?(f=e,e=d,d=f):d=a.clipPos(p(d.line,d.ch+1));f=a.getRange(e,d);a.replaceRange(b?
f.toLowerCase():f.toUpperCase(),e,d);a.setCursor(e)}},Wa={"(":"bracket",")":"bracket","{":"bracket","}":"bracket","[":"section","]":"section","*":"comment","/":"comment",m:"method",M:"method","#":"preprocess"},Ja={bracket:{isComplete:function(a){if(a.nextCh===a.symb){if(a.depth++,1<=a.depth)return!0}else a.nextCh===a.reverseSymb&&a.depth--;return!1}},section:{init:function(a){a.curMoveThrough=!0;a.symb=(a.forward?"]":"[")===a.symb?"{":"}"},isComplete:function(a){return 0===a.index&&a.nextCh===a.symb}},
comment:{isComplete:function(a){var b="*"===a.lastCh&&"/"===a.nextCh;a.lastCh=a.nextCh;return b}},method:{init:function(a){a.symb="m"===a.symb?"{":"}";a.reverseSymb="{"===a.symb?"}":"{"},isComplete:function(a){return a.nextCh===a.symb?!0:!1}},preprocess:{init:function(a){a.index=0},isComplete:function(a){if("#"===a.nextCh){var b=a.lineText.match(/#(\w+)/)[1];if("endif"===b){if(a.forward&&0===a.depth)return!0;a.depth++}else if("if"===b){if(!a.forward&&0===a.depth)return!0;a.depth--}if("else"===b&&
0===a.depth)return!0}return!1}}};na("pcre",!0,"boolean");va.prototype={getQuery:function(){return q.query},setQuery:function(a){q.query=a},getOverlay:function(){return this.searchOverlay},setOverlay:function(a){this.searchOverlay=a},isReversed:function(){return q.isReversed},setReversed:function(a){q.isReversed=a}};var Ua="(Javascript regexp)",Ka=[{name:"map"},{name:"nmap",shortName:"nm"},{name:"vmap",shortName:"vm"},{name:"unmap"},{name:"write",shortName:"w"},{name:"undo",shortName:"u"},{name:"redo",
shortName:"red"},{name:"set",shortName:"set"},{name:"sort",shortName:"sor"},{name:"substitute",shortName:"s"},{name:"nohlsearch",shortName:"noh"},{name:"delmarks",shortName:"delm"},{name:"registers",shortName:"reg",excludeFromCommandHistory:!0}];$.ExCommandDispatcher=function(){this.buildCommandMap_()};$.ExCommandDispatcher.prototype={processCommand:function(a,b){var c=a.state.vim,d=q.registerController.getRegister(":"),e=d.toString();c.visualMode&&B(a);var f=new m.StringStream(b);d.setText(b);var g=
{};g.input=b;try{this.parseInput_(a,f,g)}catch(k){throw u(a,k),k;}var h;if(g.commandName){if(c=this.matchCommand_(g.commandName)){h=c.name;c.excludeFromCommandHistory&&d.setText(e);this.parseCommandArgs_(f,g,c);if("exToKey"==c.type){for(d=0;d<c.toKeys.length;d++)m.Vim.handleKey(a,c.toKeys[d]);return}if("exToEx"==c.type){this.processCommand(a,c.toInput);return}}}else void 0!==g.line&&(h="move");if(h)try{Ia[h](a,g)}catch(l){throw u(a,l),l;}else u(a,'Not an editor command ":'+b+'"')},parseInput_:function(a,
b,c){b.eatWhile(":");b.eat("%")?(c.line=a.firstLine(),c.lineEnd=a.lastLine()):(c.line=this.parseLineSpec_(a,b),void 0!==c.line&&b.eat(",")&&(c.lineEnd=this.parseLineSpec_(a,b)));a=b.match(/^(\w+)/);c.commandName=a?a[1]:b.match(/.*/)[0];return c},parseLineSpec_:function(a,b){var c=b.match(/^(\d+)/);if(c)return parseInt(c[1],10)-1;switch(b.next()){case ".":return a.getCursor().line;case "$":return a.lastLine();case "'":if((c=a.state.vim.marks[b.next()])&&c.find())return c.find().line;throw Error("Mark not set");
default:b.backUp(1)}},parseCommandArgs_:function(a,b,c){a.eol()||(b.argString=a.match(/.*/)[0],a=c.argDelimiter||/\s+/,a=fa(b.argString).split(a),a.length&&a[0]&&(b.args=a))},matchCommand_:function(a){for(var b=a.length;0<b;b--){var c=a.substring(0,b);if(this.commandMap_[c]&&(c=this.commandMap_[c],0===c.name.indexOf(a)))return c}return null},buildCommandMap_:function(){this.commandMap_={};for(var a=0;a<Ka.length;a++){var b=Ka[a];this.commandMap_[b.shortName||b.name]=b}},map:function(a,b,c){if(":"!=
a&&":"==a.charAt(0)){if(c)throw Error("Mode not supported for ex mappings");c=a.substring(1);":"!=b&&":"==b.charAt(0)?this.commandMap_[c]={name:c,type:"exToEx",toInput:b.substring(1),user:!0}:this.commandMap_[c]={name:c,type:"exToKey",toKeys:Q(b),user:!0}}else b=":"!=b&&":"==b.charAt(0)?{keys:Q(a),type:"keyToEx",exArgs:{input:b.substring(1)},user:!0}:{keys:Q(a),type:"keyToKey",toKeys:Q(b),user:!0},c&&(b.context=c),F.unshift(b)},unmap:function(a,b){var c=function(a,b){if(a===b||null==a||null==b)return!0;
if(a.length!=b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0};if(":"!=a&&":"==a.charAt(0)){if(b)throw Error("Mode not supported for ex mappings");c=a.substring(1);if(this.commandMap_[c]&&this.commandMap_[c].user){delete this.commandMap_[c];return}}else for(var d=Q(a),e=0;e<F.length;e++)if(c(d,F[e].keys)&&F[e].context===b&&F[e].user){F.splice(e,1);return}throw Error("No such mapping.");}};var Ia={map:function(a,b,c){var d=b.args;!d||2>d.length?a&&u(a,"Invalid mapping: "+
b.input):I.map(d[0],d[1],c)},nmap:function(a,b){this.map(a,b,"normal")},vmap:function(a,b){this.map(a,b,"visual")},unmap:function(a,b,c){var d=b.args;!d||1>d.length?a&&u(a,"No such mapping: "+b.input):I.unmap(d[0],c)},move:function(a,b){L.processCommand(a,a.state.vim,{type:"motion",motion:"moveToLineOrEdgeOfDocument",motionArgs:{forward:!1,explicitRepeat:!0,linewise:!0},repeatOverride:b.line+1})},set:function(a,b){var c=b.args;if(!c||1>c.length)a&&u(a,"Invalid mapping: "+b.input);else{var d=c[0].split("\x3d"),
c=d[0],d=d[1],e=!1;if("?"==c.charAt(c.length-1)){if(d)throw Error("Trailing characters: "+b.argString);c=c.substring(0,c.length-1);e=!0}void 0===d&&"no"==c.substring(0,2)&&(c=c.substring(2),d=!1);var f=G[c]&&"boolean"==G[c].type;f&&void 0==d&&(d=!0);!f&&!d||e?(d=T(c),!0===d||!1===d?u(a," "+(d?"":"no")+c):u(a,"  "+c+"\x3d"+d)):da(c,d)}},registers:function(a,b){var c=b.args,d=q.registerController.registers,e="----------Registers----------\x3cbr\x3e\x3cbr\x3e";if(c)for(var c=c.join(""),f=0;f<c.length;f++){if(k=
c.charAt(f),q.registerController.isValidRegister(k))var g=d[k]||new v,e=e+('"'+k+"    "+g.toString()+"\x3cbr\x3e")}else for(var k in d)c=d[k].toString(),c.length&&(e+='"'+k+"    "+c+"\x3cbr\x3e");u(a,e)},sort:function(a,b){function c(a,b){if(d){var c;c=a;a=b;b=c}e&&(a=a.toLowerCase(),b=b.toLowerCase());c=g&&r.exec(a);var f=g&&r.exec(b);if(!c)return a<b?-1:1;c=parseInt((c[1]+c[2]).toLowerCase(),q);f=parseInt((f[1]+f[2]).toLowerCase(),q);return c-f}var d,e,f,g,k=function(){if(b.argString){var a=new m.StringStream(b.argString);
a.eat("!")&&(d=!0);if(!a.eol()){if(!a.eatSpace())return"Invalid arguments";var c=a.match(/[a-z]+/);if(c){c=c[0];e=-1!=c.indexOf("i");f=-1!=c.indexOf("u");var h=-1!=c.indexOf("d")&&1,k=-1!=c.indexOf("x")&&1,c=-1!=c.indexOf("o")&&1;if(1<h+k+c)return"Invalid arguments";g=h&&"decimal"||k&&"hex"||c&&"octal"}a.eatSpace()&&a.match(/\/.*\//)&&"patterns not supported"}}}();if(k)u(a,k+": "+b.argString);else{var k=b.line||a.firstLine(),h=b.lineEnd||b.line||a.lastLine();if(k!=h){var k=p(k,0),h=p(h,x(a,h)),l=
a.getRange(k,h).split("\n"),r="decimal"==g?/(-?)([\d]+)/:"hex"==g?/(-?)(?:0x)?([0-9a-f]+)/i:"octal"==g?/([0-7]+)/:null,q="decimal"==g?10:"hex"==g?16:"octal"==g?8:null,n=[],s=[];if(g)for(var t=0;t<l.length;t++)r.exec(l[t])?n.push(l[t]):s.push(l[t]);else s=l;n.sort(c);s.sort(c);l=!d?s.concat(n):n.concat(s);if(f)for(var n=l,v,l=[],t=0;t<n.length;t++)n[t]!=v&&l.push(n[t]),v=n[t];a.replaceRange(l.join("\n"),k,h)}}},substitute:function(a,b){if(!a.getSearchCursor)throw Error("Search feature not available. Requires searchcursor.js or any other getSearchCursor implementation.");
var c=b.argString,d=c?wa(c):[],e="";if(d.length){if(0!==d[0]){u(a,"Substitutions should be of the form :s/pattern/replace/");return}var f=c.substring(d[0]+1,d[1]),g,k,h=!1;if(d[1]){e=c.substring(d[1]+1,d[2]);if(T("pcre")){for(var e=new m.StringStream(e),l=[];!e.eol();){for(;e.peek()&&"\\"!=e.peek();)l.push(e.next());e.match("\\/",!0)?l.push("/"):e.match("\\\\",!0)?l.push("\\"):l.push(e.next())}e=l.join("")}else{for(var l=!1,r=[],s=-1;s<e.length;s++){var n=e.charAt(s)||"",t=e.charAt(s+1)||"";l?(r.push(n),
l=!1):"\\"===n?(l=!0,Fa.test(t)||"$"===t?r.push("$"):"/"!==t&&"\\"!==t&&r.push("\\")):("$"===n&&r.push("$"),r.push(n),"/"===t&&r.push("\\"))}e=r.join("")}q.lastSubstituteReplacePart=e}d[2]&&(k=c.substring(d[2]+1).split(" "),g=k[0],k=parseInt(k[1]));g&&(-1!=g.indexOf("c")&&(h=!0,g.replace("c","")),f=f+"/"+g)}if(f)try{X(a,f,!0,!0)}catch(v){u(a,"Invalid regex: "+f);return}e=e||q.lastSubstituteReplacePart;void 0===e?u(a,"No previous substitute regular expression"):(f=C(a).getQuery(),g=void 0!==b.line?
b.line:a.getCursor().line,c=b.lineEnd||g,k&&(g=c,c=g+k-1),k=H(a,p(g,0)),k=a.getSearchCursor(f,k),Pa(a,h,g,c,k,f,e))},redo:m.commands.redo,undo:m.commands.undo,write:function(a){m.commands.save?m.commands.save(a):a.save()},nohlsearch:function(a){ha(a)},delmarks:function(a,b){if(!b.argString||!fa(b.argString))u(a,"Argument required");else for(var c=a.state.vim,d=new m.StringStream(fa(b.argString));!d.eol();){d.eatSpace();var e=d.pos;if(!d.match(/[a-zA-Z]/,!1)){u(a,"Invalid argument: "+b.argString.substring(e));
break}var f=d.next();if(d.match("-",!0)){if(!d.match(/[a-zA-Z]/,!1)){u(a,"Invalid argument: "+b.argString.substring(e));break}var g=d.next();if(/^[a-z]$/.test(f)&&/^[a-z]$/.test(g)||O(f)&&O(g)){f=f.charCodeAt(0);g=g.charCodeAt(0);if(f>=g){u(a,"Invalid argument: "+b.argString.substring(e));break}for(e=0;e<=g-f;e++){var k=String.fromCharCode(f+e);delete c.marks[k]}}else{u(a,"Invalid argument: "+f+"-");break}}else delete c.marks[f]}}},I=new $.ExCommandDispatcher;m.keyMap.vim=function(){function a(a){return function(b){m.Vim.handleKey(b,
a)}}function b(b,e){for(var f=0;f<b.length;f++){var g=b[f];!e&&1==g.length&&(g="'"+g+"'");var k=e,h=b[f];O(h)&&"Ctrl"==k&&(h=h.toLowerCase());k&&(h=k.charAt(0)+"-"+h);h=(k={Enter:"CR",Backspace:"BS",Delete:"Del"}[h])?k:h;h=1<h.length?"\x3c"+h+"\x3e":h;c[e?e+"-"+g:g]=a(h)}}var c={nofallthrough:!0,style:"fat-cursor"};b(Y);b(ka);b(Y,"Ctrl");b(Ga);b(Ga,"Ctrl");b(Z);b(Z,"Ctrl");b(Ha);b(Ha,"Ctrl");return c}();m.keyMap["vim-insert"]={Esc:R,"Ctrl-[":R,"Ctrl-C":R,"Ctrl-N":"autocomplete","Ctrl-P":"autocomplete",
Enter:function(a){(m.commands.newlineAndIndentContinueComment||m.commands.newlineAndIndent)(a)},fallthrough:["default"]};m.keyMap["vim-replace"]={Backspace:"goCharLeft",fallthrough:["vim-insert"]};qa();return Ta};m.Vim=$()});
//# sourceMappingURL=vim.js.map