//>>built
(function(p){"object"==typeof exports&&"object"==typeof module?p(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define("codemirror4/mode/javascript/javascript",["../../lib/codemirror"],p):p(CodeMirror)})(function(p){p.defineMode("javascript",function(ja,r){function n(a,b,e){C=a;E=e;return b}function t(a,b){var e=a.next();if('"'==e||"'"==e)return b.tokenize=ka(e),b.tokenize(a,b);if("."==e&&a.match(/^\d+(?:[eE][+\-]?\d+)?/))return n("number","number");if("."==e&&a.match(".."))return n("spread",
"meta");if(/[\[\]{}\(\),;\:\.]/.test(e))return n(e);if("\x3d"==e&&a.eat("\x3e"))return n("\x3d\x3e","operator");if("0"==e&&a.eat(/x/i))return a.eatWhile(/[\da-f]/i),n("number","number");if(/\d/.test(e))return a.match(/^\d*(?:\.\d*)?(?:[eE][+\-]?\d+)?/),n("number","number");if("/"==e){if(a.eat("*"))return b.tokenize=F,F(a,b);if(a.eat("/"))return a.skipToEnd(),n("comment","comment");if("operator"==b.lastType||"keyword c"==b.lastType||"sof"==b.lastType||/^[\[{}\(,;:]$/.test(b.lastType)){a:for(var e=
!1,d,c=!1;null!=(d=a.next());){if(!e){if("/"==d&&!c)break a;"["==d?c=!0:c&&"]"==d&&(c=!1)}e=!e&&"\\"==d}a.eatWhile(/[gimy]/);return n("regexp","string-2")}a.eatWhile(L);return n("operator","operator",a.current())}if("`"==e)return b.tokenize=M,M(a,b);if("#"==e)return a.skipToEnd(),n("error","error");if(L.test(e))return a.eatWhile(L),n("operator","operator",a.current());a.eatWhile(/[\w\$_]/);e=a.current();return(d=W.propertyIsEnumerable(e)&&W[e])&&"."!=b.lastType?n(d.type,d.style,e):n("variable","variable",
e)}function ka(a){return function(b,e){var d=!1,c;if(G&&"@"==b.peek()&&b.match(la))return e.tokenize=t,n("jsonld-keyword","meta");for(;null!=(c=b.next())&&(c!=a||d);)d=!d&&"\\"==c;d||(e.tokenize=t);return n("string","string")}}function F(a,b){for(var e=!1,d;d=a.next();){if("/"==d&&e){b.tokenize=t;break}e="*"==d}return n("comment","comment")}function M(a,b){for(var e=!1,d;null!=(d=a.next());){if(!e&&("`"==d||"$"==d&&a.eat("{"))){b.tokenize=t;break}e=!e&&"\\"==d}return n("quasi","string-2",a.current())}
function N(a,b){b.fatArrowAt&&(b.fatArrowAt=null);var e=a.string.indexOf("\x3d\x3e",a.start);if(!(0>e)){for(var d=0,c=!1,e=e-1;0<=e;--e){var f=a.string.charAt(e),g=ma.indexOf(f);if(0<=g&&3>g){if(!d){++e;break}if(0==--d)break}else if(3<=g&&6>g)++d;else if(/[$\w]/.test(f))c=!0;else if(c&&!d){++e;break}}c&&!d&&(b.fatArrowAt=e)}}function X(a,b,e,d,c,f){this.indented=a;this.column=b;this.type=e;this.prev=c;this.info=f;null!=d&&(this.align=d)}function g(){for(var a=arguments.length-1;0<=a;a--)f.cc.push(arguments[a])}
function c(){g.apply(null,arguments);return!0}function u(a){function b(b){for(;b;b=b.next)if(b.name==a)return!0;return!1}var e=f.state;e.context?(f.marked="def",b(e.localVars)||(e.localVars={name:a,next:e.localVars})):!b(e.globalVars)&&r.globalVars&&(e.globalVars={name:a,next:e.globalVars})}function v(){f.state.context={prev:f.state.context,vars:f.state.localVars};f.state.localVars=na}function w(){f.state.localVars=f.state.context.vars;f.state.context=f.state.context.prev}function k(a,b){var e=function(){var d=
f.state,e=d.indented;"stat"==d.lexical.type&&(e=d.lexical.indented);d.lexical=new X(e,f.stream.column(),a,null,d.lexical,b)};e.lex=!0;return e}function h(){var a=f.state;a.lexical.prev&&(")"==a.lexical.type&&(a.indented=a.lexical.indented),a.lexical=a.lexical.prev)}function l(a){function b(e){return e==a?c():";"==a?g():c(b)}return b}function q(a,b){return"var"==a?c(k("vardef",b.length),O,l(";"),h):"keyword a"==a?c(k("form"),m,q,h):"keyword b"==a?c(k("form"),q,h):"{"==a?c(k("}"),P,h):";"==a?c():"if"==
a?("else"==f.state.lexical.info&&f.state.cc[f.state.cc.length-1]==h&&f.state.cc.pop()(),c(k("form"),m,q,h,Y)):"function"==a?c(x):"for"==a?c(k("form"),Z,q,h):"variable"==a?c(k("stat"),oa):"switch"==a?c(k("form"),m,k("}","switch"),l("{"),P,h,h):"case"==a?c(m,l(":")):"default"==a?c(l(":")):"catch"==a?c(k("form"),v,l("("),Q,l(")"),q,h,w):"module"==a?c(k("form"),v,pa,w,h):"class"==a?c(k("form"),qa,ra,h):"export"==a?c(k("form"),sa,h):"import"==a?c(k("form"),ta,h):g(k("stat"),m,l(";"),h)}function m(a){return $(a,
!1)}function s(a){return $(a,!0)}function $(a,b){if(f.state.fatArrowAt==f.stream.start){var e=b?aa:ba;if("("==a)return c(v,k(")"),D(y,")"),h,l("\x3d\x3e"),e,w);if("variable"==a)return g(v,y,l("\x3d\x3e"),e,w)}e=b?R:H;return ca.hasOwnProperty(a)?c(e):"function"==a?c(x,e):"keyword c"==a?c(b?ua:S):"("==a?c(k(")"),S,I,l(")"),h,e):"operator"==a||"spread"==a?c(b?s:m):"["==a?c(k("]"),va,h,e):"{"==a?z(da,"}",null,e):"quasi"==a?g(J,e):c()}function S(a){return a.match(/[;\}\)\],]/)?g():g(m)}function ua(a){return a.match(/[;\}\)\],]/)?
g():g(s)}function H(a,b){return","==a?c(m):R(a,b,!1)}function R(a,b,e){var d=!1==e?H:R,f=!1==e?m:s;if("\x3d\x3e"==b)return c(v,e?aa:ba,w);if("operator"==a)return/\+\+|--/.test(b)?c(d):"?"==b?c(m,l(":"),f):c(f);if("quasi"==a)return g(J,d);if(";"!=a){if("("==a)return z(s,")","call",d);if("."==a)return c(wa,d);if("["==a)return c(k("]"),S,l("]"),h,d)}}function J(a,b){return"quasi"!=a?g():"${"!=b.slice(b.length-2)?c(J):c(m,xa)}function xa(a){if("}"==a)return f.marked="string-2",f.state.tokenize=M,c(J)}
function ba(a){N(f.stream,f.state);return"{"==a?g(q):g(m)}function aa(a){N(f.stream,f.state);return"{"==a?g(q):g(s)}function oa(a){return":"==a?c(h,q):g(H,l(";"),h)}function wa(a){if("variable"==a)return f.marked="property",c()}function da(a,b){if("variable"==a){if(f.marked="property","get"==b||"set"==b)return c(ya)}else if("number"==a||"string"==a)f.marked=G?"property":a+" property";else if("["==a)return c(m,l("]"),T);if(ca.hasOwnProperty(a))return c(T)}function ya(a){if("variable"!=a)return g(T);
f.marked="property";return c(x)}function T(a){if(":"==a)return c(s);if("("==a)return g(x)}function D(a,b){function e(d){return","==d?(d=f.state.lexical,"call"==d.info&&(d.pos=(d.pos||0)+1),c(a,e)):d==b?c():c(l(b))}return function(d){return d==b?c():g(a,e)}}function z(a,b,e){for(var d=3;d<arguments.length;d++)f.cc.push(arguments[d]);return c(k(b,e),D(a,b),h)}function P(a){return"}"==a?c():g(q,P)}function ea(a){if(fa&&":"==a)return c(za)}function za(a){if("variable"==a)return f.marked="variable-3",
c()}function O(){return g(y,ea,U,Aa)}function y(a,b){if("variable"==a)return u(b),c();if("["==a)return z(y,"]");if("{"==a)return z(Ba,"}")}function Ba(a,b){if("variable"==a&&!f.stream.match(/^\s*:/,!1))return u(b),c(U);"variable"==a&&(f.marked="property");return c(l(":"),y,U)}function U(a,b){if("\x3d"==b)return c(s)}function Aa(a){if(","==a)return c(O)}function Y(a,b){if("keyword b"==a&&"else"==b)return c(k("form","else"),q,h)}function Z(a){if("("==a)return c(k(")"),Ca,l(")"),h)}function Ca(a){return"var"==
a?c(O,l(";"),K):";"==a?c(K):"variable"==a?c(Da):g(m,l(";"),K)}function Da(a,b){return"in"==b||"of"==b?(f.marked="keyword",c(m)):c(H,K)}function K(a,b){return";"==a?c(ga):"in"==b||"of"==b?(f.marked="keyword",c(m)):g(m,l(";"),ga)}function ga(a){")"!=a&&c(m)}function x(a,b){if("*"==b)return f.marked="keyword",c(x);if("variable"==a)return u(b),c(x);if("("==a)return c(v,k(")"),D(Q,")"),h,q,w)}function Q(a){return"spread"==a?c(Q):g(y,ea)}function qa(a,b){if("variable"==a)return u(b),c(Ea)}function Ea(a,
b){if("extends"==b)return c(m)}function ra(a){if("{"==a)return z(da,"}")}function pa(a,b){if("string"==a)return c(q);if("variable"==a)return u(b),c(V)}function sa(a,b){return"*"==b?(f.marked="keyword",c(V,l(";"))):"default"==b?(f.marked="keyword",c(m,l(";"))):g(q)}function ta(a){return"string"==a?c():g(ha,V)}function ha(a,b){if("{"==a)return z(ha,"}");"variable"==a&&u(b);return c()}function V(a,b){if("from"==b)return f.marked="keyword",c(m)}function va(a){return"]"==a?c():g(s,Fa)}function Fa(a){return"for"==
a?g(I,l("]")):","==a?c(D(s,"]")):g(D(s,"]"))}function I(a){if("for"==a)return c(Z,I);if("if"==a)return c(m,I)}var A=ja.indentUnit,ia=r.statementIndent,G=r.jsonld,B=r.json||G,fa=r.typescript,W=function(){function a(a){return{type:a,style:"keyword"}}var b=a("keyword a"),e=a("keyword b"),d=a("keyword c"),c=a("operator"),f={type:"atom",style:"atom"},b={"if":a("if"),"while":b,"with":b,"else":e,"do":e,"try":e,"finally":e,"return":d,"break":d,"continue":d,"new":d,"delete":d,"throw":d,"debugger":d,"var":a("var"),
"const":a("var"),let:a("var"),"function":a("function"),"catch":a("catch"),"for":a("for"),"switch":a("switch"),"case":a("case"),"default":a("default"),"in":c,"typeof":c,"instanceof":c,"true":f,"false":f,"null":f,undefined:f,NaN:f,Infinity:f,"this":a("this"),module:a("module"),"class":a("class"),"super":a("atom"),yield:d,"export":a("export"),"import":a("import"),"extends":d};if(fa){var e={type:"variable",style:"variable-3"},e={"interface":a("interface"),"extends":a("extends"),constructor:a("constructor"),
"public":a("public"),"private":a("private"),"protected":a("protected"),"static":a("static"),string:e,number:e,bool:e,any:e},g;for(g in e)b[g]=e[g]}return b}(),L=/[+\-*&%=<>!?|~^]/,la=/^@(context|id|value|language|type|container|list|set|reverse|index|base|vocab|graph)"/,C,E,ma="([{}])",ca={atom:!0,number:!0,variable:!0,string:!0,regexp:!0,"this":!0,"jsonld-keyword":!0},f={state:null,column:null,marked:null,cc:null},na={name:"this",next:{name:"arguments"}};h.lex=!0;return{startState:function(a){a=
{tokenize:t,lastType:"sof",cc:[],lexical:new X((a||0)-A,0,"block",!1),localVars:r.localVars,context:r.localVars&&{vars:r.localVars},indented:0};r.globalVars&&"object"==typeof r.globalVars&&(a.globalVars=r.globalVars);return a},token:function(a,b){a.sol()&&(b.lexical.hasOwnProperty("align")||(b.lexical.align=!1),b.indented=a.indentation(),N(a,b));if(b.tokenize!=F&&a.eatSpace())return null;var e=b.tokenize(a,b);if("comment"==C)return e;b.lastType="operator"==C&&("++"==E||"--"==E)?"incdec":C;a:{var d=
C,c=E,g=b.cc;f.state=b;f.stream=a;f.marked=null;f.cc=g;b.lexical.hasOwnProperty("align")||(b.lexical.align=!0);for(;;)if((g.length?g.pop():B?m:q)(d,c)){for(;g.length&&g[g.length-1].lex;)g.pop()();if(f.marked){e=f.marked;break a}if(d="variable"==d)b:{for(d=b.localVars;d;d=d.next)if(d.name==c){d=!0;break b}for(g=b.context;g;g=g.prev)for(d=g.vars;d;d=d.next)if(d.name==c){d=!0;break b}d=void 0}if(d){e="variable-2";break a}break a}e=void 0}return e},indent:function(a,b){if(a.tokenize==F)return p.Pass;
if(a.tokenize!=t)return 0;var c=b&&b.charAt(0),d=a.lexical;if(!/^\s*else\b/.test(b))for(var f=a.cc.length-1;0<=f;--f){var g=a.cc[f];if(g==h)d=d.prev;else if(g!=Y)break}"stat"==d.type&&"}"==c&&(d=d.prev);ia&&(")"==d.type&&"stat"==d.prev.type)&&(d=d.prev);f=d.type;g=c==f;return"vardef"==f?d.indented+("operator"==a.lastType||","==a.lastType?d.info+1:0):"form"==f&&"{"==c?d.indented:"form"==f?d.indented+A:"stat"==f?d.indented+("operator"==a.lastType||","==a.lastType?ia||A:0):"switch"==d.info&&!g&&!1!=
r.doubleIndentSwitch?d.indented+(/^(?:case|default)\b/.test(b)?A:2*A):d.align?d.column+(g?0:1):d.indented+(g?0:A)},electricChars:":{}",blockCommentStart:B?null:"/*",blockCommentEnd:B?null:"*/",lineComment:B?null:"//",fold:"brace",helperType:B?"json":"javascript",jsonldMode:G,jsonMode:B}});p.registerHelper("wordChars","javascript",/[\\w$]/);p.defineMIME("text/javascript","javascript");p.defineMIME("text/ecmascript","javascript");p.defineMIME("application/javascript","javascript");p.defineMIME("application/ecmascript",
"javascript");p.defineMIME("application/json",{name:"javascript",json:!0});p.defineMIME("application/x-json",{name:"javascript",json:!0});p.defineMIME("application/ld+json",{name:"javascript",jsonld:!0});p.defineMIME("text/typescript",{name:"javascript",typescript:!0});p.defineMIME("application/typescript",{name:"javascript",typescript:!0})});
//# sourceMappingURL=javascript.js.map