//>>built
(function(m){"object"==typeof exports&&"object"==typeof module?m(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define("codemirror4/mode/erlang/erlang",["../../lib/codemirror"],m):m(CodeMirror)})(function(m){m.defineMIME("text/x-erlang","erlang");m.defineMode("erlang",function(z){function A(a,b){if(b.in_string)return b.in_string=!q(a,'"',"\\"),c(b,a,"string");if(b.in_atom)return b.in_atom=!q(a,"'","\\"),c(b,a,"atom");if(a.eatSpace())return c(b,a,"whitespace");if(!p(b)&&a.match(/-\s*[a-z\u00df-\u00f6\u00f8-\u00ff][\w\u00d8-\u00de\u00c0-\u00d6\u00df-\u00f6\u00f8-\u00ff]*/))return h(a.current(),
B)?c(b,a,"type"):c(b,a,"attribute");var d=a.next();if("%"==d)return a.skipToEnd(),c(b,a,"comment");if(":"==d)return c(b,a,"colon");if("?"==d)return a.eatSpace(),a.eatWhile(r),c(b,a,"macro");if("#"==d)return a.eatSpace(),a.eatWhile(r),c(b,a,"record");if("$"==d)return"\\"==a.next()&&!a.match(C)?c(b,a,"error"):c(b,a,"number");if("."==d)return c(b,a,"dot");if("'"==d){if(!(b.in_atom=!q(a,"'","\\"))){if(a.match(/\s*\/\s*[0-9]/,!1))return a.match(/\s*\/\s*[0-9]/,!0),c(b,a,"fun");if(a.match(/\s*\(/,!1)||
a.match(/\s*:/,!1))return c(b,a,"function")}return c(b,a,"atom")}if('"'==d)return b.in_string=!q(a,'"',"\\"),c(b,a,"string");if(/[A-Z_\u00d8-\u00de\u00c0-\u00d6]/.test(d))return a.eatWhile(r),c(b,a,"variable");if(/[a-z_\u00df-\u00f6\u00f8-\u00ff]/.test(d)){a.eatWhile(r);if(a.match(/\s*\/\s*[0-9]/,!1))return a.match(/\s*\/\s*[0-9]/,!0),c(b,a,"fun");d=a.current();if(h(d,D))return c(b,a,"keyword");if(h(d,v))return c(b,a,"operator");if(a.match(/\s*\(/,!1))return h(d,E)&&(":"!=p(b).token||"erlang"==p(b,
2).token)?c(b,a,"builtin"):h(d,F)?c(b,a,"guard"):c(b,a,"function");if(h(d,v))return c(b,a,"operator");var g=a.match(/([\n\s]+|%[^\n]*\n)*(.)/,!1);return":"==(g?g.pop():"")?"erlang"==d?c(b,a,"builtin"):c(b,a,"function"):h(d,["true","false"])?c(b,a,"boolean"):h(d,["true","false"])?c(b,a,"boolean"):c(b,a,"atom")}var g=/[0-9]/,e=/[0-9a-zA-Z]/;return g.test(d)?(a.eatWhile(g),a.eat("#")?a.eatWhile(e)||a.backUp(1):a.eat(".")&&(a.eatWhile(g)?a.eat(/[eE]/)&&(a.eat(/[-+]/)?a.eatWhile(g)||a.backUp(2):a.eatWhile(g)||
a.backUp(1)):a.backUp(1)),c(b,a,"number")):w(a,G,t)?c(b,a,"open_paren"):w(a,H,x)?c(b,a,"close_paren"):y(a,I,J)?c(b,a,"separator"):y(a,K,L)?c(b,a,"operator"):c(b,a,null)}function w(a,b,d){if(1==a.current().length&&b.test(a.current())){for(a.backUp(1);b.test(a.peek());)if(a.next(),h(a.current(),d))return!0;a.backUp(a.current().length-1)}return!1}function y(a,b,d){if(1==a.current().length&&b.test(a.current())){for(;b.test(a.peek());)a.next();for(;0<a.current().length;){if(h(a.current(),d))return!0;a.backUp(1)}a.next()}return!1}
function q(a,b,d){for(;!a.eol();){var g=a.next();if(g==b)return!0;g==d&&a.next()}return!1}function h(a,b){return-1<b.indexOf(a)}function c(a,b,d){var g;g=b.current();var c=b.column();b=b.indentation();g={token:g,column:c,indent:b,type:d};"comment"==g.type||"whitespace"==g.type||(c=a.tokenStack,b=c.length-1,0<b&&"record"===c[b].type&&"dot"===g.type?c.pop():(0<b&&"group"===c[b].type&&c.pop(),c.push(g)),a.tokenStack=c,a.tokenStack=M(a.tokenStack));switch(d){case "atom":return"atom";case "attribute":return"attribute";
case "boolean":return"atom";case "builtin":return"builtin";case "close_paren":return null;case "colon":return null;case "comment":return"comment";case "dot":return null;case "error":return"error";case "fun":return"meta";case "function":return"tag";case "guard":return"property";case "keyword":return"keyword";case "macro":return"variable-2";case "number":return"number";case "open_paren":return null;case "operator":return"operator";case "record":return"bracket";case "separator":return null;case "string":return"string";
case "type":return"def";case "variable":return"variable";default:return null}}function p(a,b){var d=a.tokenStack.length,c=b?b:1;return d<c?!1:a.tokenStack[d-c]}function M(a){var b=a.length-1;if("dot"===a[b].type)return[];if("fun"===a[b].type&&"fun"===a[b-1].token)return a.slice(0,b-1);switch(a[a.length-1].token){case "}":return l(a,{g:["{"]});case "]":return l(a,{i:["["]});case ")":return l(a,{i:["("]});case "\x3e\x3e":return l(a,{i:["\x3c\x3c"]});case "end":return l(a,{i:"begin case fun if receive try".split(" ")});
case ",":return l(a,{e:"begin try when -\x3e , ( [ { \x3c\x3c".split(" ")});case "-\x3e":return l(a,{r:["when"],m:["try","if","case","receive"]});case ";":return l(a,{E:"case fun if receive try when".split(" ")});case "catch":return l(a,{e:["try"]});case "of":return l(a,{e:["case"]});case "after":return l(a,{e:["receive","try"]});default:return a}}function l(a,b){for(var d in b)for(var c=a.length-1,e=b[d],f=c-1;-1<f;f--)if(h(a[f].token,e)){var k=a.slice(0,f);switch(d){case "m":return k.concat(a[f]).concat(a[c]);
case "r":return k.concat(a[c]);case "i":return k;case "g":return k.concat({token:"group",column:0,indent:0,type:"group"});case "E":return k.concat(a[f]);case "e":return k.concat(a[f])}}return"E"==d?[]:a}function N(a,b){var d,c=z.indentUnit,e;e=b.match(/,|[a-z]+|\}|\]|\)|>>|\|+|\(/);e=n(e)&&0===e.index?e[0]:"";var f=p(a,1),k=p(a,2);if(a.in_string||a.in_atom)return m.Pass;if(k){if("when"==f.token)return f.column+c;if("when"===e&&"function"===k.type)return k.indent+c;if("("===e&&"fun"===f.token)return f.column+
3;if("catch"===e&&(d=u(a,["try"])))return d.column;if(h(e,["end","after","of"]))return(d=u(a,"begin case fun if receive try".split(" ")))?d.column:m.Pass;if(h(e,x))return(d=u(a,t))?d.column:m.Pass;if(h(f.token,[",","|","||"])||h(e,[",","|","||"]))return d=a.tokenStack.slice(0,-1),e=s(d,"type",["open_paren"]),(d=n(d[e])?d[e]:!1)?d.column+d.token.length:c;if("-\x3e"==f.token)return h(k.token,["receive","case","if","try"])?k.column+c+c:k.column+c;if(h(f.token,t))return f.column+f.token.length;d=a.tokenStack;
e=s(d,"type",["open_paren","separator","keyword"]);f=s(d,"type",["operator"]);d=n(e)&&n(f)&&e<f?d[e+1]:n(e)?d[e]:!1;return n(d)?d.column+c:0}return 0}function u(a,b){var d=a.tokenStack,c=s(d,"token",b);return n(d[c])?d[c]:!1}function s(a,b,d){for(var c=a.length-1;-1<c;c--)if(h(a[c][b],d))return c;return!1}function n(a){return!1!==a&&null!=a}var B=["-type","-spec","-export_type","-opaque"],D="after begin catch case cond end fun if let of query receive try when".split(" "),I=/[\->,;]/,J=["-\x3e",";",
","],v="and andalso band bnot bor bsl bsr bxor div not or orelse rem xor".split(" "),K=/[\+\-\*\/<>=\|:!]/,L="\x3d + - * / \x3e \x3e\x3d \x3c \x3d\x3c \x3d:\x3d \x3d\x3d \x3d/\x3d /\x3d || \x3c- !".split(" "),G=/[<\(\[\{]/,t=["\x3c\x3c","(","[","{"],H=/[>\)\]\}]/,x=["}","]",")","\x3e\x3e"],F="is_atom is_binary is_bitstring is_boolean is_float is_function is_integer is_list is_number is_pid is_port is_record is_reference is_tuple atom binary bitstring boolean function integer list number pid port record reference tuple".split(" "),
E="abs adler32 adler32_combine alive apply atom_to_binary atom_to_list binary_to_atom binary_to_existing_atom binary_to_list binary_to_term bit_size bitstring_to_list byte_size check_process_code contact_binary crc32 crc32_combine date decode_packet delete_module disconnect_node element erase exit float float_to_list garbage_collect get get_keys group_leader halt hd integer_to_list internal_bif iolist_size iolist_to_binary is_alive is_atom is_binary is_bitstring is_boolean is_float is_function is_integer is_list is_number is_pid is_port is_process_alive is_record is_reference is_tuple length link list_to_atom list_to_binary list_to_bitstring list_to_existing_atom list_to_float list_to_integer list_to_pid list_to_tuple load_module make_ref module_loaded monitor_node node node_link node_unlink nodes notalive now open_port pid_to_list port_close port_command port_connect port_control pre_loaded process_flag process_info processes purge_module put register registered round self setelement size spawn spawn_link spawn_monitor spawn_opt split_binary statistics term_to_binary time throw tl trunc tuple_size tuple_to_list unlink unregister whereis".split(" "),
r=/[\w@\u00d8-\u00de\u00c0-\u00d6\u00df-\u00f6\u00f8-\u00ff]/,C=/[0-7]{1,3}|[bdefnrstv\\"']|\^[a-zA-Z]|x[0-9a-zA-Z]{2}|x{[0-9a-zA-Z]+}/;return{startState:function(){return{tokenStack:[],in_string:!1,in_atom:!1}},token:function(a,b){return A(a,b)},indent:function(a,b){return N(a,b)},lineComment:"%"}})});
//# sourceMappingURL=erlang.js.map