//>>built
(function(n){"object"==typeof exports&&"object"==typeof module?n(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define("codemirror4/mode/rust/rust",["../../lib/codemirror"],n):n(CodeMirror)})(function(n){n.defineMode("rust",function(){function p(a,b){v=a;return b}function n(a,b){var e=a.next();if('"'==e)return b.tokenize=V,b.tokenize(a,b);if("'"==e){v="atom";if(a.eat("\\"))return a.skipTo("'")?(a.next(),"string"):"error";a.next();return a.eat("'")?"string":"error"}if("/"==
e){if(a.eat("/"))return a.skipToEnd(),"comment";if(a.eat("*"))return b.tokenize=E(1),b.tokenize(a,b)}if("#"==e){if(a.eat("["))return v="open-attr",null;a.eatWhile(/\w/);return p("macro","meta")}if(":"==e&&a.match(":\x3c"))return p("op",null);if(e.match(/\d/)||"."==e&&a.eat(/\d/))return e=!1,!a.match(/^x[\da-f]+/i)&&!a.match(/^b[01]+/)&&(a.eatWhile(/\d/),a.eat(".")&&(e=!0,a.eatWhile(/\d/)),a.match(/^e[+\-]?\d+/i)&&(e=!0)),e?a.match(/^f(?:32|64)/):a.match(/^[ui](?:8|16|32|64)/),p("atom","number");if(e.match(/[()\[\]{}:;,]/))return p(e,
null);if("-"==e&&a.eat("\x3e"))return p("-\x3e",null);if(e.match(K))return a.eatWhile(K),p("op",null);a.eatWhile(/\w/);c=a.current();return a.match(/^::\w/)?(a.backUp(1),p("prefix","variable-2")):b.keywords.propertyIsEnumerable(c)?p(b.keywords[c],c.match(/true|false/)?"atom":"keyword"):p("name","variable")}function V(a,b){for(var e,c=!1;e=a.next();){if('"'==e&&!c)return b.tokenize=n,p("atom","string");c=!c&&"\\"==e}return p("op","string")}function E(a){return function(b,e){for(var c=null,d;d=b.next();){if("/"==
d&&"*"==c)if(1==a){e.tokenize=n;break}else return e.tokenize=E(a-1),e.tokenize(b,e);if("*"==d&&"/"==c)return e.tokenize=E(a+1),e.tokenize(b,e);c=d}return"comment"}}function f(){for(var a=arguments.length-1;0<=a;a--)d.cc.push(arguments[a])}function b(){f.apply(null,arguments);return!0}function h(a,b){var e=function(){var e=d.state;e.lexical={indented:e.indented,column:d.stream.column(),type:a,prev:e.lexical,info:b}};e.lex=!0;return e}function g(){var a=d.state;a.lexical.prev&&(")"==a.lexical.type&&
(a.indented=a.lexical.indented),a.lexical=a.lexical.prev)}function s(){d.state.keywords=W}function t(){d.state.keywords=L}function u(a,c){function e(d){return","==d?b(a,e):d==c?b():b(e)}return function(d){return d==c?b():f(a,e)}}function w(a,c){return b(h("stat",c),a,g,m)}function m(a){return"}"==a?b():"let"==a?w(A,"let"):"fn"==a?w(r):"type"==a?b(h("stat"),B,F,g,m):"enum"==a?w(C):"mod"==a?w(M):"iface"==a?w(G):"impl"==a?w(D):"open-attr"==a?b(h("]"),u(k,"]"),g):"ignore"==a||a.match(/[\]\);,]/)?b(m):
f(h("stat"),k,g,F,m)}function F(a){return";"==a?b():f()}function k(a){return"atom"==a||"name"==a?b(H):"{"==a?b(h("}"),X,g):a.match(/[\[\(]/)?y(a,k):a.match(/[\]\)\};,]/)?f():"if-style"==a?b(k,k):"else-style"==a||"op"==a?b(k):"for"==a?b(x,N,Y,k,k):"alt"==a?b(k,Z):"fn"==a?b(r):"macro"==a?b($):b()}function H(a){return"."==c?b(aa):"::\x3c"==c?b(q,H):"op"==a||":"==c?b(k):"("==a||"["==a?y(a,k):f()}function aa(){return c.match(/^\w+$/)?(d.marked="variable",b(H)):f(k)}function X(a){if("op"==a){if("|"==c)return b(I,
g,h("}","block"),m);if("||"==c)return b(g,h("}","block"),m)}return"mutable"==c||c.match(/^\w+$/)&&":"==d.stream.peek()&&!d.stream.match("::",!1)?f(O(k)):f(m)}function O(a){function f(e){return"mutable"==c||"with"==c?(d.marked="keyword",b(f)):c.match(/^\w*$/)?(d.marked="variable",b(f)):":"==e?b(a,f):"}"==e?b():b(f)}return f}function I(a){return"name"==a?(d.marked="def",b(I)):"op"==a&&"|"==c?b():b(I)}function A(a){return a.match(/[\]\)\};]/)?b():"\x3d"==c?b(k,P):","==a?b(A):f(x,N,A)}function P(a){return a.match(/[\]\)\};,]/)?
f(A):f(k,P)}function N(a){return":"==a?b(s,l,t):f()}function Y(a){return"name"==a&&"in"==c?(d.marked="keyword",b()):f()}function r(a){return"@"==c||"~"==c?(d.marked="keyword",b(r)):"name"==a?(d.marked="def",b(r)):"\x3c"==c?b(q,r):"{"==a?f(k):"("==a?b(h(")"),u(Q,")"),g,r):"-\x3e"==a?b(s,l,t,r):";"==a?b():b(r)}function B(a){return"name"==a?(d.marked="def",b(B)):"\x3c"==c?b(q,B):"\x3d"==c?b(s,l,t):b(B)}function C(a){return"name"==a?(d.marked="def",b(C)):"\x3c"==c?b(q,C):"\x3d"==c?b(s,l,t,F):"{"==a?b(h("}"),
s,J,t,g):b(C)}function J(a){if("}"==a)return b();if("("==a)return b(h(")"),u(l,")"),g,J);c.match(/^\w+$/)&&(d.marked="def");return b(J)}function M(a){return"name"==a?(d.marked="def",b(M)):"{"==a?b(h("}"),m,g):f()}function G(a){return"name"==a?(d.marked="def",b(G)):"\x3c"==c?b(q,G):"{"==a?b(h("}"),m,g):f()}function D(a){return"\x3c"==c?b(q,D):"of"==c||"for"==c?(d.marked="keyword",b(l,D)):"name"==a?(d.marked="def",b(D)):"{"==a?b(h("}"),m,g):f()}function q(){return"\x3e"==c?b():","==c?b(q):":"==c?b(l,
q):f(l,q)}function Q(a){return"name"==a?(d.marked="def",b(Q)):":"==a?b(s,l,t):f()}function l(a){return"name"==a?(d.marked="variable-3",b(R)):"mutable"==c?(d.marked="keyword",b(l)):"atom"==a?b(R):"op"==a||"obj"==a?b(l):"fn"==a?b(S):"{"==a?b(h("{"),O(l),g):y(a,l)}function R(){return"\x3c"==c?b(q):f()}function S(a){return"("==a?b(h("("),u(l,")"),g,S):"-\x3e"==a?b(l):f()}function x(a){return"name"==a?(d.marked="def",b(T)):"atom"==a?b(T):"op"==a?b(x):a.match(/[\]\)\};,]/)?f():y(a,x)}function T(a){return"op"==
a&&"."==c?b():"to"==c?(d.marked="keyword",b(x)):f()}function Z(a){return"{"==a?b(h("}","alt"),z,g):f()}function z(a){return"}"==a?b():"|"==a?b(z):"when"==c?(d.marked="keyword",b(k,U)):a.match(/[\]\);,]/)?b(z):f(x,U)}function U(a){return"{"==a?b(h("}","alt"),m,g,z):f(z)}function $(a){return a.match(/[\[\(\{]/)?y(a,k):f()}function y(a,c){return"["==a?b(h("]"),u(c,"]"),g):"("==a?b(h(")"),u(c,")"),g):"{"==a?b(h("}"),u(c,"}"),g):b()}var L={"if":"if-style","while":"if-style","else":"else-style","do":"else-style",
ret:"else-style",fail:"else-style","break":"atom",cont:"atom","const":"let",resource:"fn",let:"let",fn:"fn","for":"for",alt:"alt",iface:"iface",impl:"impl",type:"type","enum":"enum",mod:"mod",as:"op","true":"atom","false":"atom",assert:"op",check:"op",claim:"op","native":"ignore",unsafe:"ignore","import":"else-style","export":"else-style",copy:"op",log:"op",log_err:"op",use:"op",bind:"op",self:"atom"},W=function(){for(var a={fn:"fn",block:"fn",obj:"obj"},b="bool uint int i8 i16 i32 i64 u8 u16 u32 u64 float f32 f64 str char".split(" "),
c=0,d=b.length;c<d;++c)a[b[c]]="atom";return a}(),K=/[+\-*&%=<>!?|\.@]/,v,c,d={state:null,stream:null,marked:null,cc:null};g.lex=s.lex=t.lex=!0;return{startState:function(){return{tokenize:n,cc:[],lexical:{indented:-4,column:0,type:"top",align:!1},keywords:L,indented:0}},token:function(a,b){a.sol()&&(b.lexical.hasOwnProperty("align")||(b.lexical.align=!1),b.indented=a.indentation());if(a.eatSpace())return null;v=c=null;var e=b.tokenize(a,b);if("comment"==e)return e;b.lexical.hasOwnProperty("align")||
(b.lexical.align=!0);if("prefix"==v)return e;c||(c=a.current());a:{var f=b.cc;d.state=b;d.stream=a;d.marked=null;for(d.cc=f;;)if((f.length?f.pop():m)(v)){for(;f.length&&f[f.length-1].lex;)f.pop()();e=d.marked||e;break a}e=void 0}return e},indent:function(a,b){if(a.tokenize!=n)return 0;var c=b&&b.charAt(0),d=a.lexical,f=d.type,c=c==f;return"stat"==f?d.indented+4:d.align?d.column+(c?0:1):d.indented+(c?0:"alt"==d.info?2:4)},electricChars:"{}",blockCommentStart:"/*",blockCommentEnd:"*/",lineComment:"//",
fold:"brace"}});n.defineMIME("text/x-rustsrc","rust")});
//# sourceMappingURL=rust.js.map